In [1]:
import warnings
warnings.filterwarnings("ignore")
# Libraries to read and manipulate data
import pandas as pd
import numpy as np

# libraries to help with data visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Libraries to tune model, get different metric scores, and split data
from sklearn import metrics
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.metrics import accuracy_score, classification_report
from sklearn.impute import KNNImputer
from sklearn.pipeline import Pipeline, make_pipeline
from statsmodels.api import OLS, add_constant

#libraries to help with model building
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import (
    AdaBoostClassifier,
    GradientBoostingClassifier,
    RandomForestClassifier,
    BaggingClassifier)
from xgboost import XGBClassifier

#libraries for convenience
from datetime import datetime
pd.set_option('display.float_format', lambda x: '%.3f' % x)

In [2]:
All_Players = pd.read_csv('../Resources/All_player_data.csv')
All_Players = All_Players.drop(['Unnamed: 0'],axis= 1)

In [3]:
All_Players

,GAME_DATE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,MIN,2pointer_MADE,2pointer_ATTEMPTS,...,FreeThrow_PCT,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,2022-03-12,22101005,1610612750,MIN,Minnesota,1630162,Anthony Edwards,36:22,4.000,10.000,...,1.000,0.000,8.000,8.000,5.000,3.000,1.000,1.000,1.000,15.000
1,2022-03-12,22101005,1610612750,MIN,Minnesota,1630183,Jaden McDaniels,23:54,6.000,8.000,...,1.000,2.000,4.000,6.000,0.000,0.000,2.000,2.000,6.000,14.000
2,2022-03-12,22101005,1610612750,MIN,Minnesota,1626157,Karl-Anthony Towns,25:17,4.000,9.000,...,0.750,1.000,9.000,10.000,0.000,0.000,0.000,3.000,4.000,15.000
3,2022-03-12,22101005,1610612750,MIN,Minnesota,1627736,Malik Beasley,30:52,4.000,9.000,...,0.000,0.000,3.000,3.000,1.000,1.000,0.000,1.000,4.000,12.000
4,2022-03-12,22101005,1610612750,MIN,Minnesota,1626156,D'Angelo Russell,33:46,3.000,13.000,...,1.000,0.000,6.000,6.000,9.000,1.000,0.000,5.000,0.000,14.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540345,2012-10-06,11200005,1610612743,DEN,Denver,202706,Jordan Hamilton,19,4.000,9.000,...,0.857,0.000,2.000,2.000,0.000,2.000,0.000,1.000,3.000,17.000
540346,2012-10-06,11200005,1610612743,DEN,Denver,202702,Kenneth Faried,23,7.000,11.000,...,1.000,1.000,0.000,1.000,1.000,1.000,0.000,3.000,3.000,18.000
540347,2012-10-06,11200005,1610612743,DEN,Denver,201585,Kosta Koufos,15,3.000,7.000,...,0.000,3.000,5.000,8.000,0.000,1.000,0.000,0.000,3.000,6.000
540348,2012-10-06,11200005,1610612743,DEN,Denver,202389,Timofey Mozgov,19,1.000,1.000,...,0.000,1.000,2.000,3.000,1.000,0.000,0.000,4.000,2.000,2.000
540349,2012-10-06,11200005,1610612743,DEN,Denver,201951,Ty Lawson,27,3.000,6.000,...,0.500,0.000,2.000,2.000,6.000,2.000,0.000,6.000,1.000,8.000