In [1]:
import pandas as pd
import numpy as np

In [2]:
games_details_data = pd.read_csv("../resources/games_details.csv")
games_details_data.head()

C:\Users\kevin\anaconda3\envs\PythonData\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (6) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,NICKNAME,START_POSITION,COMMENT,MIN,...,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
0,22101005,1610612750,MIN,Minnesota,1630162,Anthony Edwards,Anthony,F,NaN,36:22,...,0.0,8.0,8.0,5.0,3.0,1.0,1.0,1.0,15.0,5.0
1,22101005,1610612750,MIN,Minnesota,1630183,Jaden McDaniels,Jaden,F,NaN,23:54,...,2.0,4.0,6.0,0.0,0.0,2.0,2.0,6.0,14.0,10.0
2,22101005,1610612750,MIN,Minnesota,1626157,Karl-Anthony Towns,Karl-Anthony,C,NaN,25:17,...,1.0,9.0,10.0,0.0,0.0,0.0,3.0,4.0,15.0,14.0
3,22101005,1610612750,MIN,Minnesota,1627736,Malik Beasley,Malik,G,NaN,30:52,...,0.0,3.0,3.0,1.0,1.0,0.0,1.0,4.0,12.0,20.0
4,22101005,1610612750,MIN,Minnesota,1626156,D'Angelo Russell,D'Angelo,G,NaN,33:46,...,0.0,6.0,6.0,9.0,1.0,0.0,5.0,0.0,14.0,17.0

In [3]:
games_details_df = games_details_data.copy()

In [4]:
games_details_df.dtypes

GAME_ID                int64
TEAM_ID                int64
TEAM_ABBREVIATION     object
TEAM_CITY             object
PLAYER_ID              int64
PLAYER_NAME           object
NICKNAME              object
START_POSITION        object
COMMENT               object
MIN                   object
FGM                  float64
FGA                  float64
FG_PCT               float64
FG3M                 float64
FG3A                 float64
FG3_PCT              float64
FTM                  float64
FTA                  float64
FT_PCT               float64
OREB                 float64
DREB                 float64
REB                  float64
AST                  float64
STL                  float64
BLK                  float64
TO                   float64
PF                   float64
PTS                  float64
PLUS_MINUS           float64
dtype: object

In [5]:
games_details_df["COMMENT"].value_counts()

DNP - Coach's Decision                      54563
DNP - Coach's Decision                      30547
DND - Injury/Illness                         1267
DNP - Injury/Illness                         1151
DNP - Injury/Illness                          960
                                            ...
NWT - Ankle sprain                              1
DND - Strained rt. calf                         1
DND - Left Achilles Surgery.                    1
DND - Tendonitis Left Ankle                     1
DND - Non-Displaced Fracture, Left Fibul        1
Name: COMMENT, Length: 5348, dtype: int64

In [6]:
len(games_details_df)

645953

In [7]:
games_details_df.isnull().sum()

GAME_ID                   0
TEAM_ID                   0
TEAM_ABBREVIATION         0
TEAM_CITY                 0
PLAYER_ID                 0
PLAYER_NAME               0
NICKNAME             615591
START_POSITION       398738
COMMENT              540351
MIN                  105603
FGM                  105603
FGA                  105603
FG_PCT               105603
FG3M                 105603
FG3A                 105603
FG3_PCT              105603
FTM                  105603
FTA                  105603
FT_PCT               105603
OREB                 105603
DREB                 105603
REB                  105603
AST                  105603
STL                  105603
BLK                  105603
TO                   105603
PF                   105603
PTS                  105603
PLUS_MINUS           129264
dtype: int64

In [8]:
games_details_df = games_details_df.drop(columns = ['NICKNAME'])

games_details_df.head(10)

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,FGM,...,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
0,22101005,1610612750,MIN,Minnesota,1630162,Anthony Edwards,F,NaN,36:22,4.0,...,0.0,8.0,8.0,5.0,3.0,1.0,1.0,1.0,15.0,5.0
1,22101005,1610612750,MIN,Minnesota,1630183,Jaden McDaniels,F,NaN,23:54,6.0,...,2.0,4.0,6.0,0.0,0.0,2.0,2.0,6.0,14.0,10.0
2,22101005,1610612750,MIN,Minnesota,1626157,Karl-Anthony Towns,C,NaN,25:17,4.0,...,1.0,9.0,10.0,0.0,0.0,0.0,3.0,4.0,15.0,14.0
3,22101005,1610612750,MIN,Minnesota,1627736,Malik Beasley,G,NaN,30:52,4.0,...,0.0,3.0,3.0,1.0,1.0,0.0,1.0,4.0,12.0,20.0
4,22101005,1610612750,MIN,Minnesota,1626156,D'Angelo Russell,G,NaN,33:46,3.0,...,0.0,6.0,6.0,9.0,1.0,0.0,5.0,0.0,14.0,17.0
5,22101005,1610612750,MIN,Minnesota,1629675,Naz Reid,NaN,NaN,23:56,3.0,...,3.0,7.0,10.0,1.0,3.0,2.0,1.0,1.0,11.0,-7.0
6,22101005,1610612750,MIN,Minnesota,1629162,Jordan McLaughlin,NaN,NaN,21:00,2.0,...,0.0,1.0,1.0,3.0,3.0,0.0,0.0,1.0,5.0,-10.0
7,22101005,1610612750,MIN,Minnesota,1629669,Jaylen Nowell,NaN,NaN,21:35,6.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,16.0,-5.0
8,22101005,1610612750,MIN,Minnesota,1627752,Taurean Prince,NaN,NaN,22:53,3.0,...,0.0,2.0,2.0,1.0,1.0,0.0,1.0,2.0,11.0,1.0
9,22101005,1610612750,MIN,Minnesota,1629006,Josh Okogie,NaN,NaN,0:25,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
games_details_df.sample(n=10)

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,FGM,...,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
391825,41800202,1610612749,MIL,Milwaukee,1628391,D.J. Wilson,NaN,NaN,5:22,1.0,...,0.0,2.0,2.0,1.0,0.0,0.0,2.0,1.0,2.0,-8.0
58627,22000129,1610612749,MIL,Milwaukee,203648,Thanasis Antetokounmpo,NaN,NaN,13:20,1.0,...,3.0,2.0,5.0,0.0,0.0,0.0,0.0,3.0,2.0,-12.0
626996,21200642,1610612761,TOR,Toronto,203112,Quincy Acy,NaN,NaN,11:51,2.0,...,0.0,0.0,0.0,0.0,0.0,2.0,1.0,3.0,4.0,-1.0
533097,11500096,1610612764,WAS,Washington,2400,Drew Gooden,NaN,NaN,17:21,2.0,...,0.0,4.0,4.0,0.0,0.0,0.0,1.0,6.0,6.0,-8.0
398821,21800996,1610612753,ORL,Orlando,1626185,Jarell Martin,NaN,NaN,6:41,1.0,...,1.0,1.0,2.0,0.0,0.0,0.0,0.0,1.0,3.0,7.0
402084,21800870,1610612738,BOS,Boston,202694,Marcus Morris Sr.,F,NaN,31:02,4.0,...,1.0,5.0,6.0,2.0,0.0,0.0,0.0,2.0,11.0,4.0
246318,20400253,1610612762,UTA,Utah,2306,Carlos Arroyo,G,NaN,35:27,1.0,...,0.0,2.0,2.0,11.0,0.0,0.0,0.0,2.0,4.0,-28.0
497529,11600044,1610612755,PHI,Philadelphia,1882,Elton Brand,NaN,DNP - Coach's Decision,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
138941,20700457,1610612764,WAS,Washington,1498,Antonio Daniels,G,NaN,35:21,6.0,...,0.0,1.0,1.0,2.0,0.0,0.0,1.0,1.0,18.0,-4.0
95844,20800831,1610612749,MIL,Milwaukee,2124,Malik Allen,NaN,NaN,4:44,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,5.0

In [10]:
games_details_df['COMMENT'].value_counts()

DNP - Coach's Decision                      54563
DNP - Coach's Decision                      30547
DND - Injury/Illness                         1267
DNP - Injury/Illness                         1151
DNP - Injury/Illness                          960
                                            ...
NWT - Ankle sprain                              1
DND - Strained rt. calf                         1
DND - Left Achilles Surgery.                    1
DND - Tendonitis Left Ankle                     1
DND - Non-Displaced Fracture, Left Fibul        1
Name: COMMENT, Length: 5348, dtype: int64

In [11]:
new_details_df = games_details_df[games_details_df['COMMENT'].isnull()]

new_details_df.head(10)

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,FGM,...,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
0,22101005,1610612750,MIN,Minnesota,1630162,Anthony Edwards,F,NaN,36:22,4.0,...,0.0,8.0,8.0,5.0,3.0,1.0,1.0,1.0,15.0,5.0
1,22101005,1610612750,MIN,Minnesota,1630183,Jaden McDaniels,F,NaN,23:54,6.0,...,2.0,4.0,6.0,0.0,0.0,2.0,2.0,6.0,14.0,10.0
2,22101005,1610612750,MIN,Minnesota,1626157,Karl-Anthony Towns,C,NaN,25:17,4.0,...,1.0,9.0,10.0,0.0,0.0,0.0,3.0,4.0,15.0,14.0
3,22101005,1610612750,MIN,Minnesota,1627736,Malik Beasley,G,NaN,30:52,4.0,...,0.0,3.0,3.0,1.0,1.0,0.0,1.0,4.0,12.0,20.0
4,22101005,1610612750,MIN,Minnesota,1626156,D'Angelo Russell,G,NaN,33:46,3.0,...,0.0,6.0,6.0,9.0,1.0,0.0,5.0,0.0,14.0,17.0
5,22101005,1610612750,MIN,Minnesota,1629675,Naz Reid,NaN,NaN,23:56,3.0,...,3.0,7.0,10.0,1.0,3.0,2.0,1.0,1.0,11.0,-7.0
6,22101005,1610612750,MIN,Minnesota,1629162,Jordan McLaughlin,NaN,NaN,21:00,2.0,...,0.0,1.0,1.0,3.0,3.0,0.0,0.0,1.0,5.0,-10.0
7,22101005,1610612750,MIN,Minnesota,1629669,Jaylen Nowell,NaN,NaN,21:35,6.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,16.0,-5.0
8,22101005,1610612750,MIN,Minnesota,1627752,Taurean Prince,NaN,NaN,22:53,3.0,...,0.0,2.0,2.0,1.0,1.0,0.0,1.0,2.0,11.0,1.0
9,22101005,1610612750,MIN,Minnesota,1629006,Josh Okogie,NaN,NaN,0:25,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [12]:
len(new_details_df)

540351

In [13]:
new_details_df.isnull().sum()

GAME_ID                   0
TEAM_ID                   0
TEAM_ABBREVIATION         0
TEAM_CITY                 0
PLAYER_ID                 0
PLAYER_NAME               0
START_POSITION       293136
COMMENT              540351
MIN                       1
FGM                       1
FGA                       1
FG_PCT                    1
FG3M                      1
FG3A                      1
FG3_PCT                   1
FTM                       1
FTA                       1
FT_PCT                    1
OREB                      1
DREB                      1
REB                       1
AST                       1
STL                       1
BLK                       1
TO                        1
PF                        1
PTS                       1
PLUS_MINUS            23662
dtype: int64

In [14]:
new_details_df[new_details_df['MIN'].isna()]

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,FGM,...,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
460855,11700036,1610612758,SAC,Sacramento,204022,Jack Cooley,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
new_details_df = new_details_df[new_details_df['MIN'].notnull()]

new_details_df.head(10)

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,FGM,...,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
0,22101005,1610612750,MIN,Minnesota,1630162,Anthony Edwards,F,NaN,36:22,4.0,...,0.0,8.0,8.0,5.0,3.0,1.0,1.0,1.0,15.0,5.0
1,22101005,1610612750,MIN,Minnesota,1630183,Jaden McDaniels,F,NaN,23:54,6.0,...,2.0,4.0,6.0,0.0,0.0,2.0,2.0,6.0,14.0,10.0
2,22101005,1610612750,MIN,Minnesota,1626157,Karl-Anthony Towns,C,NaN,25:17,4.0,...,1.0,9.0,10.0,0.0,0.0,0.0,3.0,4.0,15.0,14.0
3,22101005,1610612750,MIN,Minnesota,1627736,Malik Beasley,G,NaN,30:52,4.0,...,0.0,3.0,3.0,1.0,1.0,0.0,1.0,4.0,12.0,20.0
4,22101005,1610612750,MIN,Minnesota,1626156,D'Angelo Russell,G,NaN,33:46,3.0,...,0.0,6.0,6.0,9.0,1.0,0.0,5.0,0.0,14.0,17.0
5,22101005,1610612750,MIN,Minnesota,1629675,Naz Reid,NaN,NaN,23:56,3.0,...,3.0,7.0,10.0,1.0,3.0,2.0,1.0,1.0,11.0,-7.0
6,22101005,1610612750,MIN,Minnesota,1629162,Jordan McLaughlin,NaN,NaN,21:00,2.0,...,0.0,1.0,1.0,3.0,3.0,0.0,0.0,1.0,5.0,-10.0
7,22101005,1610612750,MIN,Minnesota,1629669,Jaylen Nowell,NaN,NaN,21:35,6.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,16.0,-5.0
8,22101005,1610612750,MIN,Minnesota,1627752,Taurean Prince,NaN,NaN,22:53,3.0,...,0.0,2.0,2.0,1.0,1.0,0.0,1.0,2.0,11.0,1.0
9,22101005,1610612750,MIN,Minnesota,1629006,Josh Okogie,NaN,NaN,0:25,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [16]:
new_details_df.isnull().sum()

GAME_ID                   0
TEAM_ID                   0
TEAM_ABBREVIATION         0
TEAM_CITY                 0
PLAYER_ID                 0
PLAYER_NAME               0
START_POSITION       293135
COMMENT              540350
MIN                       0
FGM                       0
FGA                       0
FG_PCT                    0
FG3M                      0
FG3A                      0
FG3_PCT                   0
FTM                       0
FTA                       0
FT_PCT                    0
OREB                      0
DREB                      0
REB                       0
AST                       0
STL                       0
BLK                       0
TO                        0
PF                        0
PTS                       0
PLUS_MINUS            23661
dtype: int64

In [17]:
len(new_details_df)

540350

In [18]:
new_details_df = new_details_df.drop(columns = ['START_POSITION', 'COMMENT', 'PLUS_MINUS'])

new_details_df.head(10)

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,MIN,FGM,FGA,FG_PCT,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS
0,22101005,1610612750,MIN,Minnesota,1630162,Anthony Edwards,36:22,4.0,10.0,0.400,...,1.00,0.0,8.0,8.0,5.0,3.0,1.0,1.0,1.0,15.0
1,22101005,1610612750,MIN,Minnesota,1630183,Jaden McDaniels,23:54,6.0,8.0,0.750,...,1.00,2.0,4.0,6.0,0.0,0.0,2.0,2.0,6.0,14.0
2,22101005,1610612750,MIN,Minnesota,1626157,Karl-Anthony Towns,25:17,4.0,9.0,0.444,...,0.75,1.0,9.0,10.0,0.0,0.0,0.0,3.0,4.0,15.0
3,22101005,1610612750,MIN,Minnesota,1627736,Malik Beasley,30:52,4.0,9.0,0.444,...,0.00,0.0,3.0,3.0,1.0,1.0,0.0,1.0,4.0,12.0
4,22101005,1610612750,MIN,Minnesota,1626156,D'Angelo Russell,33:46,3.0,13.0,0.231,...,1.00,0.0,6.0,6.0,9.0,1.0,0.0,5.0,0.0,14.0
5,22101005,1610612750,MIN,Minnesota,1629675,Naz Reid,23:56,3.0,8.0,0.375,...,1.00,3.0,7.0,10.0,1.0,3.0,2.0,1.0,1.0,11.0
6,22101005,1610612750,MIN,Minnesota,1629162,Jordan McLaughlin,21:00,2.0,5.0,0.400,...,1.00,0.0,1.0,1.0,3.0,3.0,0.0,0.0,1.0,5.0
7,22101005,1610612750,MIN,Minnesota,1629669,Jaylen Nowell,21:35,6.0,13.0,0.462,...,1.00,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,16.0
8,22101005,1610612750,MIN,Minnesota,1627752,Taurean Prince,22:53,3.0,8.0,0.375,...,0.60,0.0,2.0,2.0,1.0,1.0,0.0,1.0,2.0,11.0
9,22101005,1610612750,MIN,Minnesota,1629006,Josh Okogie,0:25,0.0,0.0,0.000,...,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [19]:
new_details_df.isnull().sum()

GAME_ID              0
TEAM_ID              0
TEAM_ABBREVIATION    0
TEAM_CITY            0
PLAYER_ID            0
PLAYER_NAME          0
MIN                  0
FGM                  0
FGA                  0
FG_PCT               0
FG3M                 0
FG3A                 0
FG3_PCT              0
FTM                  0
FTA                  0
FT_PCT               0
OREB                 0
DREB                 0
REB                  0
AST                  0
STL                  0
BLK                  0
TO                   0
PF                   0
PTS                  0
dtype: int64

In [20]:
len(new_details_df)

540350

In [21]:
new_details_df['GAME_ID'].value_counts()

22000001    37
10500120    36
22000007    35
11900049    35
11500060    35
            ..
20300499    15
40500236    15
22001079    15
20300114    14
21401227    13
Name: GAME_ID, Length: 25668, dtype: int64

In [22]:
games_data = pd.read_csv("../resources/games.csv")
games_data.head()

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,...,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
0,2022-03-12,22101005,Final,1610612748,1610612750,2021,1610612748,104.0,0.398,0.760,...,23.0,53.0,1610612750,113.0,0.422,0.875,0.357,21.0,46.0,0
1,2022-03-12,22101006,Final,1610612741,1610612739,2021,1610612741,101.0,0.443,0.933,...,20.0,46.0,1610612739,91.0,0.419,0.824,0.208,19.0,40.0,1
2,2022-03-12,22101007,Final,1610612759,1610612754,2021,1610612759,108.0,0.412,0.813,...,28.0,52.0,1610612754,119.0,0.489,1.000,0.389,23.0,47.0,0
3,2022-03-12,22101008,Final,1610612744,1610612749,2021,1610612744,122.0,0.484,0.933,...,33.0,55.0,1610612749,109.0,0.413,0.696,0.386,27.0,39.0,1
4,2022-03-12,22101009,Final,1610612743,1610612761,2021,1610612743,115.0,0.551,0.750,...,32.0,39.0,1610612761,127.0,0.471,0.760,0.387,28.0,50.0,0

In [23]:
new_games = games_data.copy()
new_games

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,...,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
0,2022-03-12,22101005,Final,1610612748,1610612750,2021,1610612748,104.0,0.398,0.760,...,23.0,53.0,1610612750,113.0,0.422,0.875,0.357,21.0,46.0,0
1,2022-03-12,22101006,Final,1610612741,1610612739,2021,1610612741,101.0,0.443,0.933,...,20.0,46.0,1610612739,91.0,0.419,0.824,0.208,19.0,40.0,1
2,2022-03-12,22101007,Final,1610612759,1610612754,2021,1610612759,108.0,0.412,0.813,...,28.0,52.0,1610612754,119.0,0.489,1.000,0.389,23.0,47.0,0
3,2022-03-12,22101008,Final,1610612744,1610612749,2021,1610612744,122.0,0.484,0.933,...,33.0,55.0,1610612749,109.0,0.413,0.696,0.386,27.0,39.0,1
4,2022-03-12,22101009,Final,1610612743,1610612761,2021,1610612743,115.0,0.551,0.750,...,32.0,39.0,1610612761,127.0,0.471,0.760,0.387,28.0,50.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25791,2014-10-06,11400007,Final,1610612737,1610612740,2014,1610612737,93.0,0.419,0.821,...,24.0,50.0,1610612740,87.0,0.366,0.643,0.375,17.0,43.0,1
25792,2014-10-06,11400004,Final,1610612741,1610612764,2014,1610612741,81.0,0.338,0.719,...,18.0,40.0,1610612764,85.0,0.411,0.636,0.267,17.0,47.0,0
25793,2014-10-06,11400005,Final,1610612747,1610612743,2014,1610612747,98.0,0.448,0.682,...,29.0,45.0,1610612743,95.0,0.387,0.659,0.500,19.0,43.0,1
25794,2014-10-05,11400002,Final,1610612761,1610612758,2014,1610612761,99.0,0.440,0.771,...,21.0,30.0,1610612758,94.0,0.469,0.725,0.385,18.0,45.0,1
25795,2014-10-04,11400001,Final,1610612748,1610612740,2014,1610612748,86.0,0.431,0.679,...,18.0,42.0,1610612740,98.0,0.462,0.706,0.438,19.0,42.0,0

In [24]:
id_date = new_games[['GAME_DATE_EST', 'GAME_ID']].copy()
id_date

      GAME_DATE_EST   GAME_ID
0        2022-03-12  22101005
1        2022-03-12  22101006
2        2022-03-12  22101007
3        2022-03-12  22101008
4        2022-03-12  22101009
...             ...       ...
25791    2014-10-06  11400007
25792    2014-10-06  11400004
25793    2014-10-06  11400005
25794    2014-10-05  11400002
25795    2014-10-04  11400001

[25796 rows x 2 columns]

# Dataframe with ALL Player data

In [25]:
details_dates = pd.merge(new_details_df, id_date, how = 'left', on = 'GAME_ID')
details_dates

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,MIN,FGM,FGA,FG_PCT,...,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,GAME_DATE_EST
0,22101005,1610612750,MIN,Minnesota,1630162,Anthony Edwards,36:22,4.0,10.0,0.400,...,0.0,8.0,8.0,5.0,3.0,1.0,1.0,1.0,15.0,2022-03-12
1,22101005,1610612750,MIN,Minnesota,1630183,Jaden McDaniels,23:54,6.0,8.0,0.750,...,2.0,4.0,6.0,0.0,0.0,2.0,2.0,6.0,14.0,2022-03-12
2,22101005,1610612750,MIN,Minnesota,1626157,Karl-Anthony Towns,25:17,4.0,9.0,0.444,...,1.0,9.0,10.0,0.0,0.0,0.0,3.0,4.0,15.0,2022-03-12
3,22101005,1610612750,MIN,Minnesota,1627736,Malik Beasley,30:52,4.0,9.0,0.444,...,0.0,3.0,3.0,1.0,1.0,0.0,1.0,4.0,12.0,2022-03-12
4,22101005,1610612750,MIN,Minnesota,1626156,D'Angelo Russell,33:46,3.0,13.0,0.231,...,0.0,6.0,6.0,9.0,1.0,0.0,5.0,0.0,14.0,2022-03-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
541085,11200005,1610612743,DEN,Denver,202706,Jordan Hamilton,19,4.0,9.0,0.444,...,0.0,2.0,2.0,0.0,2.0,0.0,1.0,3.0,17.0,2012-10-06
541086,11200005,1610612743,DEN,Denver,202702,Kenneth Faried,23,7.0,11.0,0.636,...,1.0,0.0,1.0,1.0,1.0,0.0,3.0,3.0,18.0,2012-10-06
541087,11200005,1610612743,DEN,Denver,201585,Kosta Koufos,15,3.0,7.0,0.429,...,3.0,5.0,8.0,0.0,1.0,0.0,0.0,3.0,6.0,2012-10-06
541088,11200005,1610612743,DEN,Denver,202389,Timofey Mozgov,19,1.0,1.0,1.000,...,1.0,2.0,3.0,1.0,0.0,0.0,4.0,2.0,2.0,2012-10-06
541089,11200005,1610612743,DEN,Denver,201951,Ty Lawson,27,3.0,6.0,0.500,...,0.0,2.0,2.0,6.0,2.0,0.0,6.0,1.0,8.0,2012-10-06

In [26]:
details_dates.isnull().sum()

GAME_ID              0
TEAM_ID              0
TEAM_ABBREVIATION    0
TEAM_CITY            0
PLAYER_ID            0
PLAYER_NAME          0
MIN                  0
FGM                  0
FGA                  0
FG_PCT               0
FG3M                 0
FG3A                 0
FG3_PCT              0
FTM                  0
FTA                  0
FT_PCT               0
OREB                 0
DREB                 0
REB                  0
AST                  0
STL                  0
BLK                  0
TO                   0
PF                   0
PTS                  0
GAME_DATE_EST        0
dtype: int64

In [27]:
duplicate = details_dates[details_dates.duplicated()]
duplicate

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,MIN,FGM,FGA,FG_PCT,...,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,GAME_DATE_EST
35075,22000070,1610612738,BOS,Boston,1628369,Jayson Tatum,37:04,11.0,24.0,0.458,...,0.0,6.0,6.0,2.0,1.0,1.0,3.0,1.0,28.0,2021-01-01
35077,22000070,1610612738,BOS,Boston,202684,Tristan Thompson,25:35,2.0,4.0,0.500,...,1.0,8.0,9.0,2.0,1.0,2.0,3.0,2.0,5.0,2021-01-01
35079,22000070,1610612738,BOS,Boston,1628464,Daniel Theis,23:58,1.0,2.0,0.500,...,1.0,5.0,6.0,0.0,0.0,3.0,2.0,3.0,2.0,2021-01-01
35081,22000070,1610612738,BOS,Boston,1627759,Jaylen Brown,37:34,12.0,20.0,0.600,...,2.0,7.0,9.0,2.0,3.0,2.0,4.0,3.0,25.0,2021-01-01
35083,22000070,1610612738,BOS,Boston,203935,Marcus Smart,38:11,5.0,14.0,0.357,...,0.0,3.0,3.0,9.0,3.0,0.0,4.0,3.0,13.0,2021-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49310,22000015,1610612741,CHI,Chicago,1629690,Adam Mokoka,16:47,2.0,6.0,0.333,...,1.0,1.0,2.0,2.0,1.0,1.0,0.0,1.0,4.0,2020-12-23
49320,22000018,1610612765,DET,Detroit,1626153,Delon Wright,19:09,2.0,5.0,0.400,...,0.0,2.0,2.0,4.0,1.0,0.0,1.0,0.0,5.0,2020-12-23
49322,22000018,1610612765,DET,Detroit,201565,Derrick Rose,26:48,7.0,13.0,0.538,...,0.0,1.0,1.0,6.0,2.0,1.0,1.0,1.0,15.0,2020-12-23
49324,22000018,1610612750,MIN,Minnesota,1627736,Malik Beasley,26:37,10.0,18.0,0.556,...,1.0,3.0,4.0,2.0,1.0,0.0,1.0,3.0,23.0,2020-12-23
49326,22000018,1610612750,MIN,Minnesota,1626156,D'Angelo Russell,33:20,7.0,16.0,0.438,...,1.0,4.0,5.0,4.0,1.0,0.0,2.0,2.0,18.0,2020-12-23

In [28]:
details_dates.drop_duplicates(inplace = True)

In [29]:
details_dates

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,MIN,FGM,FGA,FG_PCT,...,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,GAME_DATE_EST
0,22101005,1610612750,MIN,Minnesota,1630162,Anthony Edwards,36:22,4.0,10.0,0.400,...,0.0,8.0,8.0,5.0,3.0,1.0,1.0,1.0,15.0,2022-03-12
1,22101005,1610612750,MIN,Minnesota,1630183,Jaden McDaniels,23:54,6.0,8.0,0.750,...,2.0,4.0,6.0,0.0,0.0,2.0,2.0,6.0,14.0,2022-03-12
2,22101005,1610612750,MIN,Minnesota,1626157,Karl-Anthony Towns,25:17,4.0,9.0,0.444,...,1.0,9.0,10.0,0.0,0.0,0.0,3.0,4.0,15.0,2022-03-12
3,22101005,1610612750,MIN,Minnesota,1627736,Malik Beasley,30:52,4.0,9.0,0.444,...,0.0,3.0,3.0,1.0,1.0,0.0,1.0,4.0,12.0,2022-03-12
4,22101005,1610612750,MIN,Minnesota,1626156,D'Angelo Russell,33:46,3.0,13.0,0.231,...,0.0,6.0,6.0,9.0,1.0,0.0,5.0,0.0,14.0,2022-03-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
541085,11200005,1610612743,DEN,Denver,202706,Jordan Hamilton,19,4.0,9.0,0.444,...,0.0,2.0,2.0,0.0,2.0,0.0,1.0,3.0,17.0,2012-10-06
541086,11200005,1610612743,DEN,Denver,202702,Kenneth Faried,23,7.0,11.0,0.636,...,1.0,0.0,1.0,1.0,1.0,0.0,3.0,3.0,18.0,2012-10-06
541087,11200005,1610612743,DEN,Denver,201585,Kosta Koufos,15,3.0,7.0,0.429,...,3.0,5.0,8.0,0.0,1.0,0.0,0.0,3.0,6.0,2012-10-06
541088,11200005,1610612743,DEN,Denver,202389,Timofey Mozgov,19,1.0,1.0,1.000,...,1.0,2.0,3.0,1.0,0.0,0.0,4.0,2.0,2.0,2012-10-06
541089,11200005,1610612743,DEN,Denver,201951,Ty Lawson,27,3.0,6.0,0.500,...,0.0,2.0,2.0,6.0,2.0,0.0,6.0,1.0,8.0,2012-10-06

In [30]:
details_dates.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 540350 entries, 0 to 541089
Data columns (total 26 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   GAME_ID            540350 non-null  int64
 1   TEAM_ID            540350 non-null  int64
 2   TEAM_ABBREVIATION  540350 non-null  object
 3   TEAM_CITY          540350 non-null  object
 4   PLAYER_ID          540350 non-null  int64
 5   PLAYER_NAME        540350 non-null  object
 6   MIN                540350 non-null  object
 7   FGM                540350 non-null  float64
 8   FGA                540350 non-null  float64
 9   FG_PCT             540350 non-null  float64
 10  FG3M               540350 non-null  float64
 11  FG3A               540350 non-null  float64
 12  FG3_PCT            540350 non-null  float64
 13  FTM                540350 non-null  float64
 14  FTA                540350 non-null  float64
 15  FT_PCT             540350 non-null  float64
 16  OREB               540350 non-null  float64
 17  DREB               540350 non-null  float64
 18  REB                540350 non-null  float64
 19  AST                540350 non-null  float64
 20  STL                540350 non-null  float64
 21  BLK                540350 non-null  float64
 22  TO                 540350 non-null  float64
 23  PF                 540350 non-null  float64
 24  PTS                540350 non-null  float64
 25  GAME_DATE_EST      540350 non-null  object
dtypes: float64(18), int64(3), object(5)
memory usage: 111.3+ MB

In [31]:
details_dates['GAME_DATE_EST'] = pd.to_datetime(details_dates['GAME_DATE_EST'])

In [32]:
details_dates.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 540350 entries, 0 to 541089
Data columns (total 26 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   GAME_ID            540350 non-null  int64
 1   TEAM_ID            540350 non-null  int64
 2   TEAM_ABBREVIATION  540350 non-null  object
 3   TEAM_CITY          540350 non-null  object
 4   PLAYER_ID          540350 non-null  int64
 5   PLAYER_NAME        540350 non-null  object
 6   MIN                540350 non-null  object
 7   FGM                540350 non-null  float64
 8   FGA                540350 non-null  float64
 9   FG_PCT             540350 non-null  float64
 10  FG3M               540350 non-null  float64
 11  FG3A               540350 non-null  float64
 12  FG3_PCT            540350 non-null  float64
 13  FTM                540350 non-null  float64
 14  FTA                540350 non-null  float64
 15  FT_PCT             540350 non-null  float64
 16  OREB               540350 non-null  float64
 17  DREB               540350 non-null  float64
 18  REB                540350 non-null  float64
 19  AST                540350 non-null  float64
 20  STL                540350 non-null  float64
 21  BLK                540350 non-null  float64
 22  TO                 540350 non-null  float64
 23  PF                 540350 non-null  float64
 24  PTS                540350 non-null  float64
 25  GAME_DATE_EST      540350 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(18), int64(3), object(4)
memory usage: 111.3+ MB

In [33]:
details_dates.set_index(details_dates.pop('GAME_DATE_EST'), inplace = True)
details_dates.reset_index(inplace = True)
details_dates

,GAME_DATE_EST,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,MIN,FGM,FGA,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS
0,2022-03-12,22101005,1610612750,MIN,Minnesota,1630162,Anthony Edwards,36:22,4.0,10.0,...,1.000,0.0,8.0,8.0,5.0,3.0,1.0,1.0,1.0,15.0
1,2022-03-12,22101005,1610612750,MIN,Minnesota,1630183,Jaden McDaniels,23:54,6.0,8.0,...,1.000,2.0,4.0,6.0,0.0,0.0,2.0,2.0,6.0,14.0
2,2022-03-12,22101005,1610612750,MIN,Minnesota,1626157,Karl-Anthony Towns,25:17,4.0,9.0,...,0.750,1.0,9.0,10.0,0.0,0.0,0.0,3.0,4.0,15.0
3,2022-03-12,22101005,1610612750,MIN,Minnesota,1627736,Malik Beasley,30:52,4.0,9.0,...,0.000,0.0,3.0,3.0,1.0,1.0,0.0,1.0,4.0,12.0
4,2022-03-12,22101005,1610612750,MIN,Minnesota,1626156,D'Angelo Russell,33:46,3.0,13.0,...,1.000,0.0,6.0,6.0,9.0,1.0,0.0,5.0,0.0,14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540345,2012-10-06,11200005,1610612743,DEN,Denver,202706,Jordan Hamilton,19,4.0,9.0,...,0.857,0.0,2.0,2.0,0.0,2.0,0.0,1.0,3.0,17.0
540346,2012-10-06,11200005,1610612743,DEN,Denver,202702,Kenneth Faried,23,7.0,11.0,...,1.000,1.0,0.0,1.0,1.0,1.0,0.0,3.0,3.0,18.0
540347,2012-10-06,11200005,1610612743,DEN,Denver,201585,Kosta Koufos,15,3.0,7.0,...,0.000,3.0,5.0,8.0,0.0,1.0,0.0,0.0,3.0,6.0
540348,2012-10-06,11200005,1610612743,DEN,Denver,202389,Timofey Mozgov,19,1.0,1.0,...,0.000,1.0,2.0,3.0,1.0,0.0,0.0,4.0,2.0,2.0
540349,2012-10-06,11200005,1610612743,DEN,Denver,201951,Ty Lawson,27,3.0,6.0,...,0.500,0.0,2.0,2.0,6.0,2.0,0.0,6.0,1.0,8.0

In [34]:
details_dates.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 540350 entries, 0 to 540349
Data columns (total 26 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   GAME_DATE_EST      540350 non-null  datetime64[ns]
 1   GAME_ID            540350 non-null  int64
 2   TEAM_ID            540350 non-null  int64
 3   TEAM_ABBREVIATION  540350 non-null  object
 4   TEAM_CITY          540350 non-null  object
 5   PLAYER_ID          540350 non-null  int64
 6   PLAYER_NAME        540350 non-null  object
 7   MIN                540350 non-null  object
 8   FGM                540350 non-null  float64
 9   FGA                540350 non-null  float64
 10  FG_PCT             540350 non-null  float64
 11  FG3M               540350 non-null  float64
 12  FG3A               540350 non-null  float64
 13  FG3_PCT            540350 non-null  float64
 14  FTM                540350 non-null  float64
 15  FTA                540350 non-null  float64
 16  FT_PCT             540350 non-null  float64
 17  OREB               540350 non-null  float64
 18  DREB               540350 non-null  float64
 19  REB                540350 non-null  float64
 20  AST                540350 non-null  float64
 21  STL                540350 non-null  float64
 22  BLK                540350 non-null  float64
 23  TO                 540350 non-null  float64
 24  PF                 540350 non-null  float64
 25  PTS                540350 non-null  float64
dtypes: datetime64[ns](1), float64(18), int64(3), object(4)
memory usage: 107.2+ MB

In [35]:
print(details_dates.GAME_DATE_EST.min())

2003-10-05 00:00:00

In [36]:
print(details_dates.GAME_DATE_EST.max())

2022-03-12 00:00:00

# Rename Columns

In [37]:
details_dates = details_dates.rename(columns = {'GAME_DATE_EST':'GAME_DATE','FGM': '2pointer_MADE', 'FGA':'2pointer_ATTEMPTS',
                                                 'FG_PCT':'2pointer_PCT', 'FG3M':'3pointer_MADE', 'FG3A':'3pointer_ATTEMPTS',
                                               'FG3_PCT':'3pointer_PCT', 'FTM':'FreeThrow_MADE', 'FTA':'FreeThrow_ATTEMPTS',
                                               'FT_PCT':'FreeThrow_PCT', 'OREB':'OFFENSIVE_REBOUNDS', 'DREB':'DEFENSIVE_REBOUNDS',
                                               'REB':'REBOUNDS_TOTAL', 'AST':'ASSISTS', 'STL':'STEALS', 'BLK':'BLOCKS',
                                               'TO':'TURNOVERS', 'PF':'PERSONAL_FOULS', 'PTS':'POINTS'})
details_dates.head()

,GAME_DATE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,MIN,2pointer_MADE,2pointer_ATTEMPTS,...,FreeThrow_PCT,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,2022-03-12,22101005,1610612750,MIN,Minnesota,1630162,Anthony Edwards,36:22,4.0,10.0,...,1.00,0.0,8.0,8.0,5.0,3.0,1.0,1.0,1.0,15.0
1,2022-03-12,22101005,1610612750,MIN,Minnesota,1630183,Jaden McDaniels,23:54,6.0,8.0,...,1.00,2.0,4.0,6.0,0.0,0.0,2.0,2.0,6.0,14.0
2,2022-03-12,22101005,1610612750,MIN,Minnesota,1626157,Karl-Anthony Towns,25:17,4.0,9.0,...,0.75,1.0,9.0,10.0,0.0,0.0,0.0,3.0,4.0,15.0
3,2022-03-12,22101005,1610612750,MIN,Minnesota,1627736,Malik Beasley,30:52,4.0,9.0,...,0.00,0.0,3.0,3.0,1.0,1.0,0.0,1.0,4.0,12.0
4,2022-03-12,22101005,1610612750,MIN,Minnesota,1626156,D'Angelo Russell,33:46,3.0,13.0,...,1.00,0.0,6.0,6.0,9.0,1.0,0.0,5.0,0.0,14.0

In [38]:
filtered_all = details_dates[['TEAM_ID', 'PLAYER_ID', 'PLAYER_NAME', '2pointer_MADE', '2pointer_ATTEMPTS',
                        '3pointer_MADE', '3pointer_ATTEMPTS', 'FreeThrow_MADE', 'FreeThrow_ATTEMPTS', 'OFFENSIVE_REBOUNDS', 
                         'DEFENSIVE_REBOUNDS', 'REBOUNDS_TOTAL', 'ASSISTS','STEALS', 'BLOCKS', 'TURNOVERS', 'PERSONAL_FOULS', 'POINTS']]
filtered_all

,TEAM_ID,PLAYER_ID,PLAYER_NAME,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,1610612750,1630162,Anthony Edwards,4.0,10.0,3.0,8.0,4.0,4.0,0.0,8.0,8.0,5.0,3.0,1.0,1.0,1.0,15.0
1,1610612750,1630183,Jaden McDaniels,6.0,8.0,1.0,3.0,1.0,1.0,2.0,4.0,6.0,0.0,0.0,2.0,2.0,6.0,14.0
2,1610612750,1626157,Karl-Anthony Towns,4.0,9.0,1.0,3.0,6.0,8.0,1.0,9.0,10.0,0.0,0.0,0.0,3.0,4.0,15.0
3,1610612750,1627736,Malik Beasley,4.0,9.0,4.0,9.0,0.0,0.0,0.0,3.0,3.0,1.0,1.0,0.0,1.0,4.0,12.0
4,1610612750,1626156,D'Angelo Russell,3.0,13.0,1.0,6.0,7.0,7.0,0.0,6.0,6.0,9.0,1.0,0.0,5.0,0.0,14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540345,1610612743,202706,Jordan Hamilton,4.0,9.0,3.0,6.0,6.0,7.0,0.0,2.0,2.0,0.0,2.0,0.0,1.0,3.0,17.0
540346,1610612743,202702,Kenneth Faried,7.0,11.0,0.0,0.0,4.0,4.0,1.0,0.0,1.0,1.0,1.0,0.0,3.0,3.0,18.0
540347,1610612743,201585,Kosta Koufos,3.0,7.0,0.0,0.0,0.0,0.0,3.0,5.0,8.0,0.0,1.0,0.0,0.0,3.0,6.0
540348,1610612743,202389,Timofey Mozgov,1.0,1.0,0.0,0.0,0.0,2.0,1.0,2.0,3.0,1.0,0.0,0.0,4.0,2.0,2.0
540349,1610612743,201951,Ty Lawson,3.0,6.0,0.0,0.0,2.0,4.0,0.0,2.0,2.0,6.0,2.0,0.0,6.0,1.0,8.0

In [39]:
by_player_all = filtered_all.groupby(['PLAYER_NAME']).agg({'TEAM_ID': 'last', 'PLAYER_ID': 'last',
                                                            '2pointer_MADE': 'sum', '2pointer_ATTEMPTS': 'sum',
                                                            '3pointer_MADE': 'sum', '3pointer_ATTEMPTS': 'sum', 'FreeThrow_MADE': 'sum', 
                                                            'FreeThrow_ATTEMPTS': 'sum', 'OFFENSIVE_REBOUNDS': 'sum', 
                                                            'DEFENSIVE_REBOUNDS': 'sum', 'REBOUNDS_TOTAL': 'sum', 'ASSISTS': 'sum',
                                                            'STEALS': 'sum', 'BLOCKS': 'sum', 'TURNOVERS': 'sum', 'PERSONAL_FOULS': 'sum', 
                                                            'POINTS': 'sum'}).reset_index()
by_player_all

,PLAYER_NAME,TEAM_ID,PLAYER_ID,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,A.J. Guyton,1610612765,2062,0.0,4.0,0.0,2.0,4.0,4.0,1.0,1.0,2.0,1.0,1.0,0.0,0.0,2.0,4.0
1,A.J. Lawson,1610612737,1630639,2.0,3.0,2.0,2.0,2.0,2.0,0.0,2.0,2.0,0.0,0.0,0.0,1.0,0.0,8.0
2,AJ Hammons,1610612742,1627773,34.0,76.0,5.0,12.0,9.0,20.0,14.0,46.0,60.0,7.0,1.0,16.0,14.0,34.0,82.0
3,AJ Price,1610612764,201985,655.0,1686.0,267.0,805.0,255.0,343.0,83.0,352.0,435.0,647.0,143.0,9.0,279.0,289.0,1832.0
4,Aamir Simms,1610612752,1630603,1.0,2.0,0.0,0.0,2.0,2.0,3.0,2.0,5.0,2.0,0.0,0.0,0.0,2.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2478,Zion Williamson,1610612740,1629627,908.0,1494.0,17.0,55.0,524.0,767.0,245.0,394.0,639.0,289.0,81.0,49.0,242.0,192.0,2357.0
2479,Zoran Dragic,1610612756,204054,11.0,33.0,3.0,15.0,3.0,5.0,5.0,4.0,9.0,5.0,2.0,0.0,5.0,6.0,28.0
2480,Zoran Planinic,1610612751,2565,225.0,553.0,40.0,144.0,161.0,240.0,53.0,170.0,223.0,189.0,68.0,7.0,137.0,264.0,651.0
2481,Zydrunas Ilgauskas,1610612739,980,3350.0,6976.0,32.0,98.0,1874.0,2373.0,1971.0,3119.0,5090.0,776.0,320.0,1043.0,1152.0,2279.0,8606.0
2482,Zylan Cheatham,1610612740,1629597,13.0,21.0,0.0,4.0,5.0,8.0,7.0,15.0,22.0,3.0,1.0,2.0,6.0,14.0,31.0

In [40]:
by_player_all.dtypes

PLAYER_NAME            object
TEAM_ID                 int64
PLAYER_ID               int64
2pointer_MADE         float64
2pointer_ATTEMPTS     float64
3pointer_MADE         float64
3pointer_ATTEMPTS     float64
FreeThrow_MADE        float64
FreeThrow_ATTEMPTS    float64
OFFENSIVE_REBOUNDS    float64
DEFENSIVE_REBOUNDS    float64
REBOUNDS_TOTAL        float64
ASSISTS               float64
STEALS                float64
BLOCKS                float64
TURNOVERS             float64
PERSONAL_FOULS        float64
POINTS                float64
dtype: object

In [41]:
# by_player_all.to_csv('../Resources/Data_by_Player.csv')

In [42]:
# details_dates.to_csv('../Resources/All_player_data.csv')

# Playoff Games by Season

In [43]:
Playoffs_test = details_dates[(details_dates['GAME_DATE'] >= '2021-05-22') & (details_dates['GAME_DATE'] <= '2021-07-20')]

Playoffs_test

,GAME_DATE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,MIN,2pointer_MADE,2pointer_ATTEMPTS,...,FreeThrow_PCT,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
23291,2021-07-20,42000406,1610612756,PHX,Phoenix,1628969,Mikal Bridges,39:28,3.0,7.0,...,0.50,1.0,5.0,6.0,2.0,2.0,0.0,0.0,4.0,7.0
23292,2021-07-20,42000406,1610612756,PHX,Phoenix,203109,Jae Crowder,40:33,4.0,11.0,...,1.00,2.0,11.0,13.0,0.0,4.0,1.0,2.0,3.0,15.0
23293,2021-07-20,42000406,1610612756,PHX,Phoenix,1629028,Deandre Ayton,36:12,4.0,12.0,...,0.80,1.0,5.0,6.0,1.0,2.0,2.0,2.0,5.0,12.0
23294,2021-07-20,42000406,1610612756,PHX,Phoenix,1626164,Devin Booker,46:15,8.0,22.0,...,1.00,0.0,3.0,3.0,5.0,0.0,0.0,6.0,4.0,19.0
23295,2021-07-20,42000406,1610612756,PHX,Phoenix,101108,Chris Paul,39:13,11.0,19.0,...,0.75,1.0,1.0,2.0,5.0,1.0,0.0,3.0,5.0,26.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25150,2021-05-22,42000161,1610612743,DEN,Denver,1630267,Facundo Campazzo,31:32,3.0,4.0,...,0.00,2.0,1.0,3.0,5.0,2.0,1.0,1.0,3.0,8.0
25151,2021-05-22,42000161,1610612743,DEN,Denver,1628420,Monte Morris,21:59,5.0,10.0,...,0.00,0.0,2.0,2.0,5.0,0.0,0.0,1.0,4.0,10.0
25152,2021-05-22,42000161,1610612743,DEN,Denver,203210,JaMychal Green,17:37,0.0,1.0,...,0.00,0.0,1.0,1.0,3.0,0.0,1.0,0.0,2.0,0.0
25153,2021-05-22,42000161,1610612743,DEN,Denver,1630210,Markus Howard,19:58,3.0,5.0,...,0.00,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,7.0
25154,2021-05-22,42000161,1610612743,DEN,Denver,200794,Paul Millsap,14:43,1.0,3.0,...,0.00,0.0,3.0,3.0,4.0,1.0,0.0,2.0,2.0,3.0

In [44]:
print(details_dates[details_dates['GAME_DATE'] == '2003-04-24'])

Empty DataFrame
Columns: [GAME_DATE, GAME_ID, TEAM_ID, TEAM_ABBREVIATION, TEAM_CITY, PLAYER_ID, PLAYER_NAME, MIN, 2pointer_MADE, 2pointer_ATTEMPTS, 2pointer_PCT, 3pointer_MADE, 3pointer_ATTEMPTS, 3pointer_PCT, FreeThrow_MADE, FreeThrow_ATTEMPTS, FreeThrow_PCT, OFFENSIVE_REBOUNDS, DEFENSIVE_REBOUNDS, REBOUNDS_TOTAL, ASSISTS, STEALS, BLOCKS, TURNOVERS, PERSONAL_FOULS, POINTS]
Index: []

[0 rows x 26 columns]

In [45]:
# regular_season = details_dates
Playoffs_04 = details_dates[(details_dates['GAME_DATE'] >= '2004-04-17') & (details_dates['GAME_DATE'] <= '2004-06-15')]

Playoffs_04

,GAME_DATE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,MIN,2pointer_MADE,2pointer_ATTEMPTS,...,FreeThrow_PCT,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
213209,2004-06-15,40300405,1610612747,LAL,Los Angeles,1904,Devean George,20:22,2.0,6.0,...,0.000,2.0,1.0,3.0,2.0,0.0,1.0,0.0,4.0,4.0
213210,2004-06-15,40300405,1610612747,LAL,Los Angeles,2098,Slava Medvedenko,23:25,4.0,8.0,...,1.000,2.0,3.0,5.0,1.0,0.0,0.0,1.0,1.0,10.0
213211,2004-06-15,40300405,1610612747,LAL,Los Angeles,406,Shaquille O'Neal,35:33,7.0,13.0,...,0.375,2.0,6.0,8.0,1.0,1.0,0.0,1.0,4.0,20.0
213212,2004-06-15,40300405,1610612747,LAL,Los Angeles,977,Kobe Bryant,45:34,7.0,21.0,...,0.909,1.0,2.0,3.0,4.0,1.0,0.0,3.0,2.0,24.0
213213,2004-06-15,40300405,1610612747,LAL,Los Angeles,56,Gary Payton,30:47,1.0,3.0,...,0.000,2.0,2.0,4.0,4.0,2.0,1.0,1.0,2.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214858,2004-04-17,40300101,1610612754,IND,Indiana,2224,Jamaal Tinsley,29:24,2.0,6.0,...,0.000,1.0,2.0,3.0,7.0,1.0,1.0,0.0,3.0,5.0
214859,2004-04-17,40300101,1610612754,IND,Indiana,1733,Al Harrington,32:57,6.0,10.0,...,0.667,6.0,4.0,10.0,3.0,5.0,1.0,2.0,3.0,14.0
214860,2004-04-17,40300101,1610612754,IND,Indiana,2410,Fred Jones,18:60,4.0,5.0,...,0.000,1.0,3.0,4.0,2.0,0.0,1.0,1.0,2.0,9.0
214861,2004-04-17,40300101,1610612754,IND,Indiana,1533,Anthony Johnson,19:35,2.0,5.0,...,1.000,0.0,1.0,1.0,2.0,0.0,1.0,3.0,4.0,6.0
214862,2004-04-17,40300101,1610612754,IND,Indiana,1886,Jonathan Bender,8:15,1.0,2.0,...,0.500,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0,3.0

In [46]:
Playoffs_05 = details_dates[(details_dates['GAME_DATE'] >= '2005-04-23') & (details_dates['GAME_DATE'] <= '2005-06-23')]

Playoffs_05

,GAME_DATE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,MIN,2pointer_MADE,2pointer_ATTEMPTS,...,FreeThrow_PCT,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
185478,2005-06-23,40400407,1610612765,DET,Detroit,2419,Tayshaun Prince,41:19,4.0,13.0,...,0.000,1.0,1.0,2.0,1.0,2.0,0.0,1.0,1.0,9.0
185479,2005-06-23,40400407,1610612765,DET,Detroit,739,Rasheed Wallace,27:22,5.0,10.0,...,0.000,0.0,1.0,1.0,1.0,2.0,1.0,1.0,5.0,11.0
185480,2005-06-23,40400407,1610612765,DET,Detroit,1112,Ben Wallace,37:54,6.0,10.0,...,0.000,2.0,9.0,11.0,1.0,2.0,2.0,0.0,5.0,12.0
185481,2005-06-23,40400407,1610612765,DET,Detroit,1497,Chauncey Billups,39:24,3.0,8.0,...,0.875,1.0,3.0,4.0,8.0,1.0,0.0,1.0,4.0,13.0
185482,2005-06-23,40400407,1610612765,DET,Detroit,1888,Richard Hamilton,46:38,6.0,18.0,...,0.750,1.0,7.0,8.0,1.0,0.0,1.0,1.0,3.0,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187120,2005-04-23,40400161,1610612760,SEA,Seattle,2209,Vladimir Radmanovic,13:27,0.0,1.0,...,0.000,0.0,2.0,2.0,0.0,2.0,0.0,0.0,0.0,0.0
187121,2005-04-23,40400161,1610612760,SEA,Seattle,2555,Nick Collison,19:27,2.0,3.0,...,0.000,0.0,1.0,1.0,1.0,0.0,0.0,1.0,4.0,4.0
187122,2005-04-23,40400161,1610612760,SEA,Seattle,1498,Antonio Daniels,28:24,3.0,8.0,...,0.750,1.0,3.0,4.0,4.0,2.0,0.0,3.0,0.0,12.0
187123,2005-04-23,40400161,1610612760,SEA,Seattle,1504,Danny Fortson,9:33,1.0,2.0,...,0.500,1.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,3.0
187124,2005-04-23,40400161,1610612760,SEA,Seattle,2863,Damien Wilkins,8:58,0.0,2.0,...,0.000,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [47]:
Playoffs_06 = details_dates[(details_dates['GAME_DATE'] >= '2006-04-22') & (details_dates['GAME_DATE'] <= '2006-06-20')]

Playoffs_06

,GAME_DATE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,MIN,2pointer_MADE,2pointer_ATTEMPTS,...,FreeThrow_PCT,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
155967,2006-06-20,40500406,1610612748,MIA,Miami,952,Antoine Walker,33:30,6.0,17.0,...,0.667,3.0,8.0,11.0,2.0,1.0,1.0,0.0,2.0,14.0
155968,2006-06-20,40500406,1610612748,MIA,Miami,2617,Udonis Haslem,40:30,8.0,13.0,...,0.250,4.0,6.0,10.0,1.0,2.0,0.0,3.0,3.0,17.0
155969,2006-06-20,40500406,1610612748,MIA,Miami,406,Shaquille O'Neal,30:19,4.0,11.0,...,0.250,3.0,9.0,12.0,1.0,0.0,1.0,2.0,5.0,9.0
155970,2006-06-20,40500406,1610612748,MIA,Miami,2548,Dwyane Wade,45:24,10.0,18.0,...,0.762,3.0,7.0,10.0,5.0,4.0,3.0,5.0,4.0,36.0
155971,2006-06-20,40500406,1610612748,MIA,Miami,1715,Jason Williams,30:27,1.0,7.0,...,0.000,0.0,1.0,1.0,7.0,0.0,0.0,2.0,0.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157682,2006-04-22,40500161,1610612746,LAC,Los Angeles,208,Sam Cassell,33:35,6.0,11.0,...,0.857,1.0,0.0,1.0,7.0,0.0,0.0,0.0,2.0,19.0
157683,2006-04-22,40500161,1610612746,LAC,Los Angeles,2209,Vladimir Radmanovic,13:14,1.0,3.0,...,1.000,2.0,3.0,5.0,1.0,1.0,0.0,3.0,3.0,5.0
157684,2006-04-22,40500161,1610612746,LAC,Los Angeles,1894,Corey Maggette,14:39,2.0,8.0,...,0.750,2.0,5.0,7.0,1.0,1.0,0.0,1.0,2.0,8.0
157685,2006-04-22,40500161,1610612746,LAC,Los Angeles,1442,Zeljko Rebraca,11:34,1.0,2.0,...,0.000,0.0,2.0,2.0,0.0,0.0,0.0,2.0,3.0,2.0
157686,2006-04-22,40500161,1610612746,LAC,Los Angeles,2733,Shaun Livingston,20:11,1.0,4.0,...,0.000,0.0,1.0,1.0,3.0,0.0,0.0,1.0,2.0,2.0

In [48]:
Playoffs_07 = details_dates[(details_dates['GAME_DATE'] >= '2007-04-21') & (details_dates['GAME_DATE'] <= '2007-06-14')]

Playoffs_07

,GAME_DATE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,MIN,2pointer_MADE,2pointer_ATTEMPTS,...,FreeThrow_PCT,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
126561,2007-06-14,40600404,1610612759,SAS,San Antonio,1477,Bruce Bowen,42:08,1.0,6.0,...,0.000,1.0,4.0,5.0,3.0,0.0,0.0,0.0,4.0,2.0
126562,2007-06-14,40600404,1610612759,SAS,San Antonio,1495,Tim Duncan,40:08,4.0,15.0,...,0.400,5.0,10.0,15.0,3.0,2.0,2.0,6.0,3.0,12.0
126563,2007-06-14,40600404,1610612759,SAS,San Antonio,101177,Fabricio Oberto,25:24,3.0,5.0,...,1.000,3.0,2.0,5.0,0.0,1.0,0.0,0.0,2.0,7.0
126564,2007-06-14,40600404,1610612759,SAS,San Antonio,714,Michael Finley,15:39,1.0,5.0,...,0.667,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,4.0
126565,2007-06-14,40600404,1610612759,SAS,San Antonio,2225,Tony Parker,38:36,10.0,14.0,...,0.400,0.0,7.0,7.0,1.0,0.0,0.0,3.0,2.0,24.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128118,2007-04-21,40600171,1610612745,HOU,Houston,1503,Tracy McGrady,40:17,8.0,17.0,...,0.667,0.0,4.0,4.0,7.0,1.0,2.0,4.0,0.0,23.0
128119,2007-04-21,40600171,1610612745,HOU,Houston,1747,Rafer Alston,46:30,3.0,11.0,...,0.000,1.0,10.0,11.0,8.0,2.0,0.0,3.0,4.0,9.0
128120,2007-04-21,40600171,1610612745,HOU,Houston,101129,Luther Head,26:19,2.0,8.0,...,0.500,0.0,4.0,4.0,3.0,1.0,1.0,0.0,2.0,6.0
128121,2007-04-21,40600171,1610612745,HOU,Houston,87,Dikembe Mutombo,8:09,0.0,0.0,...,0.000,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
128122,2007-04-21,40600171,1610612745,HOU,Houston,436,Juwan Howard,23:60,2.0,5.0,...,1.000,0.0,3.0,3.0,0.0,1.0,0.0,2.0,0.0,8.0

In [49]:
Playoffs_08 = details_dates[(details_dates['GAME_DATE'] >= '2008-04-19') & (details_dates['GAME_DATE'] <= '2008-06-17')]

Playoffs_08

,GAME_DATE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,MIN,2pointer_MADE,2pointer_ATTEMPTS,...,FreeThrow_PCT,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
97564,2008-06-17,40700406,1610612747,LAL,Los Angeles,2209,Vladimir Radmanovic,21:30,2.0,6.0,...,0.000,0.0,3.0,3.0,0.0,0.0,0.0,0.0,5.0,6.0
97565,2008-06-17,40700406,1610612747,LAL,Los Angeles,1885,Lamar Odom,40:25,2.0,8.0,...,0.625,0.0,10.0,10.0,5.0,0.0,0.0,3.0,4.0,14.0
97566,2008-06-17,40700406,1610612747,LAL,Los Angeles,2200,Pau Gasol,32:23,4.0,7.0,...,0.750,0.0,8.0,8.0,2.0,0.0,0.0,5.0,3.0,11.0
97567,2008-06-17,40700406,1610612747,LAL,Los Angeles,977,Kobe Bryant,42:46,7.0,22.0,...,1.000,1.0,2.0,3.0,1.0,1.0,0.0,4.0,1.0,22.0
97568,2008-06-17,40700406,1610612747,LAL,Los Angeles,965,Derek Fisher,28:06,2.0,4.0,...,1.000,0.0,0.0,0.0,4.0,0.0,0.0,1.0,5.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99324,2008-04-19,40700161,1610612759,SAS,San Antonio,703,Kurt Thomas,28:56,2.0,5.0,...,0.000,4.0,6.0,10.0,0.0,0.0,1.0,2.0,6.0,4.0
99325,2008-04-19,40700161,1610612759,SAS,San Antonio,1938,Manu Ginobili,45:00,10.0,24.0,...,0.800,1.0,3.0,4.0,5.0,3.0,0.0,4.0,4.0,24.0
99326,2008-04-19,40700161,1610612759,SAS,San Antonio,1521,Jacque Vaughn,2:50,0.0,1.0,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
99327,2008-04-19,40700161,1610612759,SAS,San Antonio,2137,Ime Udoka,7:41,1.0,4.0,...,0.000,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,2.0
99328,2008-04-19,40700161,1610612759,SAS,San Antonio,699,Brent Barry,9:58,1.0,1.0,...,0.500,0.0,2.0,2.0,0.0,1.0,0.0,0.0,2.0,4.0

In [50]:
Playoffs_09 = details_dates[(details_dates['GAME_DATE'] >= '2009-04-18') & (details_dates['GAME_DATE'] <= '2009-06-14')]

Playoffs_09

,GAME_DATE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,MIN,2pointer_MADE,2pointer_ATTEMPTS,...,FreeThrow_PCT,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
68542,2009-06-14,40800405,1610612747,LAL,Los Angeles,2772,Trevor Ariza,41:29,5.0,12.0,...,0.500,1.0,4.0,5.0,1.0,2.0,0.0,3.0,3.0,15.0
68543,2009-06-14,40800405,1610612747,LAL,Los Angeles,2200,Pau Gasol,42:09,6.0,9.0,...,0.500,4.0,11.0,15.0,3.0,0.0,4.0,1.0,2.0,14.0
68544,2009-06-14,40800405,1610612747,LAL,Los Angeles,101115,Andrew Bynum,16:54,3.0,11.0,...,0.000,4.0,1.0,5.0,0.0,1.0,0.0,1.0,5.0,6.0
68545,2009-06-14,40800405,1610612747,LAL,Los Angeles,977,Kobe Bryant,43:18,10.0,23.0,...,1.000,0.0,6.0,6.0,5.0,2.0,4.0,1.0,2.0,30.0
68546,2009-06-14,40800405,1610612747,LAL,Los Angeles,965,Derek Fisher,31:59,4.0,7.0,...,1.000,0.0,4.0,4.0,2.0,0.0,0.0,1.0,4.0,13.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70278,2009-04-18,40800171,1610612757,POR,Portland,2566,Travis Outlaw,26:25,4.0,10.0,...,0.500,1.0,1.0,2.0,0.0,1.0,0.0,2.0,1.0,9.0
70279,2009-04-18,40800171,1610612757,POR,Portland,200771,Sergio Rodriguez,10:53,1.0,4.0,...,0.000,1.0,0.0,1.0,2.0,0.0,0.0,1.0,1.0,2.0
70280,2009-04-18,40800171,1610612757,POR,Portland,101112,Channing Frye,20:13,2.0,5.0,...,0.000,0.0,2.0,2.0,0.0,0.0,0.0,0.0,4.0,4.0
70281,2009-04-18,40800171,1610612757,POR,Portland,201573,Jerryd Bayless,8:46,1.0,4.0,...,0.667,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,4.0
70282,2009-04-18,40800171,1610612757,POR,Portland,1913,Michael Ruffin,5:27,0.0,1.0,...,0.500,3.0,2.0,5.0,0.0,0.0,0.0,1.0,1.0,1.0

In [51]:
Playoffs_10 = details_dates[(details_dates['GAME_DATE'] >= '2010-04-17') & (details_dates['GAME_DATE'] <= '2010-06-17')]

Playoffs_10

,GAME_DATE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,MIN,2pointer_MADE,2pointer_ATTEMPTS,...,FreeThrow_PCT,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
291805,2010-06-17,40900407,1610612738,BOS,Boston,1718,Paul Pierce,45:35,5.0,15.0,...,1.000,1.0,9.0,10.0,2.0,1.0,1.0,3.0,4.0,18.0
291806,2010-06-17,40900407,1610612738,BOS,Boston,708,Kevin Garnett,38:07,8.0,13.0,...,1.000,0.0,3.0,3.0,2.0,0.0,4.0,2.0,5.0,17.0
291807,2010-06-17,40900407,1610612738,BOS,Boston,739,Rasheed Wallace,35:36,5.0,11.0,...,0.000,2.0,6.0,8.0,2.0,0.0,2.0,0.0,6.0,11.0
291808,2010-06-17,40900407,1610612738,BOS,Boston,951,Ray Allen,45:16,3.0,14.0,...,0.833,0.0,2.0,2.0,2.0,3.0,0.0,4.0,3.0,13.0
291809,2010-06-17,40900407,1610612738,BOS,Boston,200765,Rajon Rondo,44:53,6.0,13.0,...,0.500,4.0,4.0,8.0,10.0,1.0,0.0,3.0,2.0,14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
293474,2010-04-17,40900171,1610612743,DEN,Denver,2365,Chris Andersen,21:32,0.0,0.0,...,0.000,0.0,6.0,6.0,1.0,0.0,2.0,0.0,1.0,0.0
293475,2010-04-17,40900171,1610612743,DEN,Denver,201951,Ty Lawson,21:37,3.0,8.0,...,0.750,1.0,2.0,3.0,6.0,1.0,0.0,0.0,3.0,11.0
293476,2010-04-17,40900171,1610612743,DEN,Denver,101121,Joey Graham,1:45,0.0,1.0,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
293477,2010-04-17,40900171,1610612743,DEN,Denver,101130,Johan Petro,1:45,0.0,0.0,...,0.000,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
293478,2010-04-17,40900171,1610612743,DEN,Denver,2124,Malik Allen,1:45,0.0,0.0,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [52]:
Playoffs_11 = details_dates[(details_dates['GAME_DATE'] >= '2011-04-16') & (details_dates['GAME_DATE'] <= '2011-06-12')]

Playoffs_11

,GAME_DATE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,MIN,2pointer_MADE,2pointer_ATTEMPTS,...,FreeThrow_PCT,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
262364,2011-06-12,41000406,1610612742,DAL,Dallas,1890,Shawn Marion,35:22,4.0,10.0,...,0.667,3.0,5.0,8.0,1.0,1.0,0.0,2.0,3.0,12.0
262365,2011-06-12,41000406,1610612742,DAL,Dallas,1717,Dirk Nowitzki,38:54,9.0,27.0,...,1.000,0.0,11.0,11.0,1.0,2.0,0.0,2.0,4.0,21.0
262366,2011-06-12,41000406,1610612742,DAL,Dallas,2199,Tyson Chandler,30:03,2.0,4.0,...,0.500,2.0,6.0,8.0,1.0,2.0,0.0,1.0,5.0,5.0
262367,2011-06-12,41000406,1610612742,DAL,Dallas,467,Jason Kidd,36:17,2.0,4.0,...,0.750,0.0,4.0,4.0,8.0,0.0,1.0,2.0,1.0,9.0
262368,2011-06-12,41000406,1610612742,DAL,Dallas,200826,J.J. Barea,29:37,7.0,12.0,...,0.000,2.0,1.0,3.0,5.0,2.0,0.0,3.0,3.0,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263975,2011-04-16,41000111,1610612748,MIA,Miami,1710,Mike Bibby,28:20,3.0,9.0,...,0.000,0.0,2.0,2.0,1.0,0.0,0.0,3.0,2.0,8.0
263976,2011-04-16,41000111,1610612748,MIA,Miami,201202,Joel Anthony,26:21,0.0,3.0,...,0.750,3.0,1.0,4.0,0.0,0.0,1.0,2.0,3.0,3.0
263977,2011-04-16,41000111,1610612748,MIA,Miami,2592,James Jones,24:58,4.0,8.0,...,0.000,2.0,3.0,5.0,1.0,1.0,0.0,0.0,0.0,9.0
263978,2011-04-16,41000111,1610612748,MIA,Miami,2034,Mike Miller,2:56,0.0,3.0,...,0.000,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
263979,2011-04-16,41000111,1610612748,MIA,Miami,201596,Mario Chalmers,21:26,2.0,2.0,...,0.500,0.0,1.0,1.0,1.0,1.0,0.0,2.0,1.0,6.0

In [53]:
Playoffs_12 = details_dates[(details_dates['GAME_DATE'] >= '2012-04-28') & (details_dates['GAME_DATE'] <= '2012-06-21')]

Playoffs_12

,GAME_DATE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,MIN,2pointer_MADE,2pointer_ATTEMPTS,...,FreeThrow_PCT,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
239109,2012-06-21,41100405,1610612760,OKC,Oklahoma City,201142,Kevin Durant,43:16,13.0,24.0,...,1.000,2.0,9.0,11.0,3.0,2.0,1.0,7.0,5.0,32.0
239110,2012-06-21,41100405,1610612760,OKC,Oklahoma City,201586,Serge Ibaka,25:47,3.0,9.0,...,0.750,4.0,0.0,4.0,0.0,0.0,2.0,0.0,3.0,9.0
239111,2012-06-21,41100405,1610612760,OKC,Oklahoma City,2570,Kendrick Perkins,19:45,1.0,4.0,...,0.000,0.0,4.0,4.0,0.0,1.0,0.0,1.0,5.0,2.0
239112,2012-06-21,41100405,1610612760,OKC,Oklahoma City,200757,Thabo Sefolosha,9:19,0.0,2.0,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0
239113,2012-06-21,41100405,1610612760,OKC,Oklahoma City,201566,Russell Westbrook,43:16,4.0,20.0,...,0.846,0.0,4.0,4.0,6.0,2.0,0.0,2.0,3.0,19.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
240848,2012-04-28,41100101,1610612741,CHI,Chicago,200758,Ronnie Brewer,12:41,0.0,1.0,...,0.000,0.0,1.0,1.0,1.0,0.0,0.0,1.0,2.0,0.0
240849,2012-04-28,41100101,1610612741,CHI,Chicago,201600,Omer Asik,9:43,0.0,2.0,...,0.250,1.0,0.0,1.0,1.0,0.0,1.0,2.0,1.0,1.0
240850,2012-04-28,41100101,1610612741,CHI,Chicago,201959,Taj Gibson,18:36,2.0,3.0,...,0.750,1.0,2.0,3.0,0.0,3.0,0.0,0.0,4.0,7.0
240851,2012-04-28,41100101,1610612741,CHI,Chicago,201228,C.J. Watson,10:49,1.0,4.0,...,1.000,0.0,0.0,0.0,5.0,1.0,0.0,1.0,0.0,4.0
240852,2012-04-28,41100101,1610612741,CHI,Chicago,2594,Kyle Korver,23:21,5.0,8.0,...,0.000,0.0,4.0,4.0,1.0,0.0,1.0,2.0,4.0,11.0

In [54]:
Playoffs_13 = details_dates[(details_dates['GAME_DATE'] >= '2013-04-20') & (details_dates['GAME_DATE'] <= '2013-06-20')]

Playoffs_13

,GAME_DATE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,MIN,2pointer_MADE,2pointer_ATTEMPTS,...,FreeThrow_PCT,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
510156,2013-06-20,41200407,1610612759,SAS,San Antonio,202695,Kawhi Leonard,45:00,8.0,17.0,...,0.5,4.0,12.0,16.0,0.0,1.0,1.0,2.0,2.0,19.0
510157,2013-06-20,41200407,1610612759,SAS,San Antonio,1938,Manu Ginobili,35:05,6.0,12.0,...,1.0,0.0,3.0,3.0,5.0,0.0,0.0,4.0,4.0,18.0
510158,2013-06-20,41200407,1610612759,SAS,San Antonio,1495,Tim Duncan,43:10,8.0,18.0,...,1.0,4.0,8.0,12.0,2.0,4.0,1.0,3.0,4.0,24.0
510159,2013-06-20,41200407,1610612759,SAS,San Antonio,201980,Danny Green,36:27,1.0,12.0,...,1.0,1.0,4.0,5.0,0.0,2.0,1.0,2.0,3.0,5.0
510160,2013-06-20,41200407,1610612759,SAS,San Antonio,2225,Tony Parker,36:33,3.0,12.0,...,1.0,0.0,0.0,0.0,4.0,3.0,0.0,2.0,1.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
511932,2013-04-20,41200171,1610612746,LAC,Los Angeles,200797,Ryan Hollins,8:40,1.0,2.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,4.0,2.0
511933,2013-04-20,41200171,1610612746,LAC,Los Angeles,1885,Lamar Odom,18:21,1.0,7.0,...,0.5,3.0,4.0,7.0,3.0,0.0,1.0,2.0,3.0,4.0
511934,2013-04-20,41200171,1610612746,LAC,Los Angeles,202339,Eric Bledsoe,18:19,7.0,7.0,...,0.5,1.0,5.0,6.0,4.0,0.0,0.0,1.0,1.0,15.0
511935,2013-04-20,41200171,1610612746,LAC,Los Angeles,101142,Ronny Turiaf,9:12,2.0,2.0,...,0.5,1.0,2.0,3.0,0.0,0.0,0.0,0.0,3.0,5.0
511936,2013-04-20,41200171,1610612746,LAC,Los Angeles,2584,Willie Green,1:48,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [55]:
Playoffs_14 = details_dates[(details_dates['GAME_DATE'] >= '2014-04-19') & (details_dates['GAME_DATE'] <= '2014-06-15')]

Playoffs_14

,GAME_DATE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,MIN,2pointer_MADE,2pointer_ATTEMPTS,...,FreeThrow_PCT,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
479927,2014-06-15,41300405,1610612748,MIA,Miami,2544,LeBron James,41:16,10.0,21.0,...,0.889,1.0,9.0,10.0,5.0,0.0,2.0,1.0,1.0,31.0
479928,2014-06-15,41300405,1610612748,MIA,Miami,1740,Rashard Lewis,9:00,1.0,2.0,...,0.000,0.0,2.0,2.0,1.0,0.0,0.0,0.0,2.0,3.0
479929,2014-06-15,41300405,1610612748,MIA,Miami,2547,Chris Bosh,38:37,6.0,14.0,...,0.500,0.0,7.0,7.0,2.0,1.0,0.0,0.0,2.0,13.0
479930,2014-06-15,41300405,1610612748,MIA,Miami,2548,Dwyane Wade,36:00,4.0,12.0,...,0.500,0.0,3.0,3.0,1.0,0.0,0.0,3.0,3.0,11.0
479931,2014-06-15,41300405,1610612748,MIA,Miami,951,Ray Allen,31:20,1.0,8.0,...,1.000,1.0,4.0,5.0,2.0,1.0,0.0,4.0,2.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
481828,2014-04-19,41300151,1610612760,OKC,Oklahoma City,203500,Steven Adams,12:09,0.0,1.0,...,0.000,0.0,1.0,1.0,0.0,0.0,3.0,0.0,5.0,0.0
481829,2014-04-19,41300151,1610612760,OKC,Oklahoma City,202704,Reggie Jackson,23:54,1.0,5.0,...,0.875,0.0,8.0,8.0,4.0,0.0,1.0,0.0,2.0,9.0
481830,2014-04-19,41300151,1610612760,OKC,Oklahoma City,965,Derek Fisher,12:03,1.0,3.0,...,1.000,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,4.0
481831,2014-04-19,41300151,1610612760,OKC,Oklahoma City,201934,Hasheem Thabeet,4:03,0.0,0.0,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0
481832,2014-04-19,41300151,1610612760,OKC,Oklahoma City,203087,Jeremy Lamb,0:47,0.0,0.0,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [56]:
Playoffs_15 = details_dates[(details_dates['GAME_DATE'] >= '2015-04-18') & (details_dates['GAME_DATE'] <= '2015-06-16')]

Playoffs_15

,GAME_DATE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,MIN,2pointer_MADE,2pointer_ATTEMPTS,...,FreeThrow_PCT,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
449619,2015-06-16,41400406,1610612744,GSW,Golden State,2738,Andre Iguodala,36:21,9.0,20.0,...,0.40,1.0,4.0,5.0,5.0,2.0,0.0,0.0,4.0,25.0
449620,2015-06-16,41400406,1610612744,GSW,Golden State,203084,Harrison Barnes,35:27,3.0,8.0,...,0.00,0.0,2.0,2.0,2.0,1.0,0.0,0.0,3.0,9.0
449621,2015-06-16,41400406,1610612744,GSW,Golden State,203110,Draymond Green,41:28,6.0,13.0,...,0.50,1.0,10.0,11.0,10.0,3.0,1.0,3.0,5.0,16.0
449622,2015-06-16,41400406,1610612744,GSW,Golden State,202691,Klay Thompson,24:40,2.0,7.0,...,0.00,0.0,5.0,5.0,2.0,0.0,1.0,2.0,6.0,5.0
449623,2015-06-16,41400406,1610612744,GSW,Golden State,201939,Stephen Curry,43:06,8.0,19.0,...,0.75,0.0,6.0,6.0,8.0,3.0,0.0,3.0,3.0,25.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
451267,2015-04-18,41400141,1610612744,GSW,Golden State,2738,Andre Iguodala,31:18,2.0,6.0,...,0.50,0.0,4.0,4.0,3.0,1.0,0.0,0.0,2.0,8.0
451268,2015-04-18,41400141,1610612744,GSW,Golden State,2571,Leandro Barbosa,11:23,0.0,3.0,...,0.00,2.0,2.0,4.0,0.0,0.0,0.0,0.0,1.0,0.0
451269,2015-04-18,41400141,1610612744,GSW,Golden State,203105,Festus Ezeli,3:14,0.0,0.0,...,1.00,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0
451270,2015-04-18,41400141,1610612744,GSW,Golden State,2733,Shaun Livingston,13:02,1.0,3.0,...,0.00,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,2.0
451271,2015-04-18,41400141,1610612744,GSW,Golden State,201578,Marreese Speights,0:41,0.0,0.0,...,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [57]:
Playoffs_16 = details_dates[(details_dates['GAME_DATE'] >= '2016-04-16') & (details_dates['GAME_DATE'] <= '2016-06-19')]

Playoffs_16

,GAME_DATE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,MIN,2pointer_MADE,2pointer_ATTEMPTS,...,FreeThrow_PCT,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
419040,2016-06-19,41500407,1610612739,CLE,Cleveland,2544,LeBron James,46:49,9.0,24.0,...,0.800,1.0,10.0,11.0,11.0,2.0,3.0,5.0,1.0,27.0
419041,2016-06-19,41500407,1610612739,CLE,Cleveland,201567,Kevin Love,30:02,3.0,9.0,...,0.750,4.0,10.0,14.0,3.0,2.0,0.0,1.0,2.0,9.0
419042,2016-06-19,41500407,1610612739,CLE,Cleveland,202684,Tristan Thompson,31:49,3.0,3.0,...,0.750,0.0,3.0,3.0,0.0,0.0,2.0,0.0,4.0,9.0
419043,2016-06-19,41500407,1610612739,CLE,Cleveland,2747,JR Smith,38:55,5.0,13.0,...,0.000,0.0,4.0,4.0,2.0,1.0,0.0,2.0,3.0,12.0
419044,2016-06-19,41500407,1610612739,CLE,Cleveland,202681,Kyrie Irving,43:00,10.0,23.0,...,1.000,3.0,3.0,6.0,1.0,1.0,1.0,2.0,3.0,26.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
420935,2016-04-16,41500111,1610612761,TOR,Toronto,202335,Patrick Patterson,27:48,4.0,5.0,...,0.000,3.0,3.0,6.0,1.0,0.0,1.0,1.0,1.0,9.0
420936,2016-04-16,41500111,1610612761,TOR,Toronto,201960,DeMarre Carroll,19:17,2.0,4.0,...,1.000,1.0,1.0,2.0,1.0,0.0,0.0,1.0,1.0,6.0
420937,2016-04-16,41500111,1610612761,TOR,Toronto,202687,Bismack Biyombo,24:29,1.0,2.0,...,0.667,1.0,7.0,8.0,0.0,0.0,2.0,2.0,1.0,6.0
420938,2016-04-16,41500111,1610612761,TOR,Toronto,202709,Cory Joseph,24:11,5.0,6.0,...,0.875,1.0,2.0,3.0,3.0,1.0,0.0,2.0,4.0,18.0
420939,2016-04-16,41500111,1610612761,TOR,Toronto,203082,Terrence Ross,13:59,2.0,8.0,...,0.000,0.0,1.0,1.0,0.0,0.0,0.0,2.0,3.0,5.0

In [58]:
Playoffs_17 = details_dates[(details_dates['GAME_DATE'] >= '2017-04-15') & (details_dates['GAME_DATE'] <= '2017-06-12')]

Playoffs_17

,GAME_DATE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,MIN,2pointer_MADE,2pointer_ATTEMPTS,...,FreeThrow_PCT,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
388624,2017-06-12,41600405,1610612739,CLE,Cleveland,2544,LeBron James,46:13,19.0,30.0,...,0.25,2.0,11.0,13.0,8.0,2.0,1.0,2.0,3.0,41.0
388625,2017-06-12,41600405,1610612739,CLE,Cleveland,201567,Kevin Love,29:55,2.0,8.0,...,0.40,3.0,7.0,10.0,2.0,0.0,1.0,0.0,2.0,6.0
388626,2017-06-12,41600405,1610612739,CLE,Cleveland,202684,Tristan Thompson,29:52,6.0,8.0,...,0.75,4.0,4.0,8.0,3.0,1.0,1.0,3.0,1.0,15.0
388627,2017-06-12,41600405,1610612739,CLE,Cleveland,2747,JR Smith,40:49,9.0,11.0,...,0.00,0.0,3.0,3.0,1.0,0.0,2.0,0.0,2.0,25.0
388628,2017-06-12,41600405,1610612739,CLE,Cleveland,202681,Kyrie Irving,41:47,9.0,22.0,...,1.00,1.0,1.0,2.0,6.0,2.0,0.0,4.0,3.0,26.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390356,2017-04-15,41600121,1610612761,TOR,Toronto,1626181,Norman Powell,5:45,2.0,4.0,...,0.00,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,5.0
390357,2017-04-15,41600121,1610612761,TOR,Toronto,1627832,Fred VanVleet,1:46,0.0,0.0,...,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
390358,2017-04-15,41600121,1610612761,TOR,Toronto,1626153,Delon Wright,1:46,0.0,1.0,...,0.00,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
390359,2017-04-15,41600121,1610612761,TOR,Toronto,1627751,Jakob Poeltl,1:46,0.0,0.0,...,0.00,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
390360,2017-04-15,41600121,1610612761,TOR,Toronto,203512,Lucas Nogueira,1:22,0.0,1.0,...,0.50,2.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,1.0

In [59]:
Playoffs_18 = details_dates[(details_dates['GAME_DATE'] >= '2018-04-16') & (details_dates['GAME_DATE'] <= '2018-06-08')]

Playoffs_18

,GAME_DATE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,MIN,2pointer_MADE,2pointer_ATTEMPTS,...,FreeThrow_PCT,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
358855,2018-06-08,41700404,1610612744,GSW,Golden State,201142,Kevin Durant,37:38,7.0,17.0,...,1.0,1.0,11.0,12.0,10.0,1.0,3.0,2.0,3.0,20.0
358856,2018-06-08,41700404,1610612744,GSW,Golden State,203110,Draymond Green,38:37,4.0,8.0,...,0.0,1.0,2.0,3.0,9.0,1.0,3.0,1.0,5.0,9.0
358857,2018-06-08,41700404,1610612744,GSW,Golden State,201580,JaVale McGee,16:28,3.0,4.0,...,0.0,1.0,2.0,3.0,0.0,0.0,1.0,0.0,1.0,6.0
358858,2018-06-08,41700404,1610612744,GSW,Golden State,202691,Klay Thompson,28:30,4.0,10.0,...,0.0,0.0,6.0,6.0,0.0,0.0,0.0,2.0,3.0,10.0
358859,2018-06-08,41700404,1610612744,GSW,Golden State,201939,Stephen Curry,38:45,12.0,27.0,...,1.0,2.0,4.0,6.0,4.0,3.0,3.0,2.0,4.0,37.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360408,2018-04-16,41700122,1610612755,PHI,Philadelphia,101161,Amir Johnson,21:40,3.0,5.0,...,0.0,2.0,5.0,7.0,2.0,1.0,0.0,1.0,2.0,6.0
360409,2018-04-16,41700122,1610612755,PHI,Philadelphia,201158,Marco Belinelli,29:43,5.0,13.0,...,0.8,0.0,2.0,2.0,0.0,1.0,0.0,1.0,3.0,16.0
360410,2018-04-16,41700122,1610612755,PHI,Philadelphia,1628365,Markelle Fultz,4:38,0.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
360411,2018-04-16,41700122,1610612755,PHI,Philadelphia,1626158,Richaun Holmes,3:01,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,2.0,0.0
360412,2018-04-16,41700122,1610612755,PHI,Philadelphia,204456,T.J. McConnell,6:23,0.0,1.0,...,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,2.0

In [60]:
Playoffs_19 = details_dates[(details_dates['GAME_DATE'] >= '2019-04-13') & (details_dates['GAME_DATE'] <= '2019-06-13')]

Playoffs_19

,GAME_DATE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,MIN,2pointer_MADE,2pointer_ATTEMPTS,...,FreeThrow_PCT,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
329157,2019-06-13,41800406,1610612761,TOR,Toronto,202695,Kawhi Leonard,41:05,7.0,16.0,...,0.875,1.0,5.0,6.0,3.0,2.0,1.0,2.0,4.0,22.0
329158,2019-06-13,41800406,1610612761,TOR,Toronto,1627783,Pascal Siakam,46:10,10.0,17.0,...,0.750,2.0,8.0,10.0,3.0,1.0,1.0,2.0,2.0,26.0
329159,2019-06-13,41800406,1610612761,TOR,Toronto,201188,Marc Gasol,26:34,0.0,5.0,...,0.750,3.0,6.0,9.0,4.0,0.0,0.0,1.0,4.0,3.0
329160,2019-06-13,41800406,1610612761,TOR,Toronto,201980,Danny Green,17:44,0.0,0.0,...,0.000,0.0,1.0,1.0,3.0,1.0,0.0,1.0,1.0,0.0
329161,2019-06-13,41800406,1610612761,TOR,Toronto,200768,Kyle Lowry,41:42,9.0,16.0,...,0.667,2.0,5.0,7.0,10.0,3.0,0.0,3.0,5.0,26.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
330913,2019-04-13,41800121,1610612755,PHI,Philadelphia,204456,T.J. McConnell,15:50,2.0,4.0,...,0.000,0.0,0.0,0.0,3.0,0.0,0.0,0.0,1.0,4.0
330914,2019-04-13,41800121,1610612755,PHI,Philadelphia,203118,Mike Scott,32:28,1.0,8.0,...,0.000,0.0,5.0,5.0,0.0,1.0,0.0,1.0,4.0,3.0
330915,2019-04-13,41800121,1610612755,PHI,Philadelphia,203613,Jonathon Simmons,11:26,2.0,5.0,...,0.000,1.0,1.0,2.0,0.0,0.0,0.0,0.0,1.0,4.0
330916,2019-04-13,41800121,1610612755,PHI,Philadelphia,1629015,Zhaire Smith,1:20,0.0,0.0,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
330917,2019-04-13,41800121,1610612755,PHI,Philadelphia,1628413,Jonah Bolden,5:07,1.0,2.0,...,0.000,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0

In [61]:
Playoffs_20 = details_dates[(details_dates['GAME_DATE'] >= '2020-08-17') & (details_dates['GAME_DATE'] <= '2020-10-11')]

Playoffs_20

,GAME_DATE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,MIN,2pointer_MADE,2pointer_ATTEMPTS,...,FreeThrow_PCT,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
49948,2020-10-11,41900406,1610612747,LAL,Los Angeles,2544,LeBron James,41:13,13.0,20.0,...,0.250,3.0,11.0,14.0,10.0,1.0,0.0,1.0,3.0,28.0
49949,2020-10-11,41900406,1610612747,LAL,Los Angeles,201980,Danny Green,24:34,4.0,10.0,...,0.000,2.0,3.0,5.0,1.0,0.0,1.0,0.0,2.0,11.0
49950,2020-10-11,41900406,1610612747,LAL,Los Angeles,203076,Anthony Davis,35:06,7.0,17.0,...,0.714,4.0,11.0,15.0,3.0,1.0,2.0,3.0,4.0,19.0
49951,2020-10-11,41900406,1610612747,LAL,Los Angeles,1627936,Alex Caruso,32:42,2.0,7.0,...,0.000,1.0,2.0,3.0,5.0,1.0,1.0,1.0,2.0,4.0
49952,2020-10-11,41900406,1610612747,LAL,Los Angeles,203484,Kentavious Caldwell-Pope,33:26,6.0,13.0,...,1.000,1.0,1.0,2.0,0.0,1.0,0.0,2.0,5.0,17.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51637,2020-08-17,41900151,1610612746,LAC,LA,1626149,Montrezl Harrell,14:59,2.0,5.0,...,0.500,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,6.0
51638,2020-08-17,41900151,1610612746,LAC,LA,202704,Reggie Jackson,16:20,0.0,5.0,...,0.000,0.0,3.0,3.0,1.0,0.0,0.0,0.0,2.0,0.0
51639,2020-08-17,41900151,1610612746,LAC,LA,203210,JaMychal Green,18:03,2.0,3.0,...,0.000,1.0,1.0,2.0,0.0,0.0,1.0,0.0,3.0,5.0
51640,2020-08-17,41900151,1610612746,LAC,LA,1629013,Landry Shamet,8:21,0.0,1.0,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
51641,2020-08-17,41900151,1610612746,LAC,LA,1629611,Terance Mann,0:17,0.0,0.0,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [62]:
Playoffs_21 = details_dates[(details_dates['GAME_DATE'] >= '2021-05-22') & (details_dates['GAME_DATE'] <= '2021-07-20')]

Playoffs_21

,GAME_DATE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,MIN,2pointer_MADE,2pointer_ATTEMPTS,...,FreeThrow_PCT,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
23291,2021-07-20,42000406,1610612756,PHX,Phoenix,1628969,Mikal Bridges,39:28,3.0,7.0,...,0.50,1.0,5.0,6.0,2.0,2.0,0.0,0.0,4.0,7.0
23292,2021-07-20,42000406,1610612756,PHX,Phoenix,203109,Jae Crowder,40:33,4.0,11.0,...,1.00,2.0,11.0,13.0,0.0,4.0,1.0,2.0,3.0,15.0
23293,2021-07-20,42000406,1610612756,PHX,Phoenix,1629028,Deandre Ayton,36:12,4.0,12.0,...,0.80,1.0,5.0,6.0,1.0,2.0,2.0,2.0,5.0,12.0
23294,2021-07-20,42000406,1610612756,PHX,Phoenix,1626164,Devin Booker,46:15,8.0,22.0,...,1.00,0.0,3.0,3.0,5.0,0.0,0.0,6.0,4.0,19.0
23295,2021-07-20,42000406,1610612756,PHX,Phoenix,101108,Chris Paul,39:13,11.0,19.0,...,0.75,1.0,1.0,2.0,5.0,1.0,0.0,3.0,5.0,26.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25150,2021-05-22,42000161,1610612743,DEN,Denver,1630267,Facundo Campazzo,31:32,3.0,4.0,...,0.00,2.0,1.0,3.0,5.0,2.0,1.0,1.0,3.0,8.0
25151,2021-05-22,42000161,1610612743,DEN,Denver,1628420,Monte Morris,21:59,5.0,10.0,...,0.00,0.0,2.0,2.0,5.0,0.0,0.0,1.0,4.0,10.0
25152,2021-05-22,42000161,1610612743,DEN,Denver,203210,JaMychal Green,17:37,0.0,1.0,...,0.00,0.0,1.0,1.0,3.0,0.0,1.0,0.0,2.0,0.0
25153,2021-05-22,42000161,1610612743,DEN,Denver,1630210,Markus Howard,19:58,3.0,5.0,...,0.00,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,7.0
25154,2021-05-22,42000161,1610612743,DEN,Denver,200794,Paul Millsap,14:43,1.0,3.0,...,0.00,0.0,3.0,3.0,4.0,1.0,0.0,2.0,2.0,3.0

# Playoff Stats

In [63]:
frames = [Playoffs_04, Playoffs_05, Playoffs_06, Playoffs_07, Playoffs_08, Playoffs_09, Playoffs_10, Playoffs_11, 
          Playoffs_12, Playoffs_13, Playoffs_14, Playoffs_15, Playoffs_16, Playoffs_17, Playoffs_18, Playoffs_19, 
          Playoffs_20, Playoffs_21]

In [64]:
Playoff_stats_df = pd.concat(frames)
Playoff_stats_df

,GAME_DATE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,MIN,2pointer_MADE,2pointer_ATTEMPTS,...,FreeThrow_PCT,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
213209,2004-06-15,40300405,1610612747,LAL,Los Angeles,1904,Devean George,20:22,2.0,6.0,...,0.000,2.0,1.0,3.0,2.0,0.0,1.0,0.0,4.0,4.0
213210,2004-06-15,40300405,1610612747,LAL,Los Angeles,2098,Slava Medvedenko,23:25,4.0,8.0,...,1.000,2.0,3.0,5.0,1.0,0.0,0.0,1.0,1.0,10.0
213211,2004-06-15,40300405,1610612747,LAL,Los Angeles,406,Shaquille O'Neal,35:33,7.0,13.0,...,0.375,2.0,6.0,8.0,1.0,1.0,0.0,1.0,4.0,20.0
213212,2004-06-15,40300405,1610612747,LAL,Los Angeles,977,Kobe Bryant,45:34,7.0,21.0,...,0.909,1.0,2.0,3.0,4.0,1.0,0.0,3.0,2.0,24.0
213213,2004-06-15,40300405,1610612747,LAL,Los Angeles,56,Gary Payton,30:47,1.0,3.0,...,0.000,2.0,2.0,4.0,4.0,2.0,1.0,1.0,2.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25150,2021-05-22,42000161,1610612743,DEN,Denver,1630267,Facundo Campazzo,31:32,3.0,4.0,...,0.000,2.0,1.0,3.0,5.0,2.0,1.0,1.0,3.0,8.0
25151,2021-05-22,42000161,1610612743,DEN,Denver,1628420,Monte Morris,21:59,5.0,10.0,...,0.000,0.0,2.0,2.0,5.0,0.0,0.0,1.0,4.0,10.0
25152,2021-05-22,42000161,1610612743,DEN,Denver,203210,JaMychal Green,17:37,0.0,1.0,...,0.000,0.0,1.0,1.0,3.0,0.0,1.0,0.0,2.0,0.0
25153,2021-05-22,42000161,1610612743,DEN,Denver,1630210,Markus Howard,19:58,3.0,5.0,...,0.000,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,7.0
25154,2021-05-22,42000161,1610612743,DEN,Denver,200794,Paul Millsap,14:43,1.0,3.0,...,0.000,0.0,3.0,3.0,4.0,1.0,0.0,2.0,2.0,3.0

In [65]:
Playoff_stats_df.columns

Index(['GAME_DATE', 'GAME_ID', 'TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_CITY',
       'PLAYER_ID', 'PLAYER_NAME', 'MIN', '2pointer_MADE', '2pointer_ATTEMPTS',
       '2pointer_PCT', '3pointer_MADE', '3pointer_ATTEMPTS', '3pointer_PCT',
       'FreeThrow_MADE', 'FreeThrow_ATTEMPTS', 'FreeThrow_PCT',
       'OFFENSIVE_REBOUNDS', 'DEFENSIVE_REBOUNDS', 'REBOUNDS_TOTAL', 'ASSISTS',
       'STEALS', 'BLOCKS', 'TURNOVERS', 'PERSONAL_FOULS', 'POINTS'],
      dtype='object')

In [66]:
New_playoff_stats_df = Playoff_stats_df[['TEAM_ID', 'PLAYER_ID', 'PLAYER_NAME', '2pointer_MADE', '2pointer_ATTEMPTS',
                        '3pointer_MADE', '3pointer_ATTEMPTS', 'FreeThrow_MADE', 'FreeThrow_ATTEMPTS', 'OFFENSIVE_REBOUNDS', 
                         'DEFENSIVE_REBOUNDS', 'REBOUNDS_TOTAL', 'ASSISTS','STEALS', 'BLOCKS', 'TURNOVERS', 'PERSONAL_FOULS', 'POINTS']]
New_playoff_stats_df

,TEAM_ID,PLAYER_ID,PLAYER_NAME,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
213209,1610612747,1904,Devean George,2.0,6.0,0.0,2.0,0.0,0.0,2.0,1.0,3.0,2.0,0.0,1.0,0.0,4.0,4.0
213210,1610612747,2098,Slava Medvedenko,4.0,8.0,0.0,0.0,2.0,2.0,2.0,3.0,5.0,1.0,0.0,0.0,1.0,1.0,10.0
213211,1610612747,406,Shaquille O'Neal,7.0,13.0,0.0,0.0,6.0,16.0,2.0,6.0,8.0,1.0,1.0,0.0,1.0,4.0,20.0
213212,1610612747,977,Kobe Bryant,7.0,21.0,0.0,2.0,10.0,11.0,1.0,2.0,3.0,4.0,1.0,0.0,3.0,2.0,24.0
213213,1610612747,56,Gary Payton,1.0,3.0,0.0,1.0,0.0,0.0,2.0,2.0,4.0,4.0,2.0,1.0,1.0,2.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25150,1610612743,1630267,Facundo Campazzo,3.0,4.0,2.0,3.0,0.0,0.0,2.0,1.0,3.0,5.0,2.0,1.0,1.0,3.0,8.0
25151,1610612743,1628420,Monte Morris,5.0,10.0,0.0,1.0,0.0,0.0,0.0,2.0,2.0,5.0,0.0,0.0,1.0,4.0,10.0
25152,1610612743,203210,JaMychal Green,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,3.0,0.0,1.0,0.0,2.0,0.0
25153,1610612743,1630210,Markus Howard,3.0,5.0,1.0,3.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,7.0
25154,1610612743,200794,Paul Millsap,1.0,3.0,1.0,2.0,0.0,0.0,0.0,3.0,3.0,4.0,1.0,0.0,2.0,2.0,3.0

In [67]:
All_playoffs_by_player = New_playoff_stats_df.groupby(['PLAYER_NAME']).agg({'TEAM_ID': 'last', 'PLAYER_ID': 'last',
                                                            '2pointer_MADE': 'sum', '2pointer_ATTEMPTS': 'sum',
                                                            '3pointer_MADE': 'sum', '3pointer_ATTEMPTS': 'sum', 'FreeThrow_MADE': 'sum', 
                                                            'FreeThrow_ATTEMPTS': 'sum', 'OFFENSIVE_REBOUNDS': 'sum', 
                                                            'DEFENSIVE_REBOUNDS': 'sum', 'REBOUNDS_TOTAL': 'sum', 'ASSISTS': 'sum',
                                                            'STEALS': 'sum', 'BLOCKS': 'sum', 'TURNOVERS': 'sum', 'PERSONAL_FOULS': 'sum', 
                                                            'POINTS': 'sum'}).reset_index()
All_playoffs_by_player

,PLAYER_NAME,TEAM_ID,PLAYER_ID,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,AJ Price,1610612754,201985,14.0,37.0,7.0,16.0,9.0,10.0,3.0,6.0,9.0,7.0,3.0,0.0,7.0,5.0,44.0
1,Aaron Brooks,1610612750,201166,123.0,296.0,37.0,112.0,53.0,71.0,10.0,58.0,68.0,70.0,9.0,5.0,48.0,59.0,336.0
2,Aaron Gordon,1610612743,203932,72.0,161.0,17.0,43.0,26.0,44.0,32.0,58.0,90.0,38.0,11.0,4.0,27.0,39.0,187.0
3,Aaron Gray,1610612740,201189,9.0,15.0,0.0,0.0,3.0,8.0,3.0,19.0,22.0,2.0,2.0,2.0,6.0,13.0,21.0
4,Aaron Harrison,1610612766,1626151,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1123,Zeljko Rebraca,1610612746,1442,1.0,3.0,0.0,0.0,0.0,0.0,1.0,3.0,4.0,0.0,0.0,1.0,2.0,6.0,2.0
1124,Zhaire Smith,1610612755,1629015,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1125,Zhou Qi,1610612745,1627753,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0
1126,Zoran Planinic,1610612751,2565,0.0,3.0,0.0,1.0,1.0,4.0,0.0,2.0,2.0,4.0,1.0,0.0,3.0,3.0,1.0
1127,Zydrunas Ilgauskas,1610612748,980,299.0,637.0,2.0,13.0,147.0,190.0,181.0,344.0,525.0,71.0,24.0,80.0,96.0,214.0,747.0

In [68]:
All_playoffs_by_player_df = All_playoffs_by_player.copy().rename(columns = {'2pointer_MADE': '_2pointer_MADE', '2pointer_ATTEMPTS': '_2pointer_ATTEMPTS',
                                                            '3pointer_MADE': '_3pointer_MADE', '3pointer_ATTEMPTS': '_3pointer_ATTEMPTS'})

All_playoffs_by_player_df

,PLAYER_NAME,TEAM_ID,PLAYER_ID,_2pointer_MADE,_2pointer_ATTEMPTS,_3pointer_MADE,_3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,AJ Price,1610612754,201985,14.0,37.0,7.0,16.0,9.0,10.0,3.0,6.0,9.0,7.0,3.0,0.0,7.0,5.0,44.0
1,Aaron Brooks,1610612750,201166,123.0,296.0,37.0,112.0,53.0,71.0,10.0,58.0,68.0,70.0,9.0,5.0,48.0,59.0,336.0
2,Aaron Gordon,1610612743,203932,72.0,161.0,17.0,43.0,26.0,44.0,32.0,58.0,90.0,38.0,11.0,4.0,27.0,39.0,187.0
3,Aaron Gray,1610612740,201189,9.0,15.0,0.0,0.0,3.0,8.0,3.0,19.0,22.0,2.0,2.0,2.0,6.0,13.0,21.0
4,Aaron Harrison,1610612766,1626151,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1123,Zeljko Rebraca,1610612746,1442,1.0,3.0,0.0,0.0,0.0,0.0,1.0,3.0,4.0,0.0,0.0,1.0,2.0,6.0,2.0
1124,Zhaire Smith,1610612755,1629015,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1125,Zhou Qi,1610612745,1627753,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0
1126,Zoran Planinic,1610612751,2565,0.0,3.0,0.0,1.0,1.0,4.0,0.0,2.0,2.0,4.0,1.0,0.0,3.0,3.0,1.0
1127,Zydrunas Ilgauskas,1610612748,980,299.0,637.0,2.0,13.0,147.0,190.0,181.0,344.0,525.0,71.0,24.0,80.0,96.0,214.0,747.0

In [69]:
All_playoffs_by_player_df['_2pointer_PCT'] = All_playoffs_by_player_df['_2pointer_MADE']/All_playoffs_by_player_df['_2pointer_ATTEMPTS']

In [70]:
All_playoffs_by_player_df['_3pointer_PCT'] = All_playoffs_by_player_df['_3pointer_MADE']/All_playoffs_by_player_df['_3pointer_ATTEMPTS']

In [71]:
All_playoffs_by_player_df['FreeThrow_PCT'] = All_playoffs_by_player_df['FreeThrow_MADE']/All_playoffs_by_player_df['FreeThrow_ATTEMPTS']

In [72]:
All_playoffs_by_player_df.columns

Index(['PLAYER_NAME', 'TEAM_ID', 'PLAYER_ID', '_2pointer_MADE',
       '_2pointer_ATTEMPTS', '_3pointer_MADE', '_3pointer_ATTEMPTS',
       'FreeThrow_MADE', 'FreeThrow_ATTEMPTS', 'OFFENSIVE_REBOUNDS',
       'DEFENSIVE_REBOUNDS', 'REBOUNDS_TOTAL', 'ASSISTS', 'STEALS', 'BLOCKS',
       'TURNOVERS', 'PERSONAL_FOULS', 'POINTS', '_2pointer_PCT',
       '_3pointer_PCT', 'FreeThrow_PCT'],
      dtype='object')

In [73]:
All_playoffs_by_player_df = All_playoffs_by_player_df[['PLAYER_NAME', 'TEAM_ID', 'PLAYER_ID', '_2pointer_MADE',
       '_2pointer_ATTEMPTS', '_2pointer_PCT', '_3pointer_MADE', '_3pointer_ATTEMPTS', '_3pointer_PCT',
       'FreeThrow_MADE', 'FreeThrow_ATTEMPTS', 'FreeThrow_PCT', 'OFFENSIVE_REBOUNDS',
       'DEFENSIVE_REBOUNDS', 'REBOUNDS_TOTAL', 'ASSISTS', 'STEALS', 'BLOCKS',
       'TURNOVERS', 'PERSONAL_FOULS', 'POINTS']]

All_playoffs_by_player_df

,PLAYER_NAME,TEAM_ID,PLAYER_ID,_2pointer_MADE,_2pointer_ATTEMPTS,_2pointer_PCT,_3pointer_MADE,_3pointer_ATTEMPTS,_3pointer_PCT,FreeThrow_MADE,...,FreeThrow_PCT,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,AJ Price,1610612754,201985,14.0,37.0,0.378378,7.0,16.0,0.437500,9.0,...,0.900000,3.0,6.0,9.0,7.0,3.0,0.0,7.0,5.0,44.0
1,Aaron Brooks,1610612750,201166,123.0,296.0,0.415541,37.0,112.0,0.330357,53.0,...,0.746479,10.0,58.0,68.0,70.0,9.0,5.0,48.0,59.0,336.0
2,Aaron Gordon,1610612743,203932,72.0,161.0,0.447205,17.0,43.0,0.395349,26.0,...,0.590909,32.0,58.0,90.0,38.0,11.0,4.0,27.0,39.0,187.0
3,Aaron Gray,1610612740,201189,9.0,15.0,0.600000,0.0,0.0,NaN,3.0,...,0.375000,3.0,19.0,22.0,2.0,2.0,2.0,6.0,13.0,21.0
4,Aaron Harrison,1610612766,1626151,0.0,0.0,NaN,0.0,0.0,NaN,0.0,...,NaN,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1123,Zeljko Rebraca,1610612746,1442,1.0,3.0,0.333333,0.0,0.0,NaN,0.0,...,NaN,1.0,3.0,4.0,0.0,0.0,1.0,2.0,6.0,2.0
1124,Zhaire Smith,1610612755,1629015,0.0,0.0,NaN,0.0,0.0,NaN,0.0,...,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1125,Zhou Qi,1610612745,1627753,1.0,1.0,1.000000,0.0,0.0,NaN,0.0,...,NaN,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0
1126,Zoran Planinic,1610612751,2565,0.0,3.0,0.000000,0.0,1.0,0.000000,1.0,...,0.250000,0.0,2.0,2.0,4.0,1.0,0.0,3.0,3.0,1.0
1127,Zydrunas Ilgauskas,1610612748,980,299.0,637.0,0.469388,2.0,13.0,0.153846,147.0,...,0.773684,181.0,344.0,525.0,71.0,24.0,80.0,96.0,214.0,747.0

In [74]:
All_playoffs_by_player_df = All_playoffs_by_player_df.fillna(0)

In [75]:
All_playoffs_by_player_df.isnull().sum()

PLAYER_NAME           0
TEAM_ID               0
PLAYER_ID             0
_2pointer_MADE        0
_2pointer_ATTEMPTS    0
_2pointer_PCT         0
_3pointer_MADE        0
_3pointer_ATTEMPTS    0
_3pointer_PCT         0
FreeThrow_MADE        0
FreeThrow_ATTEMPTS    0
FreeThrow_PCT         0
OFFENSIVE_REBOUNDS    0
DEFENSIVE_REBOUNDS    0
REBOUNDS_TOTAL        0
ASSISTS               0
STEALS                0
BLOCKS                0
TURNOVERS             0
PERSONAL_FOULS        0
POINTS                0
dtype: int64

In [76]:
All_playoffs_by_player_df['_2pointer_PCT'] = All_playoffs_by_player_df['_2pointer_PCT'].round(3)

In [77]:
All_playoffs_by_player_df['_3pointer_PCT'] = All_playoffs_by_player_df['_3pointer_PCT'].round(3)

In [78]:
All_playoffs_by_player_df['FreeThrow_PCT'] = All_playoffs_by_player_df['FreeThrow_PCT'].round(3)

In [79]:
All_playoffs_by_player_df

,PLAYER_NAME,TEAM_ID,PLAYER_ID,_2pointer_MADE,_2pointer_ATTEMPTS,_2pointer_PCT,_3pointer_MADE,_3pointer_ATTEMPTS,_3pointer_PCT,FreeThrow_MADE,...,FreeThrow_PCT,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,AJ Price,1610612754,201985,14.0,37.0,0.378,7.0,16.0,0.438,9.0,...,0.900,3.0,6.0,9.0,7.0,3.0,0.0,7.0,5.0,44.0
1,Aaron Brooks,1610612750,201166,123.0,296.0,0.416,37.0,112.0,0.330,53.0,...,0.746,10.0,58.0,68.0,70.0,9.0,5.0,48.0,59.0,336.0
2,Aaron Gordon,1610612743,203932,72.0,161.0,0.447,17.0,43.0,0.395,26.0,...,0.591,32.0,58.0,90.0,38.0,11.0,4.0,27.0,39.0,187.0
3,Aaron Gray,1610612740,201189,9.0,15.0,0.600,0.0,0.0,0.000,3.0,...,0.375,3.0,19.0,22.0,2.0,2.0,2.0,6.0,13.0,21.0
4,Aaron Harrison,1610612766,1626151,0.0,0.0,0.000,0.0,0.0,0.000,0.0,...,0.000,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1123,Zeljko Rebraca,1610612746,1442,1.0,3.0,0.333,0.0,0.0,0.000,0.0,...,0.000,1.0,3.0,4.0,0.0,0.0,1.0,2.0,6.0,2.0
1124,Zhaire Smith,1610612755,1629015,0.0,0.0,0.000,0.0,0.0,0.000,0.0,...,0.000,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1125,Zhou Qi,1610612745,1627753,1.0,1.0,1.000,0.0,0.0,0.000,0.0,...,0.000,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0
1126,Zoran Planinic,1610612751,2565,0.0,3.0,0.000,0.0,1.0,0.000,1.0,...,0.250,0.0,2.0,2.0,4.0,1.0,0.0,3.0,3.0,1.0
1127,Zydrunas Ilgauskas,1610612748,980,299.0,637.0,0.469,2.0,13.0,0.154,147.0,...,0.774,181.0,344.0,525.0,71.0,24.0,80.0,96.0,214.0,747.0

In [80]:
from sqlalchemy import create_engine
from config import db_password

In [81]:
db_string = f"postgresql://postgres:{db_password}@127.0.0.1:5432/Final_Project"

engine = create_engine(db_string)

All_playoffs_by_player_df.to_sql(name='playoffs_by_player', con=engine)

In [82]:
# Playoff_stats_df.to_csv('../Resources/Playoffs_player_data.csv')

# Regular Season Stats

In [83]:
Reg_season_df = details_dates.drop(Playoff_stats_df.index)

Reg_season_df

,GAME_DATE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,MIN,2pointer_MADE,2pointer_ATTEMPTS,...,FreeThrow_PCT,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,2022-03-12,22101005,1610612750,MIN,Minnesota,1630162,Anthony Edwards,36:22,4.0,10.0,...,1.000,0.0,8.0,8.0,5.0,3.0,1.0,1.0,1.0,15.0
1,2022-03-12,22101005,1610612750,MIN,Minnesota,1630183,Jaden McDaniels,23:54,6.0,8.0,...,1.000,2.0,4.0,6.0,0.0,0.0,2.0,2.0,6.0,14.0
2,2022-03-12,22101005,1610612750,MIN,Minnesota,1626157,Karl-Anthony Towns,25:17,4.0,9.0,...,0.750,1.0,9.0,10.0,0.0,0.0,0.0,3.0,4.0,15.0
3,2022-03-12,22101005,1610612750,MIN,Minnesota,1627736,Malik Beasley,30:52,4.0,9.0,...,0.000,0.0,3.0,3.0,1.0,1.0,0.0,1.0,4.0,12.0
4,2022-03-12,22101005,1610612750,MIN,Minnesota,1626156,D'Angelo Russell,33:46,3.0,13.0,...,1.000,0.0,6.0,6.0,9.0,1.0,0.0,5.0,0.0,14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540345,2012-10-06,11200005,1610612743,DEN,Denver,202706,Jordan Hamilton,19,4.0,9.0,...,0.857,0.0,2.0,2.0,0.0,2.0,0.0,1.0,3.0,17.0
540346,2012-10-06,11200005,1610612743,DEN,Denver,202702,Kenneth Faried,23,7.0,11.0,...,1.000,1.0,0.0,1.0,1.0,1.0,0.0,3.0,3.0,18.0
540347,2012-10-06,11200005,1610612743,DEN,Denver,201585,Kosta Koufos,15,3.0,7.0,...,0.000,3.0,5.0,8.0,0.0,1.0,0.0,0.0,3.0,6.0
540348,2012-10-06,11200005,1610612743,DEN,Denver,202389,Timofey Mozgov,19,1.0,1.0,...,0.000,1.0,2.0,3.0,1.0,0.0,0.0,4.0,2.0,2.0
540349,2012-10-06,11200005,1610612743,DEN,Denver,201951,Ty Lawson,27,3.0,6.0,...,0.500,0.0,2.0,2.0,6.0,2.0,0.0,6.0,1.0,8.0

In [84]:
print(Reg_season_df.GAME_DATE.min())

2003-10-05 00:00:00

# Filter by Season - Reg Season

In [85]:
Season_04 = Reg_season_df[(Reg_season_df['GAME_DATE'] >= '2003-10-28') & (Reg_season_df['GAME_DATE'] <= '2004-08-01')]

Season_04

,GAME_DATE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,MIN,2pointer_MADE,2pointer_ATTEMPTS,...,FreeThrow_PCT,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
214863,2004-04-14,20301183,1610612750,MIN,Minnesota,84,Latrell Sprewell,29:14,8.0,13.0,...,1.0,0.0,2.0,2.0,2.0,2.0,0.0,2.0,0.0,20.0
214864,2004-04-14,20301183,1610612750,MIN,Minnesota,708,Kevin Garnett,31:05,9.0,13.0,...,1.0,2.0,7.0,9.0,2.0,1.0,2.0,0.0,1.0,26.0
214865,2004-04-14,20301183,1610612750,MIN,Minnesota,911,Ervin Johnson,7:02,0.0,1.0,...,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,4.0,0.0
214866,2004-04-14,20301183,1610612750,MIN,Minnesota,208,Sam Cassell,24:06,7.0,9.0,...,1.0,0.0,2.0,2.0,8.0,1.0,0.0,1.0,2.0,17.0
214867,2004-04-14,20301183,1610612750,MIN,Minnesota,2239,Trenton Hassell,17:52,2.0,3.0,...,0.5,1.0,2.0,3.0,3.0,1.0,1.0,1.0,1.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238735,2003-10-28,20300003,1610612747,LAL,Los Angeles,935,Bryon Russell,20:47,3.0,7.0,...,1.0,0.0,0.0,0.0,0.0,2.0,0.0,1.0,4.0,10.0
238736,2003-10-28,20300003,1610612747,LAL,Los Angeles,270,Horace Grant,20:53,1.0,2.0,...,0.5,0.0,5.0,5.0,2.0,0.0,1.0,0.0,2.0,3.0
238737,2003-10-28,20300003,1610612747,LAL,Los Angeles,2575,Luke Walton,6:11,2.0,3.0,...,0.0,1.0,1.0,2.0,0.0,0.0,0.0,0.0,3.0,5.0
238738,2003-10-28,20300003,1610612747,LAL,Los Angeles,2457,Jannero Pargo,8:55,2.0,3.0,...,0.0,0.0,2.0,2.0,0.0,0.0,0.0,2.0,0.0,5.0
238739,2003-10-28,20300003,1610612747,LAL,Los Angeles,2416,Kareem Rush,14:21,1.0,5.0,...,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,4.0,2.0

In [86]:
Season_05 = Reg_season_df[(Reg_season_df['GAME_DATE'] >= '2004-11-02') & (Reg_season_df['GAME_DATE'] <= '2005-08-01')]

Season_05

,GAME_DATE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,MIN,2pointer_MADE,2pointer_ATTEMPTS,...,FreeThrow_PCT,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
187125,2005-04-20,20401230,1610612756,PHX,Phoenix,2047,Quentin Richardson,37:15,6.0,18.0,...,0.000,0.0,5.0,5.0,1.0,1.0,0.0,1.0,3.0,17.0
187126,2005-04-20,20401230,1610612756,PHX,Phoenix,1890,Shawn Marion,17:13,0.0,5.0,...,0.000,0.0,4.0,4.0,0.0,1.0,0.0,0.0,0.0,0.0
187127,2005-04-20,20401230,1610612756,PHX,Phoenix,2405,Amar'e Stoudemire,30:58,10.0,17.0,...,0.727,5.0,6.0,11.0,2.0,0.0,3.0,2.0,2.0,30.0
187128,2005-04-20,20401230,1610612756,PHX,Phoenix,2207,Joe Johnson,33:35,9.0,15.0,...,0.000,0.0,3.0,3.0,6.0,2.0,0.0,3.0,3.0,19.0
187129,2005-04-20,20401230,1610612756,PHX,Phoenix,2571,Leandro Barbosa,41:32,7.0,13.0,...,1.000,1.0,3.0,4.0,4.0,2.0,0.0,4.0,3.0,16.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212024,2004-11-02,20400003,1610612747,LAL,Los Angeles,2567,Brian Cook,25:17,5.0,10.0,...,0.000,0.0,2.0,2.0,3.0,0.0,2.0,0.0,1.0,10.0
212025,2004-11-02,20400003,1610612747,LAL,Los Angeles,1908,Jumaine Jones,20:36,1.0,4.0,...,0.000,0.0,3.0,3.0,1.0,1.0,0.0,3.0,3.0,3.0
212026,2004-11-02,20400003,1610612747,LAL,Los Angeles,2357,Tierre Brown,13:20,1.0,4.0,...,0.000,0.0,1.0,1.0,4.0,0.0,0.0,2.0,2.0,2.0
212027,2004-11-02,20400003,1610612747,LAL,Los Angeles,258,Brian Grant,10:46,1.0,1.0,...,0.000,0.0,1.0,1.0,0.0,0.0,1.0,2.0,1.0,2.0
212028,2004-11-02,20400003,1610612747,LAL,Los Angeles,2416,Kareem Rush,6:30,0.0,1.0,...,0.000,0.0,1.0,1.0,0.0,0.0,0.0,0.0,2.0,0.0

In [87]:
Season_06 = Reg_season_df[(Reg_season_df['GAME_DATE'] >= '2005-11-01') & (Reg_season_df['GAME_DATE'] <= '2006-08-01')]

Season_06

,GAME_DATE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,MIN,2pointer_MADE,2pointer_ATTEMPTS,...,FreeThrow_PCT,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
157687,2006-04-19,20501223,1610612759,SAS,San Antonio,1477,Bruce Bowen,10:14,0.0,1.0,...,0.000,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
157688,2006-04-19,20501223,1610612759,SAS,San Antonio,109,Robert Horry,21:58,0.0,5.0,...,1.000,1.0,5.0,6.0,3.0,3.0,2.0,2.0,1.0,2.0
157689,2006-04-19,20501223,1610612759,SAS,San Antonio,1737,Nazr Mohammed,21:27,2.0,8.0,...,0.750,5.0,1.0,6.0,1.0,1.0,1.0,1.0,4.0,7.0
157690,2006-04-19,20501223,1610612759,SAS,San Antonio,2757,Beno Udrih,27:37,2.0,7.0,...,0.833,0.0,1.0,1.0,2.0,1.0,0.0,2.0,1.0,9.0
157691,2006-04-19,20501223,1610612759,SAS,San Antonio,1938,Manu Ginobili,25:42,5.0,10.0,...,0.000,1.0,3.0,4.0,6.0,2.0,1.0,3.0,0.0,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182599,2005-11-01,20500003,1610612756,PHX,Phoenix,2564,Boris Diaw,23:46,3.0,4.0,...,0.500,1.0,3.0,4.0,3.0,0.0,1.0,4.0,3.0,7.0
182600,2005-11-01,20500003,1610612756,PHX,Phoenix,754,Jim Jackson,27:42,2.0,8.0,...,0.000,0.0,3.0,3.0,1.0,1.0,0.0,2.0,5.0,5.0
182601,2005-11-01,20500003,1610612756,PHX,Phoenix,2571,Leandro Barbosa,17:01,4.0,11.0,...,0.000,3.0,5.0,8.0,3.0,0.0,1.0,3.0,2.0,8.0
182602,2005-11-01,20500003,1610612756,PHX,Phoenix,258,Brian Grant,5:13,1.0,1.0,...,1.000,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,3.0
182603,2005-11-01,20500003,1610612756,PHX,Phoenix,2067,Eddie House,4:55,2.0,2.0,...,0.000,0.0,1.0,1.0,1.0,2.0,0.0,0.0,0.0,4.0

In [88]:
Season_07 = Reg_season_df[(Reg_season_df['GAME_DATE'] >= '2006-10-31') & (Reg_season_df['GAME_DATE'] <= '2007-08-01')]

Season_07

,GAME_DATE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,MIN,2pointer_MADE,2pointer_ATTEMPTS,...,FreeThrow_PCT,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
128123,2007-04-18,20601223,1610612764,WAS,Washington,2553,Jarvis Hayes,32:24,3.0,10.0,...,1.000,0.0,3.0,3.0,0.0,2.0,0.0,1.0,1.0,9.0
128124,2007-04-18,20601223,1610612764,WAS,Washington,1712,Antawn Jamison,39:24,5.0,14.0,...,0.750,0.0,11.0,11.0,1.0,1.0,0.0,1.0,3.0,19.0
128125,2007-04-18,20601223,1610612764,WAS,Washington,2041,Etan Thomas,21:10,4.0,6.0,...,0.500,2.0,6.0,8.0,0.0,1.0,4.0,2.0,2.0,10.0
128126,2007-04-18,20601223,1610612764,WAS,Washington,2052,DeShawn Stevenson,32:51,5.0,11.0,...,0.500,0.0,1.0,1.0,3.0,0.0,0.0,2.0,3.0,15.0
128127,2007-04-18,20601223,1610612764,WAS,Washington,1498,Antonio Daniels,37:52,4.0,6.0,...,0.625,0.0,5.0,5.0,9.0,0.0,0.0,1.0,0.0,13.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153203,2006-10-31,20600002,1610612747,LAL,Los Angeles,2230,Maurice Evans,29:19,8.0,13.0,...,0.500,2.0,2.0,4.0,0.0,3.0,0.0,1.0,3.0,17.0
153204,2006-10-31,20600002,1610612747,LAL,Los Angeles,101142,Ronny Turiaf,3:24,1.0,2.0,...,0.000,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0
153205,2006-10-31,20600002,1610612747,LAL,Los Angeles,2209,Vladimir Radmanovic,20:14,4.0,7.0,...,0.000,2.0,1.0,3.0,3.0,0.0,1.0,2.0,4.0,8.0
153206,2006-10-31,20600002,1610612747,LAL,Los Angeles,2567,Brian Cook,15:23,4.0,7.0,...,0.000,1.0,0.0,1.0,1.0,1.0,0.0,2.0,1.0,9.0
153207,2006-10-31,20600002,1610612747,LAL,Los Angeles,200770,Jordan Farmar,14:04,3.0,3.0,...,0.000,0.0,2.0,2.0,1.0,0.0,0.0,2.0,1.0,6.0

In [89]:
Season_08 = Reg_season_df[(Reg_season_df['GAME_DATE'] >= '2007-10-30') & (Reg_season_df['GAME_DATE'] <= '2008-08-01')]

Season_08

,GAME_DATE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,MIN,2pointer_MADE,2pointer_ATTEMPTS,...,FreeThrow_PCT,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
99329,2008-04-16,20701226,1610612746,LAC,Los Angeles,201154,Al Thornton,28:36,1.0,8.0,...,0.0,0.0,5.0,5.0,2.0,0.0,1.0,2.0,3.0,2.0
99330,2008-04-16,20701226,1610612746,LAC,Los Angeles,2694,Josh Powell,19:56,5.0,9.0,...,0.0,7.0,3.0,10.0,1.0,0.0,0.0,0.0,0.0,10.0
99331,2008-04-16,20701226,1610612746,LAC,Los Angeles,1882,Elton Brand,40:47,5.0,14.0,...,1.0,3.0,9.0,12.0,1.0,0.0,3.0,2.0,3.0,18.0
99332,2008-04-16,20701226,1610612746,LAC,Los Angeles,1749,Cuttino Mobley,37:06,3.0,8.0,...,0.0,0.0,4.0,4.0,1.0,0.0,0.0,1.0,1.0,6.0
99333,2008-04-16,20701226,1610612746,LAC,Los Angeles,2470,Smush Parker,29:04,4.0,8.0,...,0.0,0.0,2.0,2.0,2.0,1.0,0.0,4.0,2.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124209,2007-10-30,20700003,1610612744,GSW,Golden State,2440,Matt Barnes,15:29,1.0,7.0,...,0.0,2.0,2.0,4.0,1.0,0.0,1.0,2.0,2.0,2.0
124210,2007-10-30,20700003,1610612744,GSW,Golden State,1607,Troy Hudson,15:47,1.0,6.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,2.0,1.0,2.0
124211,2007-10-30,20700003,1610612744,GSW,Golden State,201158,Marco Belinelli,12:01,2.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,6.0
124212,2007-10-30,20700003,1610612744,GSW,Golden State,1506,Austin Croshere,6:47,0.0,1.0,...,0.0,0.0,2.0,2.0,1.0,0.0,0.0,0.0,1.0,0.0
124213,2007-10-30,20700003,1610612744,GSW,Golden State,200753,Patrick O'Bryant,4:44,1.0,1.0,...,0.0,0.0,2.0,2.0,1.0,0.0,0.0,0.0,2.0,2.0

In [90]:
Season_09 = Reg_season_df[(Reg_season_df['GAME_DATE'] >= '2008-10-28') & (Reg_season_df['GAME_DATE'] <= '2009-08-01')]

Season_09

,GAME_DATE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,MIN,2pointer_MADE,2pointer_ATTEMPTS,...,FreeThrow_PCT,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
70283,2009-04-15,20801225,1610612751,NJN,New Jersey,201583,Ryan Anderson,32:14,4.0,11.0,...,0.75,3.0,8.0,11.0,0.0,3.0,0.0,2.0,3.0,13.0
70284,2009-04-15,20801225,1610612751,NJN,New Jersey,2239,Trenton Hassell,16:18,2.0,6.0,...,0.00,1.0,1.0,2.0,1.0,0.0,0.0,0.0,1.0,4.0
70285,2009-04-15,20801225,1610612751,NJN,New Jersey,201572,Brook Lopez,29:42,2.0,9.0,...,1.00,3.0,4.0,7.0,1.0,0.0,3.0,2.0,1.0,6.0
70286,2009-04-15,20801225,1610612751,NJN,New Jersey,2039,Keyon Dooling,25:37,2.0,8.0,...,1.00,2.0,5.0,7.0,5.0,0.0,0.0,1.0,1.0,6.0
70287,2009-04-15,20801225,1610612751,NJN,New Jersey,201604,Chris Douglas-Roberts,44:22,6.0,16.0,...,1.00,1.0,1.0,2.0,2.0,2.0,0.0,5.0,2.0,18.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94907,2008-10-28,20800003,1610612747,LAL,Los Angeles,2772,Trevor Ariza,24:18,4.0,7.0,...,1.00,0.0,2.0,2.0,1.0,1.0,2.0,0.0,0.0,11.0
94908,2008-10-28,20800003,1610612747,LAL,Los Angeles,2756,Sasha Vujacic,12:30,2.0,6.0,...,0.00,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,5.0
94909,2008-10-28,20800003,1610612747,LAL,Los Angeles,2036,Chris Mihm,3:32,1.0,1.0,...,0.00,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,2.0
94910,2008-10-28,20800003,1610612747,LAL,Los Angeles,2694,Josh Powell,2:43,0.0,1.0,...,0.00,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
94911,2008-10-28,20800003,1610612747,LAL,Los Angeles,2575,Luke Walton,2:43,0.0,1.0,...,0.00,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [91]:
Season_10 = Reg_season_df[(Reg_season_df['GAME_DATE'] >= '2009-10-27') & (Reg_season_df['GAME_DATE'] <= '2010-08-01')]

Season_10

,GAME_DATE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,MIN,2pointer_MADE,2pointer_ATTEMPTS,...,FreeThrow_PCT,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
293479,2010-04-14,20901226,1610612752,NYK,New York,201568,Danilo Gallinari,37:28,6.0,18.0,...,0.625,1.0,3.0,4.0,2.0,1.0,0.0,3.0,3.0,22.0
293480,2010-04-14,20901226,1610612752,NYK,New York,101135,David Lee,32:54,8.0,17.0,...,1.000,6.0,5.0,11.0,5.0,1.0,1.0,5.0,4.0,19.0
293481,2010-04-14,20901226,1610612752,NYK,New York,2853,Earl Barron,39:52,4.0,10.0,...,0.750,4.0,3.0,7.0,1.0,1.0,0.0,1.0,3.0,11.0
293482,2010-04-14,20901226,1610612752,NYK,New York,201611,Henry Walker,35:11,8.0,17.0,...,0.857,2.0,5.0,7.0,1.0,0.0,0.0,0.0,3.0,28.0
293483,2010-04-14,20901226,1610612752,NYK,New York,2768,Chris Duhon,24:00,4.0,7.0,...,0.000,0.0,0.0,0.0,5.0,1.0,0.0,0.0,0.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318287,2009-10-27,20900004,1610612747,LAL,Los Angeles,2756,Sasha Vujacic,4:46,0.0,0.0,...,0.000,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
318288,2009-10-27,20900004,1610612747,LAL,Los Angeles,2788,DJ Mbenga,9:48,1.0,5.0,...,0.000,2.0,1.0,3.0,0.0,0.0,0.0,0.0,1.0,2.0
318289,2009-10-27,20900004,1610612747,LAL,Los Angeles,200769,Shannon Brown,8:41,0.0,0.0,...,0.250,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0
318290,2009-10-27,20900004,1610612747,LAL,Los Angeles,2694,Josh Powell,7:56,1.0,3.0,...,0.000,1.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,2.0
318291,2009-10-27,20900004,1610612747,LAL,Los Angeles,2575,Luke Walton,3:22,0.0,1.0,...,0.000,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [92]:
Season_11 = Reg_season_df[(Reg_season_df['GAME_DATE'] >= '2010-10-26') & (Reg_season_df['GAME_DATE'] <= '2011-08-01')]

Season_11

,GAME_DATE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,MIN,2pointer_MADE,2pointer_ATTEMPTS,...,FreeThrow_PCT,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
263980,2011-04-13,21001227,1610612757,POR,Portland,201164,Rudy Fernandez,34:52,2.0,8.0,...,0.00,0.0,2.0,2.0,5.0,1.0,0.0,1.0,1.0,5.0
263981,2011-04-13,21001227,1610612757,POR,Portland,202419,Chris Johnson,40:19,1.0,8.0,...,0.75,8.0,5.0,13.0,1.0,1.0,1.0,2.0,4.0,8.0
263982,2011-04-13,21001227,1610612757,POR,Portland,2853,Earl Barron,36:39,2.0,10.0,...,0.50,4.0,9.0,13.0,3.0,0.0,0.0,3.0,4.0,5.0
263983,2011-04-13,21001227,1610612757,POR,Portland,202083,Wesley Matthews,24:00,5.0,9.0,...,1.00,0.0,1.0,1.0,1.0,0.0,0.0,4.0,0.0,18.0
263984,2011-04-13,21001227,1610612757,POR,Portland,1889,Andre Miller,7:05,2.0,3.0,...,0.00,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289128,2010-10-26,21000003,1610612747,LAL,Los Angeles,202382,Derrick Caracter,2:14,0.0,1.0,...,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
289129,2010-10-26,21000003,1610612747,LAL,Los Angeles,689,Theo Ratliff,16:53,0.0,2.0,...,0.00,1.0,1.0,2.0,1.0,0.0,2.0,0.0,1.0,0.0
289130,2010-10-26,21000003,1610612747,LAL,Los Angeles,2581,Steve Blake,21:32,3.0,5.0,...,0.50,0.0,0.0,0.0,3.0,1.0,0.0,0.0,2.0,10.0
289131,2010-10-26,21000003,1610612747,LAL,Los Angeles,200769,Shannon Brown,21:15,6.0,9.0,...,0.00,0.0,1.0,1.0,1.0,4.0,0.0,2.0,0.0,16.0
289132,2010-10-26,21000003,1610612747,LAL,Los Angeles,2440,Matt Barnes,15:47,1.0,4.0,...,1.00,4.0,1.0,5.0,2.0,0.0,0.0,1.0,3.0,6.0

In [93]:
Season_12 = Reg_season_df[(Reg_season_df['GAME_DATE'] >= '2011-12-25') & (Reg_season_df['GAME_DATE'] <= '2012-08-01')]

Season_12

,GAME_DATE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,MIN,2pointer_MADE,2pointer_ATTEMPTS,...,FreeThrow_PCT,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
240853,2012-04-26,21100986,1610612740,NOH,New Orleans,202498,Lance Thomas,45:45,2.0,6.0,...,0.875,2.0,6.0,8.0,0.0,1.0,2.0,2.0,3.0,11.0
240854,2012-04-26,21100986,1610612740,NOH,New Orleans,202329,Al-Farouq Aminu,43:32,4.0,13.0,...,0.333,0.0,10.0,10.0,3.0,0.0,0.0,0.0,3.0,11.0
240855,2012-04-26,21100986,1610612740,NOH,New Orleans,201160,Jason Smith,4:54,1.0,2.0,...,0.000,0.0,4.0,4.0,2.0,0.0,0.0,0.0,0.0,2.0
240856,2012-04-26,21100986,1610612740,NOH,New Orleans,201158,Marco Belinelli,16:09,4.0,8.0,...,0.000,0.0,4.0,4.0,2.0,1.0,1.0,0.0,0.0,9.0
240857,2012-04-26,21100986,1610612740,NOH,New Orleans,202406,Jerome Dyson,41:12,6.0,14.0,...,0.500,1.0,1.0,2.0,1.0,3.0,1.0,4.0,3.0,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261606,2011-12-25,21100001,1610612752,NYK,New York,2407,Jared Jeffries,12:30,1.0,3.0,...,0.000,1.0,0.0,1.0,0.0,0.0,1.0,0.0,2.0,2.0
261607,2011-12-25,21100001,1610612752,NYK,New York,202697,Iman Shumpert,22:02,3.0,13.0,...,1.000,1.0,3.0,4.0,1.0,0.0,0.0,2.0,2.0,11.0
261608,2011-12-25,21100001,1610612752,NYK,New York,201611,Henry Walker,14:43,0.0,1.0,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,3.0,4.0,0.0
261609,2011-12-25,21100001,1610612752,NYK,New York,202725,Josh Harrellson,9:03,0.0,0.0,...,0.000,0.0,2.0,2.0,1.0,0.0,1.0,1.0,0.0,0.0
261610,2011-12-25,21100001,1610612752,NYK,New York,200764,Renaldo Balkman,7:41,1.0,1.0,...,0.000,2.0,1.0,3.0,1.0,0.0,0.0,0.0,2.0,2.0

In [94]:
Season_13 = Reg_season_df[(Reg_season_df['GAME_DATE'] >= '2012-10-30') & (Reg_season_df['GAME_DATE'] <= '2013-08-01')]

Season_13

,GAME_DATE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,MIN,2pointer_MADE,2pointer_ATTEMPTS,...,FreeThrow_PCT,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
511937,2013-04-17,21201223,1610612762,UTA,Utah,202330,Gordon Hayward,30:44,4.0,8.0,...,0.000,3.0,0.0,3.0,2.0,1.0,0.0,3.0,1.0,9.0
511938,2013-04-17,21201223,1610612762,UTA,Utah,200794,Paul Millsap,27:34,2.0,7.0,...,0.500,5.0,3.0,8.0,0.0,1.0,2.0,0.0,4.0,6.0
511939,2013-04-17,21201223,1610612762,UTA,Utah,2744,Al Jefferson,40:21,8.0,19.0,...,1.000,2.0,14.0,16.0,2.0,0.0,1.0,1.0,5.0,22.0
511940,2013-04-17,21201223,1610612762,UTA,Utah,200751,Randy Foye,35:14,1.0,9.0,...,0.667,1.0,2.0,3.0,2.0,0.0,1.0,0.0,2.0,7.0
511941,2013-04-17,21201223,1610612762,UTA,Utah,2590,Mo Williams,33:04,3.0,13.0,...,0.400,0.0,1.0,1.0,3.0,1.0,0.0,3.0,1.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
537689,2012-10-30,21200001,1610612739,CLE,Cleveland,101139,CJ Miles,17:42,1.0,5.0,...,0.000,0.0,4.0,4.0,1.0,0.0,0.0,3.0,0.0,2.0
537690,2012-10-30,21200001,1610612739,CLE,Cleveland,203092,Tyler Zeller,14:53,2.0,4.0,...,0.500,0.0,2.0,2.0,0.0,1.0,1.0,0.0,2.0,5.0
537691,2012-10-30,21200001,1610612739,CLE,Cleveland,200789,Daniel Gibson,16:11,3.0,5.0,...,0.500,1.0,2.0,3.0,1.0,0.0,1.0,0.0,2.0,10.0
537692,2012-10-30,21200001,1610612739,CLE,Cleveland,2575,Luke Walton,12:14,1.0,2.0,...,0.000,0.0,1.0,1.0,0.0,0.0,0.0,2.0,0.0,2.0
537693,2012-10-30,21200001,1610612739,CLE,Cleveland,202388,Donald Sloan,13:26,2.0,5.0,...,0.000,0.0,0.0,0.0,1.0,0.0,0.0,2.0,2.0,4.0

In [95]:
Season_14 = Reg_season_df[(Reg_season_df['GAME_DATE'] >= '2013-10-29') & (Reg_season_df['GAME_DATE'] <= '2014-08-01')]

Season_14

,GAME_DATE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,MIN,2pointer_MADE,2pointer_ATTEMPTS,...,FreeThrow_PCT,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
481833,2014-04-16,21301221,1610612747,LAL,Los Angeles,202325,Wesley Johnson,34:38,5.0,17.0,...,0.000,1.0,10.0,11.0,2.0,0.0,0.0,0.0,1.0,11.0
481834,2014-04-16,21301221,1610612747,LAL,Los Angeles,203527,Ryan Kelly,36:36,6.0,11.0,...,0.000,1.0,7.0,8.0,2.0,0.0,0.0,1.0,3.0,12.0
481835,2014-04-16,21301221,1610612747,LAL,Los Angeles,201941,Jordan Hill,27:51,7.0,13.0,...,0.667,3.0,11.0,14.0,2.0,1.0,2.0,0.0,1.0,18.0
481836,2014-04-16,21301221,1610612747,LAL,Los Angeles,201975,Jodie Meeks,30:25,5.0,6.0,...,1.000,0.0,3.0,3.0,3.0,2.0,0.0,1.0,1.0,14.0
481837,2014-04-16,21301221,1610612747,LAL,Los Angeles,203088,Kendall Marshall,27:32,5.0,7.0,...,0.500,0.0,2.0,2.0,11.0,0.0,0.0,4.0,2.0,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
507446,2013-10-29,21300003,1610612747,LAL,Los Angeles,201975,Jodie Meeks,25:35,4.0,8.0,...,1.000,0.0,3.0,3.0,2.0,1.0,0.0,2.0,2.0,13.0
507447,2013-10-29,21300003,1610612747,LAL,Los Angeles,200770,Jordan Farmar,27:16,6.0,10.0,...,0.500,2.0,2.0,4.0,6.0,1.0,0.0,3.0,5.0,16.0
507448,2013-10-29,21300003,1610612747,LAL,Los Angeles,202333,Xavier Henry,26:24,8.0,13.0,...,0.375,2.0,4.0,6.0,2.0,1.0,0.0,1.0,1.0,22.0
507449,2013-10-29,21300003,1610612747,LAL,Los Angeles,202325,Wesley Johnson,20:32,1.0,11.0,...,0.000,0.0,3.0,3.0,1.0,0.0,1.0,0.0,4.0,3.0
507450,2013-10-29,21300003,1610612747,LAL,Los Angeles,201941,Jordan Hill,18:02,6.0,8.0,...,0.000,7.0,1.0,8.0,2.0,1.0,1.0,1.0,2.0,12.0

In [96]:
Season_15 = Reg_season_df[(Reg_season_df['GAME_DATE'] >= '2014-10-28') & (Reg_season_df['GAME_DATE'] <= '2015-08-01')]

Season_15

,GAME_DATE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,MIN,2pointer_MADE,2pointer_ATTEMPTS,...,FreeThrow_PCT,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
451272,2015-04-15,21401224,1610612753,ORL,Orlando,203932,Aaron Gordon,34:13,3.0,11.0,...,0.000,3.0,4.0,7.0,0.0,0.0,0.0,0.0,2.0,7.0
451273,2015-04-15,21401224,1610612753,ORL,Orlando,203094,Andrew Nicholson,28:24,8.0,10.0,...,0.000,3.0,6.0,9.0,1.0,0.0,1.0,1.0,5.0,18.0
451274,2015-04-15,21401224,1610612753,ORL,Orlando,202696,Nikola Vucevic,39:42,12.0,21.0,...,0.500,1.0,10.0,11.0,5.0,1.0,1.0,2.0,4.0,26.0
451275,2015-04-15,21401224,1610612753,ORL,Orlando,203506,Victor Oladipo,44:12,7.0,17.0,...,0.400,0.0,2.0,2.0,3.0,0.0,1.0,4.0,0.0,19.0
451276,2015-04-15,21401224,1610612753,ORL,Orlando,203901,Elfrid Payton,34:30,1.0,5.0,...,0.000,0.0,3.0,3.0,6.0,4.0,1.0,4.0,1.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
477248,2014-10-28,21400003,1610612747,LAL,Los Angeles,203903,Jordan Clarkson,20:22,1.0,4.0,...,0.833,0.0,4.0,4.0,2.0,0.0,0.0,1.0,3.0,8.0
477249,2014-10-28,21400003,1610612747,LAL,Los Angeles,202334,Ed Davis,21:35,5.0,7.0,...,0.500,2.0,4.0,6.0,0.0,1.0,2.0,0.0,6.0,11.0
477250,2014-10-28,21400003,1610612747,LAL,Los Angeles,202333,Xavier Henry,18:28,0.0,4.0,...,0.750,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,3.0
477251,2014-10-28,21400003,1610612747,LAL,Los Angeles,203944,Julius Randle,13:34,1.0,3.0,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0
477252,2014-10-28,21400003,1610612747,LAL,Los Angeles,203135,Robert Sacre,7:07,1.0,5.0,...,0.000,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,2.0

In [97]:
Season_16 = Reg_season_df[(Reg_season_df['GAME_DATE'] >= '2015-10-27') & (Reg_season_df['GAME_DATE'] <= '2016-08-01')]

Season_16

,GAME_DATE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,MIN,2pointer_MADE,2pointer_ATTEMPTS,...,FreeThrow_PCT,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
420940,2016-04-13,21501224,1610612758,SAC,Sacramento,202341,James Anderson,37:12,5.0,12.0,...,0.333,1.0,3.0,4.0,5.0,3.0,0.0,6.0,3.0,13.0
420941,2016-04-13,21501224,1610612758,SAC,Sacramento,201585,Kosta Koufos,33:25,6.0,13.0,...,0.000,4.0,7.0,11.0,1.0,1.0,2.0,0.0,3.0,12.0
420942,2016-04-13,21501224,1610612758,SAC,Sacramento,1626161,Willie Cauley-Stein,31:20,3.0,10.0,...,0.000,3.0,5.0,8.0,3.0,2.0,1.0,2.0,5.0,6.0
420943,2016-04-13,21501224,1610612758,SAC,Sacramento,203463,Ben McLemore,39:52,10.0,20.0,...,0.000,2.0,3.0,5.0,3.0,2.0,0.0,3.0,2.0,24.0
420944,2016-04-13,21501224,1610612758,SAC,Sacramento,203552,Seth Curry,40:13,3.0,18.0,...,1.000,1.0,5.0,6.0,5.0,0.0,0.0,5.0,1.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447013,2015-10-27,21500003,1610612744,GSW,Golden State,203105,Festus Ezeli,17:01,6.0,10.0,...,0.500,3.0,1.0,4.0,1.0,1.0,1.0,1.0,2.0,13.0
447014,2015-10-27,21500003,1610612744,GSW,Golden State,203949,James Michael McAdoo,2:31,0.0,0.0,...,1.000,0.0,0.0,0.0,0.0,1.0,0.0,2.0,4.0,2.0
447015,2015-10-27,21500003,1610612744,GSW,Golden State,201578,Marreese Speights,10:42,2.0,7.0,...,1.000,4.0,1.0,5.0,1.0,0.0,1.0,2.0,1.0,9.0
447016,2015-10-27,21500003,1610612744,GSW,Golden State,2733,Shaun Livingston,21:20,3.0,6.0,...,0.000,0.0,3.0,3.0,2.0,0.0,1.0,0.0,1.0,6.0
447017,2015-10-27,21500003,1610612744,GSW,Golden State,201575,Brandon Rush,1:40,0.0,0.0,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [98]:
Season_17 = Reg_season_df[(Reg_season_df['GAME_DATE'] >= '2016-10-25') & (Reg_season_df['GAME_DATE'] <= '2017-08-01')]

Season_17

,GAME_DATE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,MIN,2pointer_MADE,2pointer_ATTEMPTS,...,FreeThrow_PCT,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
390361,2017-04-12,21601224,1610612750,MIN,Minnesota,203952,Andrew Wiggins,30:19,7.0,17.0,...,0.714,0.0,2.0,2.0,3.0,1.0,0.0,4.0,2.0,21.0
390362,2017-04-12,21601224,1610612750,MIN,Minnesota,203476,Gorgui Dieng,27:21,3.0,8.0,...,0.000,3.0,5.0,8.0,2.0,0.0,0.0,3.0,2.0,6.0
390363,2017-04-12,21601224,1610612750,MIN,Minnesota,1626157,Karl-Anthony Towns,36:09,12.0,17.0,...,1.000,1.0,20.0,21.0,3.0,1.0,0.0,0.0,2.0,28.0
390364,2017-04-12,21601224,1610612750,MIN,Minnesota,201575,Brandon Rush,24:19,3.0,3.0,...,0.000,1.0,1.0,2.0,2.0,0.0,0.0,2.0,0.0,8.0
390365,2017-04-12,21601224,1610612750,MIN,Minnesota,1627739,Kris Dunn,32:16,5.0,13.0,...,0.000,0.0,2.0,2.0,16.0,1.0,2.0,3.0,4.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
416495,2016-10-25,21600003,1610612744,GSW,Golden State,2733,Shaun Livingston,12:54,1.0,3.0,...,0.000,0.0,2.0,2.0,0.0,1.0,0.0,1.0,0.0,2.0
416496,2016-10-25,21600003,1610612744,GSW,Golden State,1627775,Patrick McCaw,9:00,1.0,3.0,...,0.000,0.0,0.0,0.0,2.0,1.0,1.0,0.0,0.0,2.0
416497,2016-10-25,21600003,1610612744,GSW,Golden State,2760,Anderson Varejao,3:10,0.0,0.0,...,0.500,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,1.0
416498,2016-10-25,21600003,1610612744,GSW,Golden State,201580,JaVale McGee,3:41,1.0,2.0,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
416499,2016-10-25,21600003,1610612744,GSW,Golden State,1626172,Kevon Looney,3:41,0.0,0.0,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [99]:
Season_18 = Reg_season_df[(Reg_season_df['GAME_DATE'] >= '2017-10-17') & (Reg_season_df['GAME_DATE'] <= '2018-08-01')]

Season_18

,GAME_DATE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,MIN,2pointer_MADE,2pointer_ATTEMPTS,...,FreeThrow_PCT,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
360413,2018-04-15,41700131,1610612754,IND,Indiana,202711,Bojan Bogdanovic,38:46,5.0,17.0,...,1.00,0.0,6.0,6.0,1.0,3.0,0.0,1.0,3.0,15.0
360414,2018-04-15,41700131,1610612754,IND,Indiana,201152,Thaddeus Young,31:19,3.0,4.0,...,0.50,2.0,1.0,3.0,1.0,0.0,1.0,0.0,0.0,7.0
360415,2018-04-15,41700131,1610612754,IND,Indiana,1626167,Myles Turner,33:32,6.0,9.0,...,0.75,1.0,7.0,8.0,2.0,0.0,1.0,1.0,3.0,16.0
360416,2018-04-15,41700131,1610612754,IND,Indiana,203506,Victor Oladipo,36:52,11.0,19.0,...,0.50,0.0,6.0,6.0,4.0,4.0,1.0,4.0,3.0,32.0
360417,2018-04-15,41700131,1610612754,IND,Indiana,201954,Darren Collison,30:44,2.0,9.0,...,0.50,1.0,4.0,5.0,6.0,2.0,0.0,2.0,0.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
386686,2017-10-17,21700002,1610612744,GSW,Golden State,201156,Nick Young,26:10,8.0,9.0,...,1.00,1.0,1.0,2.0,0.0,0.0,0.0,1.0,4.0,23.0
386687,2017-10-17,21700002,1610612744,GSW,Golden State,2733,Shaun Livingston,18:33,2.0,5.0,...,1.00,1.0,0.0,1.0,5.0,0.0,0.0,1.0,2.0,6.0
386688,2017-10-17,21700002,1610612744,GSW,Golden State,201956,Omri Casspi,4:28,0.0,0.0,...,1.00,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0
386689,2017-10-17,21700002,1610612744,GSW,Golden State,1626172,Kevon Looney,7:46,0.0,0.0,...,0.50,0.0,2.0,2.0,0.0,1.0,0.0,0.0,2.0,1.0
386690,2017-10-17,21700002,1610612744,GSW,Golden State,2561,David West,9:25,2.0,3.0,...,0.00,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,4.0

In [100]:
Season_19 = Reg_season_df[(Reg_season_df['GAME_DATE'] >= '2018-10-16') & (Reg_season_df['GAME_DATE'] <= '2019-08-01')]

Season_19

,GAME_DATE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,MIN,2pointer_MADE,2pointer_ATTEMPTS,...,FreeThrow_PCT,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
330918,2019-04-10,21801220,1610612754,IND,Indiana,203926,Doug McDermott,31:39,4.0,12.0,...,1.0,1.0,4.0,5.0,2.0,1.0,0.0,0.0,2.0,13.0
330919,2019-04-10,21801220,1610612754,IND,Indiana,1628388,TJ Leaf,34:12,12.0,19.0,...,0.8,5.0,5.0,10.0,2.0,2.0,2.0,0.0,2.0,28.0
330920,2019-04-10,21801220,1610612754,IND,Indiana,203124,Kyle O'Quinn,10:29,2.0,5.0,...,1.0,0.0,2.0,2.0,2.0,0.0,2.0,1.0,2.0,6.0
330921,2019-04-10,21801220,1610612754,IND,Indiana,201936,Tyreke Evans,26:11,9.0,14.0,...,0.8,0.0,2.0,2.0,5.0,0.0,0.0,3.0,4.0,27.0
330922,2019-04-10,21801220,1610612754,IND,Indiana,201954,Darren Collison,16:09,1.0,3.0,...,1.0,0.0,1.0,1.0,4.0,1.0,0.0,1.0,3.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357014,2018-10-16,21800002,1610612744,GSW,Golden State,1626188,Quinn Cook,13:12,1.0,2.0,...,0.0,1.0,1.0,2.0,1.0,0.0,0.0,2.0,2.0,3.0
357015,2018-10-16,21800002,1610612744,GSW,Golden State,2733,Shaun Livingston,14:34,3.0,5.0,...,0.0,2.0,1.0,3.0,1.0,1.0,0.0,1.0,2.0,6.0
357016,2018-10-16,21800002,1610612744,GSW,Golden State,1628395,Jordan Bell,6:39,0.0,0.0,...,0.0,1.0,1.0,2.0,0.0,0.0,1.0,0.0,1.0,0.0
357017,2018-10-16,21800002,1610612744,GSW,Golden State,1628035,Alfonzo McKinnie,2:21,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
357018,2018-10-16,21800002,1610612744,GSW,Golden State,201973,Jonas Jerebko,6:10,0.0,0.0,...,0.0,0.0,3.0,3.0,0.0,0.0,0.0,1.0,2.0,0.0

In [101]:
Season_20 = Reg_season_df[(Reg_season_df['GAME_DATE'] >= '2019-10-22') & (Reg_season_df['GAME_DATE'] <= '2020-10-31')]

Season_20

,GAME_DATE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,MIN,2pointer_MADE,2pointer_ATTEMPTS,...,FreeThrow_PCT,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
51642,2020-08-15,51900111,1610612763,MEM,Memphis,203937,Kyle Anderson,27:10,4.0,6.0,...,1.000,1.0,5.0,6.0,9.0,2.0,1.0,6.0,3.0,10.0
51643,2020-08-15,51900111,1610612763,MEM,Memphis,201229,Anthony Tolliver,23:26,2.0,4.0,...,1.000,1.0,2.0,3.0,0.0,0.0,1.0,0.0,6.0,7.0
51644,2020-08-15,51900111,1610612763,MEM,Memphis,202685,Jonas Valanciunas,34:02,8.0,16.0,...,1.000,4.0,13.0,17.0,6.0,0.0,0.0,1.0,3.0,22.0
51645,2020-08-15,51900111,1610612763,MEM,Memphis,1628415,Dillon Brooks,37:41,7.0,18.0,...,0.667,1.0,1.0,2.0,2.0,1.0,0.0,0.0,3.0,20.0
51646,2020-08-15,51900111,1610612763,MEM,Memphis,1629630,Ja Morant,41:52,13.0,28.0,...,0.750,1.0,3.0,4.0,8.0,0.0,0.0,8.0,1.0,35.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
327314,2019-10-22,21900001,1610612761,TOR,Toronto,200768,Kyle Lowry,44:60,4.0,15.0,...,0.846,1.0,4.0,5.0,6.0,2.0,0.0,4.0,4.0,22.0
327315,2019-10-22,21900001,1610612761,TOR,Toronto,1627832,Fred VanVleet,44:20,12.0,18.0,...,0.833,0.0,5.0,5.0,7.0,2.0,0.0,2.0,0.0,34.0
327316,2019-10-22,21900001,1610612761,TOR,Toronto,201586,Serge Ibaka,25:60,4.0,10.0,...,0.833,2.0,3.0,5.0,0.0,1.0,0.0,3.0,2.0,13.0
327317,2019-10-22,21900001,1610612761,TOR,Toronto,1626181,Norman Powell,28:39,2.0,7.0,...,0.000,1.0,7.0,8.0,2.0,0.0,0.0,2.0,2.0,5.0
327318,2019-10-22,21900001,1610612761,TOR,Toronto,1629056,Terence Davis,15:10,2.0,6.0,...,0.000,2.0,3.0,5.0,2.0,2.0,0.0,0.0,2.0,5.0

In [102]:
Season_21 = Reg_season_df[(Reg_season_df['GAME_DATE'] >= '2020-12-22') & (Reg_season_df['GAME_DATE'] <= '2021-08-01')]

Season_21

,GAME_DATE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,MIN,2pointer_MADE,2pointer_ATTEMPTS,...,FreeThrow_PCT,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
25155,2021-05-21,52000211,1610612763,MEM,Memphis,203937,Kyle Anderson,39:01,2.0,7.0,...,1.000,2.0,8.0,10.0,6.0,1.0,2.0,0.0,1.0,9.0
25156,2021-05-21,52000211,1610612763,MEM,Memphis,1628991,Jaren Jackson Jr.,14:56,1.0,6.0,...,0.875,2.0,0.0,2.0,0.0,0.0,2.0,1.0,4.0,10.0
25157,2021-05-21,52000211,1610612763,MEM,Memphis,202685,Jonas Valanciunas,25:33,3.0,6.0,...,0.500,6.0,6.0,12.0,3.0,0.0,0.0,3.0,6.0,9.0
25158,2021-05-21,52000211,1610612763,MEM,Memphis,1628415,Dillon Brooks,45:04,7.0,22.0,...,0.000,1.0,1.0,2.0,3.0,2.0,0.0,1.0,5.0,14.0
25159,2021-05-21,52000211,1610612763,MEM,Memphis,1629630,Ja Morant,45:45,14.0,29.0,...,1.000,2.0,4.0,6.0,6.0,4.0,0.0,5.0,2.0,35.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48608,2020-12-22,22000002,1610612746,LAC,LA,1628379,Luke Kennard,21:03,2.0,6.0,...,0.000,0.0,2.0,2.0,2.0,2.0,1.0,1.0,3.0,4.0
48609,2020-12-22,22000002,1610612747,LAL,Los Angeles,203484,Kentavious Caldwell-Pope,23:03,2.0,4.0,...,1.000,0.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,9.0
48610,2020-12-22,22000002,1610612747,LAL,Los Angeles,203471,Dennis Schroder,27:48,5.0,15.0,...,0.500,1.0,11.0,12.0,8.0,0.0,0.0,1.0,4.0,14.0
48611,2020-12-22,22000002,1610612747,LAL,Los Angeles,1628398,Kyle Kuzma,26:38,6.0,11.0,...,1.000,0.0,1.0,1.0,0.0,0.0,0.0,2.0,2.0,15.0
48612,2020-12-22,22000002,1610612747,LAL,Los Angeles,202693,Markieff Morris,19:00,1.0,3.0,...,0.667,1.0,3.0,4.0,1.0,0.0,0.0,0.0,0.0,5.0

In [103]:
reg_frames = [Season_04, Season_05, Season_06, Season_07, Season_08, Season_09, Season_10, Season_11, 
          Season_12, Season_13, Season_14, Season_15, Season_16, Season_17, Season_18, Season_19, 
          Season_20, Season_21]

In [104]:
Reg_season_stats_df = pd.concat(reg_frames)
Reg_season_stats_df

,GAME_DATE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,MIN,2pointer_MADE,2pointer_ATTEMPTS,...,FreeThrow_PCT,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
214863,2004-04-14,20301183,1610612750,MIN,Minnesota,84,Latrell Sprewell,29:14,8.0,13.0,...,1.000,0.0,2.0,2.0,2.0,2.0,0.0,2.0,0.0,20.0
214864,2004-04-14,20301183,1610612750,MIN,Minnesota,708,Kevin Garnett,31:05,9.0,13.0,...,1.000,2.0,7.0,9.0,2.0,1.0,2.0,0.0,1.0,26.0
214865,2004-04-14,20301183,1610612750,MIN,Minnesota,911,Ervin Johnson,7:02,0.0,1.0,...,0.000,0.0,2.0,2.0,0.0,0.0,0.0,0.0,4.0,0.0
214866,2004-04-14,20301183,1610612750,MIN,Minnesota,208,Sam Cassell,24:06,7.0,9.0,...,1.000,0.0,2.0,2.0,8.0,1.0,0.0,1.0,2.0,17.0
214867,2004-04-14,20301183,1610612750,MIN,Minnesota,2239,Trenton Hassell,17:52,2.0,3.0,...,0.500,1.0,2.0,3.0,3.0,1.0,1.0,1.0,1.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48608,2020-12-22,22000002,1610612746,LAC,LA,1628379,Luke Kennard,21:03,2.0,6.0,...,0.000,0.0,2.0,2.0,2.0,2.0,1.0,1.0,3.0,4.0
48609,2020-12-22,22000002,1610612747,LAL,Los Angeles,203484,Kentavious Caldwell-Pope,23:03,2.0,4.0,...,1.000,0.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,9.0
48610,2020-12-22,22000002,1610612747,LAL,Los Angeles,203471,Dennis Schroder,27:48,5.0,15.0,...,0.500,1.0,11.0,12.0,8.0,0.0,0.0,1.0,4.0,14.0
48611,2020-12-22,22000002,1610612747,LAL,Los Angeles,1628398,Kyle Kuzma,26:38,6.0,11.0,...,1.000,0.0,1.0,1.0,0.0,0.0,0.0,2.0,2.0,15.0
48612,2020-12-22,22000002,1610612747,LAL,Los Angeles,202693,Markieff Morris,19:00,1.0,3.0,...,0.667,1.0,3.0,4.0,1.0,0.0,0.0,0.0,0.0,5.0

# True Regular Season Stats

In [105]:
New_season_stats_df = Reg_season_stats_df[['TEAM_ID', 'PLAYER_ID', 'PLAYER_NAME', '2pointer_MADE', '2pointer_ATTEMPTS',
                        '3pointer_MADE', '3pointer_ATTEMPTS', 'FreeThrow_MADE', 'FreeThrow_ATTEMPTS', 'OFFENSIVE_REBOUNDS', 
                         'DEFENSIVE_REBOUNDS', 'REBOUNDS_TOTAL', 'ASSISTS','STEALS', 'BLOCKS', 'TURNOVERS', 'PERSONAL_FOULS', 'POINTS']]
New_season_stats_df

,TEAM_ID,PLAYER_ID,PLAYER_NAME,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
214863,1610612750,84,Latrell Sprewell,8.0,13.0,2.0,5.0,2.0,2.0,0.0,2.0,2.0,2.0,2.0,0.0,2.0,0.0,20.0
214864,1610612750,708,Kevin Garnett,9.0,13.0,0.0,0.0,8.0,8.0,2.0,7.0,9.0,2.0,1.0,2.0,0.0,1.0,26.0
214865,1610612750,911,Ervin Johnson,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,4.0,0.0
214866,1610612750,208,Sam Cassell,7.0,9.0,1.0,1.0,2.0,2.0,0.0,2.0,2.0,8.0,1.0,0.0,1.0,2.0,17.0
214867,1610612750,2239,Trenton Hassell,2.0,3.0,0.0,0.0,1.0,2.0,1.0,2.0,3.0,3.0,1.0,1.0,1.0,1.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48608,1610612746,1628379,Luke Kennard,2.0,6.0,0.0,3.0,0.0,0.0,0.0,2.0,2.0,2.0,2.0,1.0,1.0,3.0,4.0
48609,1610612747,203484,Kentavious Caldwell-Pope,2.0,4.0,1.0,3.0,4.0,4.0,0.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,9.0
48610,1610612747,203471,Dennis Schroder,5.0,15.0,2.0,5.0,2.0,4.0,1.0,11.0,12.0,8.0,0.0,0.0,1.0,4.0,14.0
48611,1610612747,1628398,Kyle Kuzma,6.0,11.0,1.0,3.0,2.0,2.0,0.0,1.0,1.0,0.0,0.0,0.0,2.0,2.0,15.0
48612,1610612747,202693,Markieff Morris,1.0,3.0,1.0,2.0,2.0,3.0,1.0,3.0,4.0,1.0,0.0,0.0,0.0,0.0,5.0

In [106]:
All_seasons_players = New_season_stats_df.groupby(['PLAYER_NAME']).agg({'TEAM_ID': 'last', 'PLAYER_ID': 'last',
                                                            '2pointer_MADE': 'sum', '2pointer_ATTEMPTS': 'sum',
                                                            '3pointer_MADE': 'sum', '3pointer_ATTEMPTS': 'sum', 'FreeThrow_MADE': 'sum', 
                                                            'FreeThrow_ATTEMPTS': 'sum', 'OFFENSIVE_REBOUNDS': 'sum', 
                                                            'DEFENSIVE_REBOUNDS': 'sum', 'REBOUNDS_TOTAL': 'sum', 'ASSISTS': 'sum',
                                                            'STEALS': 'sum', 'BLOCKS': 'sum', 'TURNOVERS': 'sum', 'PERSONAL_FOULS': 'sum', 
                                                            'POINTS': 'sum'}).reset_index()
All_seasons_players

,PLAYER_NAME,TEAM_ID,PLAYER_ID,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,AJ Hammons,1610612742,1627773,17.0,42.0,5.0,10.0,9.0,20.0,8.0,28.0,36.0,4.0,1.0,13.0,10.0,21.0,48.0
1,AJ Price,1610612754,201985,549.0,1444.0,218.0,690.0,207.0,279.0,68.0,309.0,377.0,567.0,125.0,9.0,229.0,237.0,1523.0
2,Aaron Brooks,1610612750,201166,2261.0,5478.0,820.0,2218.0,917.0,1095.0,254.0,825.0,1079.0,1925.0,359.0,87.0,1000.0,1217.0,6259.0
3,Aaron Gordon,1610612753,203932,2181.0,4851.0,503.0,1567.0,923.0,1328.0,716.0,2162.0,2878.0,1129.0,346.0,292.0,660.0,909.0,5788.0
4,Aaron Gray,1610612761,201189,440.0,864.0,0.0,3.0,186.0,331.0,431.0,759.0,1190.0,207.0,94.0,87.0,265.0,678.0,1066.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1856,Zion Williamson,1610612740,1629627,853.0,1410.0,16.0,48.0,485.0,713.0,232.0,361.0,593.0,276.0,74.0,48.0,227.0,178.0,2207.0
1857,Zoran Dragic,1610612756,204054,11.0,30.0,3.0,14.0,3.0,5.0,5.0,3.0,8.0,5.0,2.0,0.0,5.0,6.0,28.0
1858,Zoran Planinic,1610612751,2565,196.0,485.0,37.0,128.0,130.0,192.0,47.0,151.0,198.0,164.0,58.0,7.0,119.0,237.0,559.0
1859,Zydrunas Ilgauskas,1610612748,980,2874.0,5986.0,30.0,84.0,1622.0,2045.0,1707.0,2612.0,4319.0,665.0,277.0,912.0,990.0,1925.0,7400.0
1860,Zylan Cheatham,1610612740,1629597,11.0,16.0,0.0,2.0,5.0,8.0,5.0,14.0,19.0,3.0,1.0,1.0,6.0,13.0,27.0

In [107]:
All_seasons_players = All_seasons_players.rename(columns = {'2pointer_MADE': '_2pointer_MADE', '2pointer_ATTEMPTS': '_2pointer_ATTEMPTS',
                                                       '3pointer_MADE': '_3pointer_MADE', '3pointer_ATTEMPTS': '_3pointer_ATTEMPTS'})
All_seasons_players

,PLAYER_NAME,TEAM_ID,PLAYER_ID,_2pointer_MADE,_2pointer_ATTEMPTS,_3pointer_MADE,_3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,AJ Hammons,1610612742,1627773,17.0,42.0,5.0,10.0,9.0,20.0,8.0,28.0,36.0,4.0,1.0,13.0,10.0,21.0,48.0
1,AJ Price,1610612754,201985,549.0,1444.0,218.0,690.0,207.0,279.0,68.0,309.0,377.0,567.0,125.0,9.0,229.0,237.0,1523.0
2,Aaron Brooks,1610612750,201166,2261.0,5478.0,820.0,2218.0,917.0,1095.0,254.0,825.0,1079.0,1925.0,359.0,87.0,1000.0,1217.0,6259.0
3,Aaron Gordon,1610612753,203932,2181.0,4851.0,503.0,1567.0,923.0,1328.0,716.0,2162.0,2878.0,1129.0,346.0,292.0,660.0,909.0,5788.0
4,Aaron Gray,1610612761,201189,440.0,864.0,0.0,3.0,186.0,331.0,431.0,759.0,1190.0,207.0,94.0,87.0,265.0,678.0,1066.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1856,Zion Williamson,1610612740,1629627,853.0,1410.0,16.0,48.0,485.0,713.0,232.0,361.0,593.0,276.0,74.0,48.0,227.0,178.0,2207.0
1857,Zoran Dragic,1610612756,204054,11.0,30.0,3.0,14.0,3.0,5.0,5.0,3.0,8.0,5.0,2.0,0.0,5.0,6.0,28.0
1858,Zoran Planinic,1610612751,2565,196.0,485.0,37.0,128.0,130.0,192.0,47.0,151.0,198.0,164.0,58.0,7.0,119.0,237.0,559.0
1859,Zydrunas Ilgauskas,1610612748,980,2874.0,5986.0,30.0,84.0,1622.0,2045.0,1707.0,2612.0,4319.0,665.0,277.0,912.0,990.0,1925.0,7400.0
1860,Zylan Cheatham,1610612740,1629597,11.0,16.0,0.0,2.0,5.0,8.0,5.0,14.0,19.0,3.0,1.0,1.0,6.0,13.0,27.0

In [108]:
All_seasons_player_df = All_seasons_players.copy().rename(columns = {'2pointer_MADE': '_2pointer_MADE', '2pointer_ATTEMPTS': '_2pointer_ATTEMPTS',
                                                            '3pointer_MADE': '_3pointer_MADE', '3pointer_ATTEMPTS': '_3pointer_ATTEMPTS'})

All_seasons_player_df

,PLAYER_NAME,TEAM_ID,PLAYER_ID,_2pointer_MADE,_2pointer_ATTEMPTS,_3pointer_MADE,_3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,AJ Hammons,1610612742,1627773,17.0,42.0,5.0,10.0,9.0,20.0,8.0,28.0,36.0,4.0,1.0,13.0,10.0,21.0,48.0
1,AJ Price,1610612754,201985,549.0,1444.0,218.0,690.0,207.0,279.0,68.0,309.0,377.0,567.0,125.0,9.0,229.0,237.0,1523.0
2,Aaron Brooks,1610612750,201166,2261.0,5478.0,820.0,2218.0,917.0,1095.0,254.0,825.0,1079.0,1925.0,359.0,87.0,1000.0,1217.0,6259.0
3,Aaron Gordon,1610612753,203932,2181.0,4851.0,503.0,1567.0,923.0,1328.0,716.0,2162.0,2878.0,1129.0,346.0,292.0,660.0,909.0,5788.0
4,Aaron Gray,1610612761,201189,440.0,864.0,0.0,3.0,186.0,331.0,431.0,759.0,1190.0,207.0,94.0,87.0,265.0,678.0,1066.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1856,Zion Williamson,1610612740,1629627,853.0,1410.0,16.0,48.0,485.0,713.0,232.0,361.0,593.0,276.0,74.0,48.0,227.0,178.0,2207.0
1857,Zoran Dragic,1610612756,204054,11.0,30.0,3.0,14.0,3.0,5.0,5.0,3.0,8.0,5.0,2.0,0.0,5.0,6.0,28.0
1858,Zoran Planinic,1610612751,2565,196.0,485.0,37.0,128.0,130.0,192.0,47.0,151.0,198.0,164.0,58.0,7.0,119.0,237.0,559.0
1859,Zydrunas Ilgauskas,1610612748,980,2874.0,5986.0,30.0,84.0,1622.0,2045.0,1707.0,2612.0,4319.0,665.0,277.0,912.0,990.0,1925.0,7400.0
1860,Zylan Cheatham,1610612740,1629597,11.0,16.0,0.0,2.0,5.0,8.0,5.0,14.0,19.0,3.0,1.0,1.0,6.0,13.0,27.0

In [109]:
All_seasons_player_df['_2pointer_PCT'] = All_seasons_player_df['_2pointer_MADE']/All_seasons_player_df['_2pointer_ATTEMPTS']

In [110]:
All_seasons_player_df['_3pointer_PCT'] = All_seasons_player_df['_3pointer_MADE']/All_seasons_player_df['_3pointer_ATTEMPTS']

In [111]:
All_seasons_player_df['FreeThrow_PCT'] = All_seasons_player_df['FreeThrow_MADE']/All_seasons_player_df['FreeThrow_ATTEMPTS']

In [112]:
All_seasons_player_df = All_seasons_player_df[['PLAYER_NAME', 'TEAM_ID', 'PLAYER_ID', '_2pointer_MADE',
       '_2pointer_ATTEMPTS', '_2pointer_PCT', '_3pointer_MADE', '_3pointer_ATTEMPTS', '_3pointer_PCT',
       'FreeThrow_MADE', 'FreeThrow_ATTEMPTS', 'FreeThrow_PCT', 'OFFENSIVE_REBOUNDS',
       'DEFENSIVE_REBOUNDS', 'REBOUNDS_TOTAL', 'ASSISTS', 'STEALS', 'BLOCKS',
       'TURNOVERS', 'PERSONAL_FOULS', 'POINTS']]

All_seasons_player_df

,PLAYER_NAME,TEAM_ID,PLAYER_ID,_2pointer_MADE,_2pointer_ATTEMPTS,_2pointer_PCT,_3pointer_MADE,_3pointer_ATTEMPTS,_3pointer_PCT,FreeThrow_MADE,...,FreeThrow_PCT,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,AJ Hammons,1610612742,1627773,17.0,42.0,0.404762,5.0,10.0,0.500000,9.0,...,0.450000,8.0,28.0,36.0,4.0,1.0,13.0,10.0,21.0,48.0
1,AJ Price,1610612754,201985,549.0,1444.0,0.380194,218.0,690.0,0.315942,207.0,...,0.741935,68.0,309.0,377.0,567.0,125.0,9.0,229.0,237.0,1523.0
2,Aaron Brooks,1610612750,201166,2261.0,5478.0,0.412742,820.0,2218.0,0.369702,917.0,...,0.837443,254.0,825.0,1079.0,1925.0,359.0,87.0,1000.0,1217.0,6259.0
3,Aaron Gordon,1610612753,203932,2181.0,4851.0,0.449598,503.0,1567.0,0.320996,923.0,...,0.695030,716.0,2162.0,2878.0,1129.0,346.0,292.0,660.0,909.0,5788.0
4,Aaron Gray,1610612761,201189,440.0,864.0,0.509259,0.0,3.0,0.000000,186.0,...,0.561934,431.0,759.0,1190.0,207.0,94.0,87.0,265.0,678.0,1066.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1856,Zion Williamson,1610612740,1629627,853.0,1410.0,0.604965,16.0,48.0,0.333333,485.0,...,0.680224,232.0,361.0,593.0,276.0,74.0,48.0,227.0,178.0,2207.0
1857,Zoran Dragic,1610612756,204054,11.0,30.0,0.366667,3.0,14.0,0.214286,3.0,...,0.600000,5.0,3.0,8.0,5.0,2.0,0.0,5.0,6.0,28.0
1858,Zoran Planinic,1610612751,2565,196.0,485.0,0.404124,37.0,128.0,0.289062,130.0,...,0.677083,47.0,151.0,198.0,164.0,58.0,7.0,119.0,237.0,559.0
1859,Zydrunas Ilgauskas,1610612748,980,2874.0,5986.0,0.480120,30.0,84.0,0.357143,1622.0,...,0.793154,1707.0,2612.0,4319.0,665.0,277.0,912.0,990.0,1925.0,7400.0
1860,Zylan Cheatham,1610612740,1629597,11.0,16.0,0.687500,0.0,2.0,0.000000,5.0,...,0.625000,5.0,14.0,19.0,3.0,1.0,1.0,6.0,13.0,27.0

In [113]:
All_seasons_player_df = All_seasons_player_df.fillna(0)

In [114]:
All_seasons_player_df.isnull().sum()

PLAYER_NAME           0
TEAM_ID               0
PLAYER_ID             0
_2pointer_MADE        0
_2pointer_ATTEMPTS    0
_2pointer_PCT         0
_3pointer_MADE        0
_3pointer_ATTEMPTS    0
_3pointer_PCT         0
FreeThrow_MADE        0
FreeThrow_ATTEMPTS    0
FreeThrow_PCT         0
OFFENSIVE_REBOUNDS    0
DEFENSIVE_REBOUNDS    0
REBOUNDS_TOTAL        0
ASSISTS               0
STEALS                0
BLOCKS                0
TURNOVERS             0
PERSONAL_FOULS        0
POINTS                0
dtype: int64

In [115]:
All_seasons_player_df['_2pointer_PCT'] = All_seasons_player_df['_2pointer_PCT'].round(3)

In [116]:
All_seasons_player_df['_3pointer_PCT'] = All_seasons_player_df['_3pointer_PCT'].round(3)

In [117]:
All_seasons_player_df['FreeThrow_PCT'] = All_seasons_player_df['FreeThrow_PCT'].round(3)

In [118]:
All_seasons_player_df

,PLAYER_NAME,TEAM_ID,PLAYER_ID,_2pointer_MADE,_2pointer_ATTEMPTS,_2pointer_PCT,_3pointer_MADE,_3pointer_ATTEMPTS,_3pointer_PCT,FreeThrow_MADE,...,FreeThrow_PCT,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,AJ Hammons,1610612742,1627773,17.0,42.0,0.405,5.0,10.0,0.500,9.0,...,0.450,8.0,28.0,36.0,4.0,1.0,13.0,10.0,21.0,48.0
1,AJ Price,1610612754,201985,549.0,1444.0,0.380,218.0,690.0,0.316,207.0,...,0.742,68.0,309.0,377.0,567.0,125.0,9.0,229.0,237.0,1523.0
2,Aaron Brooks,1610612750,201166,2261.0,5478.0,0.413,820.0,2218.0,0.370,917.0,...,0.837,254.0,825.0,1079.0,1925.0,359.0,87.0,1000.0,1217.0,6259.0
3,Aaron Gordon,1610612753,203932,2181.0,4851.0,0.450,503.0,1567.0,0.321,923.0,...,0.695,716.0,2162.0,2878.0,1129.0,346.0,292.0,660.0,909.0,5788.0
4,Aaron Gray,1610612761,201189,440.0,864.0,0.509,0.0,3.0,0.000,186.0,...,0.562,431.0,759.0,1190.0,207.0,94.0,87.0,265.0,678.0,1066.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1856,Zion Williamson,1610612740,1629627,853.0,1410.0,0.605,16.0,48.0,0.333,485.0,...,0.680,232.0,361.0,593.0,276.0,74.0,48.0,227.0,178.0,2207.0
1857,Zoran Dragic,1610612756,204054,11.0,30.0,0.367,3.0,14.0,0.214,3.0,...,0.600,5.0,3.0,8.0,5.0,2.0,0.0,5.0,6.0,28.0
1858,Zoran Planinic,1610612751,2565,196.0,485.0,0.404,37.0,128.0,0.289,130.0,...,0.677,47.0,151.0,198.0,164.0,58.0,7.0,119.0,237.0,559.0
1859,Zydrunas Ilgauskas,1610612748,980,2874.0,5986.0,0.480,30.0,84.0,0.357,1622.0,...,0.793,1707.0,2612.0,4319.0,665.0,277.0,912.0,990.0,1925.0,7400.0
1860,Zylan Cheatham,1610612740,1629597,11.0,16.0,0.688,0.0,2.0,0.000,5.0,...,0.625,5.0,14.0,19.0,3.0,1.0,1.0,6.0,13.0,27.0

In [119]:
# All_seasons_player.to_csv('../Resources/Reg_season_by_player.csv')

In [120]:
db_string = f"postgresql://postgres:{db_password}@127.0.0.1:5432/Final_Project"

engine = create_engine(db_string)

All_seasons_player_df.to_sql(name='reg_season_by_player', con=engine)

In [121]:
# Reg_season_df.to_csv('../Resources/Reg_season_player_data.csv')

# Group season data by PLAYER_NAME

In [122]:
filtered_04 = Season_04[['TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_CITY', 'PLAYER_ID', 'PLAYER_NAME', '2pointer_MADE', '2pointer_ATTEMPTS',
                        '3pointer_MADE', '3pointer_ATTEMPTS', 'FreeThrow_MADE', 'FreeThrow_ATTEMPTS', 'OFFENSIVE_REBOUNDS', 
                         'DEFENSIVE_REBOUNDS', 'REBOUNDS_TOTAL', 'ASSISTS','STEALS', 'BLOCKS', 'TURNOVERS', 'PERSONAL_FOULS', 'POINTS']]
filtered_04

,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
214863,1610612750,MIN,Minnesota,84,Latrell Sprewell,8.0,13.0,2.0,5.0,2.0,2.0,0.0,2.0,2.0,2.0,2.0,0.0,2.0,0.0,20.0
214864,1610612750,MIN,Minnesota,708,Kevin Garnett,9.0,13.0,0.0,0.0,8.0,8.0,2.0,7.0,9.0,2.0,1.0,2.0,0.0,1.0,26.0
214865,1610612750,MIN,Minnesota,911,Ervin Johnson,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,4.0,0.0
214866,1610612750,MIN,Minnesota,208,Sam Cassell,7.0,9.0,1.0,1.0,2.0,2.0,0.0,2.0,2.0,8.0,1.0,0.0,1.0,2.0,17.0
214867,1610612750,MIN,Minnesota,2239,Trenton Hassell,2.0,3.0,0.0,0.0,1.0,2.0,1.0,2.0,3.0,3.0,1.0,1.0,1.0,1.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238735,1610612747,LAL,Los Angeles,935,Bryon Russell,3.0,7.0,1.0,5.0,3.0,3.0,0.0,0.0,0.0,0.0,2.0,0.0,1.0,4.0,10.0
238736,1610612747,LAL,Los Angeles,270,Horace Grant,1.0,2.0,0.0,0.0,1.0,2.0,0.0,5.0,5.0,2.0,0.0,1.0,0.0,2.0,3.0
238737,1610612747,LAL,Los Angeles,2575,Luke Walton,2.0,3.0,1.0,1.0,0.0,0.0,1.0,1.0,2.0,0.0,0.0,0.0,0.0,3.0,5.0
238738,1610612747,LAL,Los Angeles,2457,Jannero Pargo,2.0,3.0,1.0,1.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,2.0,0.0,5.0
238739,1610612747,LAL,Los Angeles,2416,Kareem Rush,1.0,5.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,4.0,2.0

In [123]:
# def str_to_number(time_str):
#     if not isinstance(time_str, str):
#         return 0
#     minutes, sec, *_ = [int(x) for x in time_str.split(':')]
#     return minutes + sec / 60

# filtered_21.MIN = filtered_21.MIN.map(str_to_number)

In [124]:
by_player_04 = filtered_04.groupby(['PLAYER_NAME']).agg({'TEAM_ID': 'last', 'TEAM_ABBREVIATION': 'last', 'TEAM_CITY': 'last', 'PLAYER_ID': 'last',
                                                            '2pointer_MADE': 'sum', '2pointer_ATTEMPTS': 'sum',
                                                            '3pointer_MADE': 'sum', '3pointer_ATTEMPTS': 'sum', 'FreeThrow_MADE': 'sum', 
                                                            'FreeThrow_ATTEMPTS': 'sum', 'OFFENSIVE_REBOUNDS': 'sum', 
                                                            'DEFENSIVE_REBOUNDS': 'sum', 'REBOUNDS_TOTAL': 'sum', 'ASSISTS': 'sum',
                                                            'STEALS': 'sum', 'BLOCKS': 'sum', 'TURNOVERS': 'sum', 'PERSONAL_FOULS': 'sum', 
                                                            'POINTS': 'sum'}).reset_index()
by_player_04

,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,Aaron McKie,1610612755,PHI,Philadelphia,243,265.0,577.0,75.0,172.0,84.0,111.0,45.0,208.0,253.0,195.0,85.0,23.0,103.0,142.0,689.0
1,Aaron Williams,1610612751,NJN,New Jersey,1425,172.0,342.0,1.0,3.0,105.0,155.0,101.0,193.0,294.0,81.0,34.0,46.0,89.0,187.0,450.0
2,Adonal Foyle,1610612744,GSW,Golden State,1502,59.0,130.0,0.0,0.0,19.0,35.0,54.0,113.0,167.0,17.0,6.0,46.0,21.0,68.0,137.0
3,Adrian Griffin,1610612745,HOU,Houston,1559,5.0,18.0,1.0,2.0,0.0,4.0,1.0,18.0,19.0,10.0,7.0,2.0,3.0,17.0,11.0
4,Al Harrington,1610612754,IND,Indiana,1733,421.0,909.0,21.0,77.0,185.0,252.0,163.0,345.0,508.0,131.0,80.0,22.0,163.0,250.0,1048.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
437,Zaza Pachulia,1610612753,ORL,Orlando,2585,68.0,175.0,0.0,0.0,58.0,90.0,69.0,105.0,174.0,13.0,21.0,12.0,34.0,87.0,194.0
438,Zeljko Rebraca,1610612765,DET,Detroit,1442,34.0,77.0,0.0,0.0,23.0,30.0,23.0,35.0,58.0,6.0,5.0,11.0,17.0,52.0,91.0
439,Zendon Hamilton,1610612755,PHI,Philadelphia,1985,51.0,95.0,0.0,0.0,67.0,96.0,49.0,97.0,146.0,13.0,8.0,8.0,27.0,74.0,169.0
440,Zoran Planinic,1610612751,NJN,New Jersey,2565,52.0,128.0,9.0,32.0,38.0,60.0,14.0,41.0,55.0,67.0,13.0,3.0,35.0,70.0,151.0
441,Zydrunas Ilgauskas,1610612739,CLE,Cleveland,980,466.0,965.0,2.0,7.0,303.0,406.0,279.0,374.0,653.0,109.0,39.0,201.0,163.0,277.0,1237.0

In [125]:
filtered_05 = Season_05[['TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_CITY', 'PLAYER_ID', 'PLAYER_NAME', '2pointer_MADE', '2pointer_ATTEMPTS',
                        '3pointer_MADE', '3pointer_ATTEMPTS', 'FreeThrow_MADE', 'FreeThrow_ATTEMPTS', 'OFFENSIVE_REBOUNDS', 
                         'DEFENSIVE_REBOUNDS', 'REBOUNDS_TOTAL', 'ASSISTS','STEALS', 'BLOCKS', 'TURNOVERS', 'PERSONAL_FOULS', 'POINTS']]
filtered_05

,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
187125,1610612756,PHX,Phoenix,2047,Quentin Richardson,6.0,18.0,5.0,14.0,0.0,0.0,0.0,5.0,5.0,1.0,1.0,0.0,1.0,3.0,17.0
187126,1610612756,PHX,Phoenix,1890,Shawn Marion,0.0,5.0,0.0,3.0,0.0,0.0,0.0,4.0,4.0,0.0,1.0,0.0,0.0,0.0,0.0
187127,1610612756,PHX,Phoenix,2405,Amar'e Stoudemire,10.0,17.0,2.0,2.0,8.0,11.0,5.0,6.0,11.0,2.0,0.0,3.0,2.0,2.0,30.0
187128,1610612756,PHX,Phoenix,2207,Joe Johnson,9.0,15.0,1.0,1.0,0.0,0.0,0.0,3.0,3.0,6.0,2.0,0.0,3.0,3.0,19.0
187129,1610612756,PHX,Phoenix,2571,Leandro Barbosa,7.0,13.0,1.0,4.0,1.0,1.0,1.0,3.0,4.0,4.0,2.0,0.0,4.0,3.0,16.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212024,1610612747,LAL,Los Angeles,2567,Brian Cook,5.0,10.0,0.0,2.0,0.0,0.0,0.0,2.0,2.0,3.0,0.0,2.0,0.0,1.0,10.0
212025,1610612747,LAL,Los Angeles,1908,Jumaine Jones,1.0,4.0,1.0,3.0,0.0,0.0,0.0,3.0,3.0,1.0,1.0,0.0,3.0,3.0,3.0
212026,1610612747,LAL,Los Angeles,2357,Tierre Brown,1.0,4.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,4.0,0.0,0.0,2.0,2.0,2.0
212027,1610612747,LAL,Los Angeles,258,Brian Grant,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,2.0,1.0,2.0
212028,1610612747,LAL,Los Angeles,2416,Kareem Rush,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,2.0,0.0

In [126]:
by_player_05 = filtered_05.groupby(['PLAYER_NAME']).agg({'TEAM_ID': 'last', 'TEAM_ABBREVIATION': 'last', 'TEAM_CITY': 'last', 'PLAYER_ID': 'last',
                                                            '2pointer_MADE': 'sum', '2pointer_ATTEMPTS': 'sum',
                                                            '3pointer_MADE': 'sum', '3pointer_ATTEMPTS': 'sum', 'FreeThrow_MADE': 'sum', 
                                                            'FreeThrow_ATTEMPTS': 'sum', 'OFFENSIVE_REBOUNDS': 'sum', 
                                                            'DEFENSIVE_REBOUNDS': 'sum', 'REBOUNDS_TOTAL': 'sum', 'ASSISTS': 'sum',
                                                            'STEALS': 'sum', 'BLOCKS': 'sum', 'TURNOVERS': 'sum', 'PERSONAL_FOULS': 'sum', 
                                                            'POINTS': 'sum'}).reset_index()
by_player_05

,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,Aaron McKie,1610612755,PHI,Philadelphia,243,61.0,142.0,20.0,62.0,10.0,16.0,20.0,152.0,172.0,103.0,48.0,17.0,31.0,116.0,152.0
1,Aaron Williams,1610612751,NJN,New Jersey,1425,29.0,63.0,0.0,0.0,15.0,17.0,17.0,43.0,60.0,8.0,5.0,8.0,17.0,70.0,73.0
2,Adonal Foyle,1610612744,GSW,Golden State,1502,156.0,311.0,0.0,0.0,40.0,72.0,165.0,264.0,429.0,56.0,26.0,159.0,58.0,201.0,352.0
3,Adrian Griffin,1610612741,CHI,Chicago,1559,58.0,161.0,2.0,9.0,33.0,44.0,52.0,94.0,146.0,53.0,43.0,4.0,30.0,78.0,151.0
4,Al Harrington,1610612737,ATL,Atlanta,1733,453.0,986.0,16.0,74.0,236.0,351.0,145.0,316.0,461.0,208.0,85.0,16.0,204.0,249.0,1158.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
459,Zaza Pachulia,1610612749,MIL,Milwaukee,2585,160.0,354.0,0.0,1.0,138.0,185.0,131.0,247.0,378.0,60.0,44.0,34.0,70.0,166.0,458.0
460,Zeljko Rebraca,1610612746,LAC,Los Angeles,1442,133.0,234.0,0.0,0.0,73.0,85.0,49.0,135.0,184.0,26.0,13.0,40.0,49.0,130.0,339.0
461,Zendon Hamilton,1610612749,MIL,Milwaukee,1985,11.0,32.0,0.0,0.0,29.0,48.0,18.0,24.0,42.0,6.0,5.0,2.0,12.0,26.0,51.0
462,Zoran Planinic,1610612751,NJN,New Jersey,2565,78.0,174.0,15.0,40.0,46.0,66.0,19.0,50.0,69.0,44.0,25.0,0.0,41.0,76.0,217.0
463,Zydrunas Ilgauskas,1610612739,CLE,Cleveland,980,458.0,979.0,2.0,7.0,402.0,503.0,299.0,373.0,672.0,100.0,53.0,165.0,191.0,313.0,1320.0

In [127]:
filtered_06 = Season_06[['TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_CITY', 'PLAYER_ID', 'PLAYER_NAME', '2pointer_MADE', '2pointer_ATTEMPTS',
                        '3pointer_MADE', '3pointer_ATTEMPTS', 'FreeThrow_MADE', 'FreeThrow_ATTEMPTS', 'OFFENSIVE_REBOUNDS', 
                         'DEFENSIVE_REBOUNDS', 'REBOUNDS_TOTAL', 'ASSISTS','STEALS', 'BLOCKS', 'TURNOVERS', 'PERSONAL_FOULS', 'POINTS']]
filtered_06

,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
157687,1610612759,SAS,San Antonio,1477,Bruce Bowen,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
157688,1610612759,SAS,San Antonio,109,Robert Horry,0.0,5.0,0.0,2.0,2.0,2.0,1.0,5.0,6.0,3.0,3.0,2.0,2.0,1.0,2.0
157689,1610612759,SAS,San Antonio,1737,Nazr Mohammed,2.0,8.0,0.0,0.0,3.0,4.0,5.0,1.0,6.0,1.0,1.0,1.0,1.0,4.0,7.0
157690,1610612759,SAS,San Antonio,2757,Beno Udrih,2.0,7.0,0.0,1.0,5.0,6.0,0.0,1.0,1.0,2.0,1.0,0.0,2.0,1.0,9.0
157691,1610612759,SAS,San Antonio,1938,Manu Ginobili,5.0,10.0,1.0,2.0,0.0,0.0,1.0,3.0,4.0,6.0,2.0,1.0,3.0,0.0,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182599,1610612756,PHX,Phoenix,2564,Boris Diaw,3.0,4.0,0.0,0.0,1.0,2.0,1.0,3.0,4.0,3.0,0.0,1.0,4.0,3.0,7.0
182600,1610612756,PHX,Phoenix,754,Jim Jackson,2.0,8.0,1.0,3.0,0.0,0.0,0.0,3.0,3.0,1.0,1.0,0.0,2.0,5.0,5.0
182601,1610612756,PHX,Phoenix,2571,Leandro Barbosa,4.0,11.0,0.0,2.0,0.0,0.0,3.0,5.0,8.0,3.0,0.0,1.0,3.0,2.0,8.0
182602,1610612756,PHX,Phoenix,258,Brian Grant,1.0,1.0,0.0,0.0,1.0,1.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,3.0
182603,1610612756,PHX,Phoenix,2067,Eddie House,2.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,2.0,0.0,0.0,0.0,4.0

In [128]:
by_player_06 = filtered_06.groupby(['PLAYER_NAME']).agg({'TEAM_ID': 'last', 'TEAM_ABBREVIATION': 'last', 'TEAM_CITY': 'last', 'PLAYER_ID': 'last',
                                                            '2pointer_MADE': 'sum', '2pointer_ATTEMPTS': 'sum',
                                                            '3pointer_MADE': 'sum', '3pointer_ATTEMPTS': 'sum', 'FreeThrow_MADE': 'sum', 
                                                            'FreeThrow_ATTEMPTS': 'sum', 'OFFENSIVE_REBOUNDS': 'sum', 
                                                            'DEFENSIVE_REBOUNDS': 'sum', 'REBOUNDS_TOTAL': 'sum', 'ASSISTS': 'sum',
                                                            'STEALS': 'sum', 'BLOCKS': 'sum', 'TURNOVERS': 'sum', 'PERSONAL_FOULS': 'sum', 
                                                            'POINTS': 'sum'}).reset_index()
by_player_06

,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,Aaron McKie,1610612747,LAL,Los Angeles,243,3.0,12.0,0.0,2.0,1.0,2.0,3.0,17.0,20.0,11.0,5.0,0.0,2.0,7.0,7.0
1,Aaron Miles,1610612744,GSW,Golden State,101223,6.0,18.0,0.0,0.0,4.0,4.0,0.0,14.0,14.0,24.0,4.0,1.0,11.0,13.0,16.0
2,Aaron Williams,1610612761,TOR,Toronto,1425,91.0,176.0,0.0,0.0,40.0,58.0,64.0,117.0,181.0,17.0,17.0,21.0,30.0,138.0,222.0
3,Adonal Foyle,1610612744,GSW,Golden State,1502,152.0,300.0,0.0,0.0,41.0,67.0,143.0,281.0,424.0,33.0,44.0,125.0,80.0,215.0,345.0
4,Adrian Griffin,1610612742,DAL,Dallas,1559,98.0,204.0,0.0,2.0,41.0,53.0,75.0,152.0,227.0,89.0,51.0,9.0,39.0,113.0,237.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
453,Zaza Pachulia,1610612737,ATL,Atlanta,2585,307.0,681.0,0.0,2.0,297.0,404.0,264.0,349.0,613.0,129.0,89.0,39.0,180.0,286.0,911.0
454,Zeljko Rebraca,1610612746,LAC,Los Angeles,1442,52.0,96.0,0.0,0.0,31.0,41.0,13.0,51.0,64.0,9.0,5.0,19.0,24.0,59.0,135.0
455,Zendon Hamilton,1610612739,CLE,Cleveland,1985,7.0,14.0,0.0,0.0,12.0,18.0,3.0,8.0,11.0,0.0,4.0,0.0,6.0,5.0,26.0
456,Zoran Planinic,1610612751,NJN,New Jersey,2565,66.0,183.0,13.0,56.0,46.0,66.0,14.0,60.0,74.0,53.0,20.0,4.0,43.0,91.0,191.0
457,Zydrunas Ilgauskas,1610612739,CLE,Cleveland,980,450.0,889.0,0.0,5.0,317.0,380.0,245.0,346.0,591.0,91.0,38.0,136.0,155.0,280.0,1217.0

In [129]:
filtered_07 = Season_07[['TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_CITY', 'PLAYER_ID', 'PLAYER_NAME', '2pointer_MADE', '2pointer_ATTEMPTS',
                        '3pointer_MADE', '3pointer_ATTEMPTS', 'FreeThrow_MADE', 'FreeThrow_ATTEMPTS', 'OFFENSIVE_REBOUNDS', 
                         'DEFENSIVE_REBOUNDS', 'REBOUNDS_TOTAL', 'ASSISTS','STEALS', 'BLOCKS', 'TURNOVERS', 'PERSONAL_FOULS', 'POINTS']]
filtered_07

,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
128123,1610612764,WAS,Washington,2553,Jarvis Hayes,3.0,10.0,1.0,2.0,2.0,2.0,0.0,3.0,3.0,0.0,2.0,0.0,1.0,1.0,9.0
128124,1610612764,WAS,Washington,1712,Antawn Jamison,5.0,14.0,0.0,3.0,9.0,12.0,0.0,11.0,11.0,1.0,1.0,0.0,1.0,3.0,19.0
128125,1610612764,WAS,Washington,2041,Etan Thomas,4.0,6.0,0.0,0.0,2.0,4.0,2.0,6.0,8.0,0.0,1.0,4.0,2.0,2.0,10.0
128126,1610612764,WAS,Washington,2052,DeShawn Stevenson,5.0,11.0,3.0,7.0,2.0,4.0,0.0,1.0,1.0,3.0,0.0,0.0,2.0,3.0,15.0
128127,1610612764,WAS,Washington,1498,Antonio Daniels,4.0,6.0,0.0,1.0,5.0,8.0,0.0,5.0,5.0,9.0,0.0,0.0,1.0,0.0,13.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153203,1610612747,LAL,Los Angeles,2230,Maurice Evans,8.0,13.0,0.0,1.0,1.0,2.0,2.0,2.0,4.0,0.0,3.0,0.0,1.0,3.0,17.0
153204,1610612747,LAL,Los Angeles,101142,Ronny Turiaf,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0
153205,1610612747,LAL,Los Angeles,2209,Vladimir Radmanovic,4.0,7.0,0.0,0.0,0.0,2.0,2.0,1.0,3.0,3.0,0.0,1.0,2.0,4.0,8.0
153206,1610612747,LAL,Los Angeles,2567,Brian Cook,4.0,7.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,2.0,1.0,9.0
153207,1610612747,LAL,Los Angeles,200770,Jordan Farmar,3.0,3.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,1.0,0.0,0.0,2.0,1.0,6.0

In [130]:
by_player_07 = filtered_07.groupby(['PLAYER_NAME']).agg({'TEAM_ID': 'last', 'TEAM_ABBREVIATION': 'last', 'TEAM_CITY': 'last', 'PLAYER_ID': 'last',
                                                            '2pointer_MADE': 'sum', '2pointer_ATTEMPTS': 'sum',
                                                            '3pointer_MADE': 'sum', '3pointer_ATTEMPTS': 'sum', 'FreeThrow_MADE': 'sum', 
                                                            'FreeThrow_ATTEMPTS': 'sum', 'OFFENSIVE_REBOUNDS': 'sum', 
                                                            'DEFENSIVE_REBOUNDS': 'sum', 'REBOUNDS_TOTAL': 'sum', 'ASSISTS': 'sum',
                                                            'STEALS': 'sum', 'BLOCKS': 'sum', 'TURNOVERS': 'sum', 'PERSONAL_FOULS': 'sum', 
                                                            'POINTS': 'sum'}).reset_index()
by_player_07

,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,Aaron McKie,1610612747,LAL,Los Angeles,243,11.0,17.0,0.0,0.0,0.0,0.0,1.0,17.0,18.0,13.0,4.0,0.0,8.0,14.0,22.0
1,Aaron Williams,1610612746,LAC,Los Angeles,1425,29.0,53.0,0.0,1.0,18.0,22.0,27.0,58.0,85.0,7.0,7.0,14.0,18.0,56.0,76.0
2,Adam Morrison,1610612766,CHA,Charlotte,200747,355.0,944.0,87.0,258.0,120.0,169.0,54.0,176.0,230.0,163.0,28.0,6.0,130.0,179.0,917.0
3,Adonal Foyle,1610612744,GSW,Golden State,1502,48.0,85.0,0.0,0.0,11.0,25.0,51.0,75.0,126.0,19.0,11.0,50.0,23.0,61.0,107.0
4,Adrian Griffin,1610612741,CHI,Chicago,1559,61.0,129.0,0.0,6.0,15.0,19.0,40.0,69.0,109.0,59.0,32.0,4.0,38.0,78.0,137.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
453,Yao Ming,1610612745,HOU,Houston,2397,423.0,819.0,0.0,2.0,356.0,413.0,101.0,351.0,452.0,94.0,17.0,94.0,167.0,159.0,1202.0
454,Yaroslav Korolev,1610612746,LAC,Los Angeles,101117,4.0,16.0,1.0,5.0,3.0,6.0,1.0,2.0,3.0,4.0,3.0,0.0,1.0,0.0,12.0
455,Zach Randolph,1610612757,POR,Portland,2216,600.0,1286.0,14.0,48.0,394.0,481.0,199.0,489.0,688.0,147.0,53.0,15.0,215.0,184.0,1608.0
456,Zaza Pachulia,1610612737,ATL,Atlanta,2585,291.0,614.0,0.0,1.0,293.0,373.0,199.0,301.0,500.0,106.0,77.0,36.0,162.0,267.0,875.0
457,Zydrunas Ilgauskas,1610612739,CLE,Cleveland,980,385.0,793.0,0.0,1.0,155.0,192.0,242.0,357.0,599.0,123.0,48.0,98.0,141.0,257.0,925.0

In [131]:
filtered_08 = Season_08[['TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_CITY', 'PLAYER_ID', 'PLAYER_NAME', '2pointer_MADE', '2pointer_ATTEMPTS',
                        '3pointer_MADE', '3pointer_ATTEMPTS', 'FreeThrow_MADE', 'FreeThrow_ATTEMPTS', 'OFFENSIVE_REBOUNDS', 
                         'DEFENSIVE_REBOUNDS', 'REBOUNDS_TOTAL', 'ASSISTS','STEALS', 'BLOCKS', 'TURNOVERS', 'PERSONAL_FOULS', 'POINTS']]
filtered_08

,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
99329,1610612746,LAC,Los Angeles,201154,Al Thornton,1.0,8.0,0.0,1.0,0.0,0.0,0.0,5.0,5.0,2.0,0.0,1.0,2.0,3.0,2.0
99330,1610612746,LAC,Los Angeles,2694,Josh Powell,5.0,9.0,0.0,0.0,0.0,0.0,7.0,3.0,10.0,1.0,0.0,0.0,0.0,0.0,10.0
99331,1610612746,LAC,Los Angeles,1882,Elton Brand,5.0,14.0,0.0,0.0,8.0,8.0,3.0,9.0,12.0,1.0,0.0,3.0,2.0,3.0,18.0
99332,1610612746,LAC,Los Angeles,1749,Cuttino Mobley,3.0,8.0,0.0,0.0,0.0,0.0,0.0,4.0,4.0,1.0,0.0,0.0,1.0,1.0,6.0
99333,1610612746,LAC,Los Angeles,2470,Smush Parker,4.0,8.0,1.0,3.0,0.0,0.0,0.0,2.0,2.0,2.0,1.0,0.0,4.0,2.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124209,1610612744,GSW,Golden State,2440,Matt Barnes,1.0,7.0,0.0,3.0,0.0,0.0,2.0,2.0,4.0,1.0,0.0,1.0,2.0,2.0,2.0
124210,1610612744,GSW,Golden State,1607,Troy Hudson,1.0,6.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,2.0,1.0,2.0
124211,1610612744,GSW,Golden State,201158,Marco Belinelli,2.0,4.0,2.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,6.0
124212,1610612744,GSW,Golden State,1506,Austin Croshere,0.0,1.0,0.0,1.0,0.0,0.0,0.0,2.0,2.0,1.0,0.0,0.0,0.0,1.0,0.0
124213,1610612744,GSW,Golden State,200753,Patrick O'Bryant,1.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,1.0,0.0,0.0,0.0,2.0,2.0

In [132]:
by_player_08 = filtered_08.groupby(['PLAYER_NAME']).agg({'TEAM_ID': 'last', 'TEAM_ABBREVIATION': 'last', 'TEAM_CITY': 'last', 'PLAYER_ID': 'last',
                                                            '2pointer_MADE': 'sum', '2pointer_ATTEMPTS': 'sum',
                                                            '3pointer_MADE': 'sum', '3pointer_ATTEMPTS': 'sum', 'FreeThrow_MADE': 'sum', 
                                                            'FreeThrow_ATTEMPTS': 'sum', 'OFFENSIVE_REBOUNDS': 'sum', 
                                                            'DEFENSIVE_REBOUNDS': 'sum', 'REBOUNDS_TOTAL': 'sum', 'ASSISTS': 'sum',
                                                            'STEALS': 'sum', 'BLOCKS': 'sum', 'TURNOVERS': 'sum', 'PERSONAL_FOULS': 'sum', 
                                                            'POINTS': 'sum'}).reset_index()
by_player_08

,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,Aaron Brooks,1610612745,HOU,Houston,201166,93.0,225.0,36.0,109.0,42.0,49.0,13.0,43.0,56.0,87.0,13.0,5.0,44.0,69.0,264.0
1,Aaron Gray,1610612741,CHI,Chicago,201189,103.0,204.0,0.0,1.0,56.0,99.0,70.0,98.0,168.0,41.0,21.0,16.0,57.0,117.0,262.0
2,Aaron Williams,1610612746,LAC,Los Angeles,1425,27.0,55.0,0.0,0.0,14.0,18.0,15.0,46.0,61.0,9.0,12.0,15.0,13.0,44.0,68.0
3,Acie Law,1610612737,ATL,Atlanta,201151,95.0,237.0,7.0,34.0,38.0,48.0,12.0,45.0,57.0,113.0,29.0,0.0,56.0,73.0,235.0
4,Adonal Foyle,1610612753,ORL,Orlando,1502,70.0,153.0,0.0,0.0,16.0,34.0,71.0,137.0,208.0,18.0,16.0,45.0,32.0,94.0,156.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
445,Yao Ming,1610612745,HOU,Houston,2397,432.0,852.0,0.0,2.0,345.0,406.0,172.0,422.0,594.0,129.0,25.0,111.0,183.0,171.0,1209.0
446,Yi Jianlian,1610612749,MIL,Milwaukee,201146,219.0,520.0,6.0,21.0,122.0,145.0,106.0,238.0,344.0,55.0,36.0,56.0,90.0,153.0,566.0
447,Zach Randolph,1610612752,NYK,New York,2216,486.0,1058.0,22.0,80.0,223.0,289.0,184.0,526.0,710.0,140.0,59.0,16.0,186.0,194.0,1217.0
448,Zaza Pachulia,1610612737,ATL,Atlanta,2585,107.0,245.0,0.0,3.0,108.0,153.0,89.0,159.0,248.0,36.0,24.0,13.0,69.0,140.0,322.0
449,Zydrunas Ilgauskas,1610612739,CLE,Cleveland,980,417.0,879.0,0.0,1.0,195.0,243.0,263.0,419.0,682.0,104.0,34.0,120.0,135.0,247.0,1029.0

In [133]:
filtered_09 = Season_09[['TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_CITY', 'PLAYER_ID', 'PLAYER_NAME', '2pointer_MADE', '2pointer_ATTEMPTS',
                        '3pointer_MADE', '3pointer_ATTEMPTS', 'FreeThrow_MADE', 'FreeThrow_ATTEMPTS', 'OFFENSIVE_REBOUNDS', 
                         'DEFENSIVE_REBOUNDS', 'REBOUNDS_TOTAL', 'ASSISTS','STEALS', 'BLOCKS', 'TURNOVERS', 'PERSONAL_FOULS', 'POINTS']]
filtered_09

,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
70283,1610612751,NJN,New Jersey,201583,Ryan Anderson,4.0,11.0,2.0,5.0,3.0,4.0,3.0,8.0,11.0,0.0,3.0,0.0,2.0,3.0,13.0
70284,1610612751,NJN,New Jersey,2239,Trenton Hassell,2.0,6.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,1.0,0.0,0.0,0.0,1.0,4.0
70285,1610612751,NJN,New Jersey,201572,Brook Lopez,2.0,9.0,0.0,0.0,2.0,2.0,3.0,4.0,7.0,1.0,0.0,3.0,2.0,1.0,6.0
70286,1610612751,NJN,New Jersey,2039,Keyon Dooling,2.0,8.0,0.0,3.0,2.0,2.0,2.0,5.0,7.0,5.0,0.0,0.0,1.0,1.0,6.0
70287,1610612751,NJN,New Jersey,201604,Chris Douglas-Roberts,6.0,16.0,0.0,0.0,6.0,6.0,1.0,1.0,2.0,2.0,2.0,0.0,5.0,2.0,18.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94907,1610612747,LAL,Los Angeles,2772,Trevor Ariza,4.0,7.0,2.0,2.0,1.0,1.0,0.0,2.0,2.0,1.0,1.0,2.0,0.0,0.0,11.0
94908,1610612747,LAL,Los Angeles,2756,Sasha Vujacic,2.0,6.0,1.0,2.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,5.0
94909,1610612747,LAL,Los Angeles,2036,Chris Mihm,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,2.0
94910,1610612747,LAL,Los Angeles,2694,Josh Powell,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
94911,1610612747,LAL,Los Angeles,2575,Luke Walton,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [134]:
by_player_09 = filtered_09.groupby(['PLAYER_NAME']).agg({'TEAM_ID': 'last', 'TEAM_ABBREVIATION': 'last', 'TEAM_CITY': 'last', 'PLAYER_ID': 'last',
                                                            '2pointer_MADE': 'sum', '2pointer_ATTEMPTS': 'sum',
                                                            '3pointer_MADE': 'sum', '3pointer_ATTEMPTS': 'sum', 'FreeThrow_MADE': 'sum', 
                                                            'FreeThrow_ATTEMPTS': 'sum', 'OFFENSIVE_REBOUNDS': 'sum', 
                                                            'DEFENSIVE_REBOUNDS': 'sum', 'REBOUNDS_TOTAL': 'sum', 'ASSISTS': 'sum',
                                                            'STEALS': 'sum', 'BLOCKS': 'sum', 'TURNOVERS': 'sum', 'PERSONAL_FOULS': 'sum', 
                                                            'POINTS': 'sum'}).reset_index()
by_player_09

,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,Aaron Brooks,1610612745,HOU,Houston,201166,316.0,783.0,113.0,309.0,149.0,172.0,33.0,124.0,157.0,238.0,46.0,8.0,125.0,152.0,894.0
1,Aaron Gray,1610612741,CHI,Chicago,201189,81.0,167.0,0.0,1.0,34.0,59.0,84.0,136.0,220.0,46.0,14.0,18.0,40.0,135.0,196.0
2,Acie Law,1610612737,ATL,Atlanta,201151,52.0,139.0,9.0,29.0,49.0,60.0,6.0,52.0,58.0,86.0,11.0,3.0,29.0,43.0,162.0
3,Adam Morrison,1610612766,CHA,Charlotte,200747,80.0,223.0,32.0,96.0,17.0,23.0,18.0,62.0,80.0,41.0,9.0,4.0,32.0,77.0,209.0
4,Adonal Foyle,1610612753,ORL,Orlando,1502,7.0,11.0,0.0,0.0,3.0,6.0,9.0,17.0,26.0,1.0,0.0,8.0,3.0,5.0,17.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
439,Yao Ming,1610612745,HOU,Houston,2397,566.0,1032.0,1.0,1.0,381.0,440.0,204.0,557.0,761.0,137.0,30.0,150.0,234.0,257.0,1514.0
440,Yi Jianlian,1610612751,NJN,New Jersey,201146,191.0,500.0,48.0,140.0,95.0,123.0,67.0,259.0,326.0,60.0,29.0,36.0,70.0,157.0,525.0
441,Zach Randolph,1610612752,NYK,New York,2216,415.0,873.0,32.0,97.0,179.0,244.0,157.0,347.0,504.0,103.0,43.0,16.0,114.0,133.0,1041.0
442,Zaza Pachulia,1610612737,ATL,Atlanta,2585,159.0,320.0,0.0,3.0,163.0,230.0,173.0,263.0,436.0,57.0,35.0,26.0,91.0,208.0,481.0
443,Zydrunas Ilgauskas,1610612739,CLE,Cleveland,980,342.0,724.0,15.0,39.0,139.0,174.0,157.0,333.0,490.0,64.0,28.0,84.0,90.0,183.0,838.0

In [135]:
filtered_10 = Season_10[['TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_CITY', 'PLAYER_ID', 'PLAYER_NAME', '2pointer_MADE', '2pointer_ATTEMPTS',
                        '3pointer_MADE', '3pointer_ATTEMPTS', 'FreeThrow_MADE', 'FreeThrow_ATTEMPTS', 'OFFENSIVE_REBOUNDS', 
                         'DEFENSIVE_REBOUNDS', 'REBOUNDS_TOTAL', 'ASSISTS','STEALS', 'BLOCKS', 'TURNOVERS', 'PERSONAL_FOULS', 'POINTS']]
filtered_10

,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
293479,1610612752,NYK,New York,201568,Danilo Gallinari,6.0,18.0,5.0,12.0,5.0,8.0,1.0,3.0,4.0,2.0,1.0,0.0,3.0,3.0,22.0
293480,1610612752,NYK,New York,101135,David Lee,8.0,17.0,0.0,0.0,3.0,3.0,6.0,5.0,11.0,5.0,1.0,1.0,5.0,4.0,19.0
293481,1610612752,NYK,New York,2853,Earl Barron,4.0,10.0,0.0,0.0,3.0,4.0,4.0,3.0,7.0,1.0,1.0,0.0,1.0,3.0,11.0
293482,1610612752,NYK,New York,201611,Henry Walker,8.0,17.0,6.0,10.0,6.0,7.0,2.0,5.0,7.0,1.0,0.0,0.0,0.0,3.0,28.0
293483,1610612752,NYK,New York,2768,Chris Duhon,4.0,7.0,2.0,4.0,0.0,0.0,0.0,0.0,0.0,5.0,1.0,0.0,0.0,0.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318287,1610612747,LAL,Los Angeles,2756,Sasha Vujacic,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
318288,1610612747,LAL,Los Angeles,2788,DJ Mbenga,1.0,5.0,0.0,0.0,0.0,0.0,2.0,1.0,3.0,0.0,0.0,0.0,0.0,1.0,2.0
318289,1610612747,LAL,Los Angeles,200769,Shannon Brown,0.0,0.0,0.0,0.0,1.0,4.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0
318290,1610612747,LAL,Los Angeles,2694,Josh Powell,1.0,3.0,0.0,1.0,0.0,0.0,1.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,2.0
318291,1610612747,LAL,Los Angeles,2575,Luke Walton,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [136]:
by_player_10 = filtered_10.groupby(['PLAYER_NAME']).agg({'TEAM_ID': 'last', 'TEAM_ABBREVIATION': 'last', 'TEAM_CITY': 'last', 'PLAYER_ID': 'last',
                                                            '2pointer_MADE': 'sum', '2pointer_ATTEMPTS': 'sum',
                                                            '3pointer_MADE': 'sum', '3pointer_ATTEMPTS': 'sum', 'FreeThrow_MADE': 'sum', 
                                                            'FreeThrow_ATTEMPTS': 'sum', 'OFFENSIVE_REBOUNDS': 'sum', 
                                                            'DEFENSIVE_REBOUNDS': 'sum', 'REBOUNDS_TOTAL': 'sum', 'ASSISTS': 'sum',
                                                            'STEALS': 'sum', 'BLOCKS': 'sum', 'TURNOVERS': 'sum', 'PERSONAL_FOULS': 'sum', 
                                                            'POINTS': 'sum'}).reset_index()
by_player_10

,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,AJ Price,1610612754,IND,Indiana,201985,145.0,354.0,60.0,174.0,60.0,75.0,12.0,76.0,88.0,106.0,35.0,3.0,59.0,53.0,410.0
1,Aaron Brooks,1610612745,HOU,Houston,201166,575.0,1331.0,209.0,525.0,245.0,298.0,54.0,161.0,215.0,434.0,69.0,14.0,232.0,199.0,1604.0
2,Aaron Gray,1610612741,CHI,Chicago,201189,42.0,82.0,0.0,0.0,20.0,28.0,45.0,61.0,106.0,22.0,9.0,11.0,18.0,54.0,104.0
3,Acie Law,1610612744,GSW,Golden State,201151,35.0,75.0,5.0,16.0,38.0,49.0,3.0,14.0,17.0,26.0,11.0,1.0,17.0,16.0,113.0
4,Adam Morrison,1610612747,LAL,Los Angeles,200747,32.0,85.0,5.0,21.0,5.0,8.0,10.0,22.0,32.0,18.0,3.0,2.0,10.0,17.0,74.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
437,Yakhouba Diawara,1610612748,MIA,Miami,200821,2.0,10.0,1.0,6.0,0.0,0.0,1.0,3.0,4.0,3.0,1.0,0.0,3.0,8.0,5.0
438,Yi Jianlian,1610612751,NJN,New Jersey,201146,227.0,563.0,15.0,41.0,154.0,193.0,115.0,257.0,372.0,47.0,37.0,52.0,77.0,170.0,623.0
439,Zach Randolph,1610612763,MEM,Memphis,2216,652.0,1336.0,15.0,52.0,362.0,465.0,330.0,620.0,950.0,149.0,80.0,34.0,174.0,226.0,1681.0
440,Zaza Pachulia,1610612737,ATL,Atlanta,2585,120.0,246.0,0.0,4.0,93.0,143.0,117.0,176.0,293.0,42.0,37.0,31.0,58.0,186.0,333.0
441,Zydrunas Ilgauskas,1610612739,CLE,Cleveland,980,194.0,438.0,11.0,23.0,75.0,101.0,114.0,231.0,345.0,48.0,14.0,50.0,63.0,183.0,474.0

In [137]:
filtered_11 = Season_11[['TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_CITY', 'PLAYER_ID', 'PLAYER_NAME', '2pointer_MADE', '2pointer_ATTEMPTS',
                        '3pointer_MADE', '3pointer_ATTEMPTS', 'FreeThrow_MADE', 'FreeThrow_ATTEMPTS', 'OFFENSIVE_REBOUNDS', 
                         'DEFENSIVE_REBOUNDS', 'REBOUNDS_TOTAL', 'ASSISTS','STEALS', 'BLOCKS', 'TURNOVERS', 'PERSONAL_FOULS', 'POINTS']]
filtered_11

,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
263980,1610612757,POR,Portland,201164,Rudy Fernandez,2.0,8.0,1.0,5.0,0.0,0.0,0.0,2.0,2.0,5.0,1.0,0.0,1.0,1.0,5.0
263981,1610612757,POR,Portland,202419,Chris Johnson,1.0,8.0,0.0,0.0,6.0,8.0,8.0,5.0,13.0,1.0,1.0,1.0,2.0,4.0,8.0
263982,1610612757,POR,Portland,2853,Earl Barron,2.0,10.0,0.0,0.0,1.0,2.0,4.0,9.0,13.0,3.0,0.0,0.0,3.0,4.0,5.0
263983,1610612757,POR,Portland,202083,Wesley Matthews,5.0,9.0,4.0,7.0,4.0,4.0,0.0,1.0,1.0,1.0,0.0,0.0,4.0,0.0,18.0
263984,1610612757,POR,Portland,1889,Andre Miller,2.0,3.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289128,1610612747,LAL,Los Angeles,202382,Derrick Caracter,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
289129,1610612747,LAL,Los Angeles,689,Theo Ratliff,0.0,2.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,1.0,0.0,2.0,0.0,1.0,0.0
289130,1610612747,LAL,Los Angeles,2581,Steve Blake,3.0,5.0,3.0,4.0,1.0,2.0,0.0,0.0,0.0,3.0,1.0,0.0,0.0,2.0,10.0
289131,1610612747,LAL,Los Angeles,200769,Shannon Brown,6.0,9.0,4.0,5.0,0.0,0.0,0.0,1.0,1.0,1.0,4.0,0.0,2.0,0.0,16.0
289132,1610612747,LAL,Los Angeles,2440,Matt Barnes,1.0,4.0,0.0,1.0,4.0,4.0,4.0,1.0,5.0,2.0,0.0,0.0,1.0,3.0,6.0

In [138]:
by_player_11 = filtered_11.groupby(['PLAYER_NAME']).agg({'TEAM_ID': 'last', 'TEAM_ABBREVIATION': 'last', 'TEAM_CITY': 'last', 'PLAYER_ID': 'last',
                                                            '2pointer_MADE': 'sum', '2pointer_ATTEMPTS': 'sum',
                                                            '3pointer_MADE': 'sum', '3pointer_ATTEMPTS': 'sum', 'FreeThrow_MADE': 'sum', 
                                                            'FreeThrow_ATTEMPTS': 'sum', 'OFFENSIVE_REBOUNDS': 'sum', 
                                                            'DEFENSIVE_REBOUNDS': 'sum', 'REBOUNDS_TOTAL': 'sum', 'ASSISTS': 'sum',
                                                            'STEALS': 'sum', 'BLOCKS': 'sum', 'TURNOVERS': 'sum', 'PERSONAL_FOULS': 'sum', 
                                                            'POINTS': 'sum'}).reset_index()
by_player_11

,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,AJ Price,1610612754,IND,Indiana,201985,114.0,320.0,41.0,149.0,54.0,81.0,16.0,56.0,72.0,111.0,29.0,1.0,53.0,61.0,323.0
1,Aaron Brooks,1610612745,HOU,Houston,201166,220.0,587.0,70.0,236.0,124.0,140.0,20.0,58.0,78.0,233.0,34.0,3.0,99.0,115.0,634.0
2,Aaron Gray,1610612740,NOH,New Orleans,201189,56.0,99.0,0.0,0.0,17.0,34.0,59.0,112.0,171.0,16.0,11.0,12.0,32.0,96.0,129.0
3,Acie Law,1610612763,MEM,Memphis,201151,81.0,186.0,6.0,36.0,47.0,64.0,12.0,51.0,63.0,84.0,32.0,0.0,43.0,61.0,215.0
4,Al Harrington,1610612743,DEN,Denver,1733,281.0,675.0,117.0,328.0,86.0,117.0,76.0,256.0,332.0,101.0,39.0,10.0,106.0,202.0,765.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447,Yi Jianlian,1610612764,WAS,Washington,201146,145.0,347.0,3.0,13.0,62.0,91.0,79.0,169.0,248.0,25.0,27.0,32.0,51.0,115.0,355.0
448,Zabian Dowdell,1610612756,PHX,Phoenix,202220,51.0,125.0,3.0,10.0,16.0,17.0,5.0,15.0,20.0,51.0,20.0,2.0,29.0,30.0,121.0
449,Zach Randolph,1610612763,MEM,Memphis,2216,598.0,1188.0,8.0,43.0,300.0,396.0,326.0,588.0,914.0,163.0,63.0,25.0,151.0,175.0,1504.0
450,Zaza Pachulia,1610612737,ATL,Atlanta,2585,107.0,232.0,0.0,0.0,135.0,179.0,119.0,214.0,333.0,58.0,34.0,22.0,69.0,184.0,349.0
451,Zydrunas Ilgauskas,1610612748,MIA,Miami,980,162.0,319.0,0.0,1.0,36.0,46.0,108.0,179.0,287.0,26.0,23.0,58.0,52.0,185.0,360.0

In [139]:
filtered_12 = Season_12[['TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_CITY', 'PLAYER_ID', 'PLAYER_NAME', '2pointer_MADE', '2pointer_ATTEMPTS',
                        '3pointer_MADE', '3pointer_ATTEMPTS', 'FreeThrow_MADE', 'FreeThrow_ATTEMPTS', 'OFFENSIVE_REBOUNDS', 
                         'DEFENSIVE_REBOUNDS', 'REBOUNDS_TOTAL', 'ASSISTS','STEALS', 'BLOCKS', 'TURNOVERS', 'PERSONAL_FOULS', 'POINTS']]
filtered_12

,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
240853,1610612740,NOH,New Orleans,202498,Lance Thomas,2.0,6.0,0.0,0.0,7.0,8.0,2.0,6.0,8.0,0.0,1.0,2.0,2.0,3.0,11.0
240854,1610612740,NOH,New Orleans,202329,Al-Farouq Aminu,4.0,13.0,2.0,3.0,1.0,3.0,0.0,10.0,10.0,3.0,0.0,0.0,0.0,3.0,11.0
240855,1610612740,NOH,New Orleans,201160,Jason Smith,1.0,2.0,0.0,0.0,0.0,0.0,0.0,4.0,4.0,2.0,0.0,0.0,0.0,0.0,2.0
240856,1610612740,NOH,New Orleans,201158,Marco Belinelli,4.0,8.0,1.0,2.0,0.0,0.0,0.0,4.0,4.0,2.0,1.0,1.0,0.0,0.0,9.0
240857,1610612740,NOH,New Orleans,202406,Jerome Dyson,6.0,14.0,0.0,3.0,3.0,6.0,1.0,1.0,2.0,1.0,3.0,1.0,4.0,3.0,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261606,1610612752,NYK,New York,2407,Jared Jeffries,1.0,3.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,2.0,2.0
261607,1610612752,NYK,New York,202697,Iman Shumpert,3.0,13.0,0.0,1.0,5.0,5.0,1.0,3.0,4.0,1.0,0.0,0.0,2.0,2.0,11.0
261608,1610612752,NYK,New York,201611,Henry Walker,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,4.0,0.0
261609,1610612752,NYK,New York,202725,Josh Harrellson,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,1.0,0.0,1.0,1.0,0.0,0.0
261610,1610612752,NYK,New York,200764,Renaldo Balkman,1.0,1.0,0.0,0.0,0.0,0.0,2.0,1.0,3.0,1.0,0.0,0.0,0.0,2.0,2.0

In [140]:
by_player_12 = filtered_12.groupby(['PLAYER_NAME']).agg({'TEAM_ID': 'last', 'TEAM_ABBREVIATION': 'last', 'TEAM_CITY': 'last', 'PLAYER_ID': 'last',
                                                            '2pointer_MADE': 'sum', '2pointer_ATTEMPTS': 'sum',
                                                            '3pointer_MADE': 'sum', '3pointer_ATTEMPTS': 'sum', 'FreeThrow_MADE': 'sum', 
                                                            'FreeThrow_ATTEMPTS': 'sum', 'OFFENSIVE_REBOUNDS': 'sum', 
                                                            'DEFENSIVE_REBOUNDS': 'sum', 'REBOUNDS_TOTAL': 'sum', 'ASSISTS': 'sum',
                                                            'STEALS': 'sum', 'BLOCKS': 'sum', 'TURNOVERS': 'sum', 'PERSONAL_FOULS': 'sum', 
                                                            'POINTS': 'sum'}).reset_index()
by_player_12

,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,AJ Price,1610612754,IND,Indiana,201985,59.0,174.0,26.0,88.0,28.0,35.0,13.0,48.0,61.0,86.0,20.0,2.0,32.0,30.0,172.0
1,Aaron Gray,1610612761,TOR,Toronto,201189,83.0,161.0,0.0,0.0,25.0,47.0,83.0,198.0,281.0,27.0,22.0,17.0,51.0,127.0,191.0
2,Al Harrington,1610612743,DEN,Denver,1733,345.0,773.0,101.0,303.0,119.0,176.0,72.0,318.0,390.0,88.0,58.0,12.0,112.0,181.0,910.0
3,Al Horford,1610612737,ATL,Atlanta,201143,57.0,103.0,0.0,1.0,22.0,30.0,26.0,51.0,77.0,24.0,10.0,14.0,16.0,21.0,136.0
4,Al Jefferson,1610612762,UTA,Utah,2744,516.0,1048.0,1.0,4.0,137.0,177.0,133.0,452.0,585.0,134.0,47.0,101.0,62.0,155.0,1170.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
473,Xavier Henry,1610612740,NOH,New Orleans,202333,90.0,228.0,7.0,17.0,52.0,85.0,24.0,82.0,106.0,35.0,26.0,8.0,35.0,59.0,239.0
474,Xavier Silas,1610612755,PHI,Philadelphia,202918,4.0,15.0,1.0,6.0,2.0,3.0,2.0,2.0,4.0,3.0,0.0,0.0,3.0,5.0,11.0
475,Yi Jianlian,1610612742,DAL,Dallas,201146,31.0,82.0,3.0,10.0,14.0,21.0,12.0,37.0,49.0,5.0,7.0,8.0,14.0,23.0,79.0
476,Zach Randolph,1610612763,MEM,Memphis,2216,132.0,285.0,2.0,8.0,58.0,88.0,78.0,147.0,225.0,48.0,21.0,4.0,40.0,57.0,324.0
477,Zaza Pachulia,1610612737,ATL,Atlanta,2585,169.0,339.0,0.0,0.0,117.0,158.0,154.0,303.0,457.0,79.0,55.0,29.0,81.0,172.0,455.0

In [141]:
filtered_13 = Season_13[['TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_CITY', 'PLAYER_ID', 'PLAYER_NAME', '2pointer_MADE', '2pointer_ATTEMPTS',
                        '3pointer_MADE', '3pointer_ATTEMPTS', 'FreeThrow_MADE', 'FreeThrow_ATTEMPTS', 'OFFENSIVE_REBOUNDS', 
                         'DEFENSIVE_REBOUNDS', 'REBOUNDS_TOTAL', 'ASSISTS','STEALS', 'BLOCKS', 'TURNOVERS', 'PERSONAL_FOULS', 'POINTS']]
filtered_13

,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
511937,1610612762,UTA,Utah,202330,Gordon Hayward,4.0,8.0,1.0,1.0,0.0,1.0,3.0,0.0,3.0,2.0,1.0,0.0,3.0,1.0,9.0
511938,1610612762,UTA,Utah,200794,Paul Millsap,2.0,7.0,0.0,0.0,2.0,4.0,5.0,3.0,8.0,0.0,1.0,2.0,0.0,4.0,6.0
511939,1610612762,UTA,Utah,2744,Al Jefferson,8.0,19.0,0.0,0.0,6.0,6.0,2.0,14.0,16.0,2.0,0.0,1.0,1.0,5.0,22.0
511940,1610612762,UTA,Utah,200751,Randy Foye,1.0,9.0,1.0,5.0,4.0,6.0,1.0,2.0,3.0,2.0,0.0,1.0,0.0,2.0,7.0
511941,1610612762,UTA,Utah,2590,Mo Williams,3.0,13.0,0.0,3.0,2.0,5.0,0.0,1.0,1.0,3.0,1.0,0.0,3.0,1.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
537689,1610612739,CLE,Cleveland,101139,CJ Miles,1.0,5.0,0.0,1.0,0.0,0.0,0.0,4.0,4.0,1.0,0.0,0.0,3.0,0.0,2.0
537690,1610612739,CLE,Cleveland,203092,Tyler Zeller,2.0,4.0,0.0,0.0,1.0,2.0,0.0,2.0,2.0,0.0,1.0,1.0,0.0,2.0,5.0
537691,1610612739,CLE,Cleveland,200789,Daniel Gibson,3.0,5.0,2.0,4.0,2.0,4.0,1.0,2.0,3.0,1.0,0.0,1.0,0.0,2.0,10.0
537692,1610612739,CLE,Cleveland,2575,Luke Walton,1.0,2.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,2.0,0.0,2.0
537693,1610612739,CLE,Cleveland,202388,Donald Sloan,2.0,5.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,2.0,4.0

In [142]:
by_player_13 = filtered_13.groupby(['PLAYER_NAME']).agg({'TEAM_ID': 'last', 'TEAM_ABBREVIATION': 'last', 'TEAM_CITY': 'last', 'PLAYER_ID': 'last',
                                                            '2pointer_MADE': 'sum', '2pointer_ATTEMPTS': 'sum',
                                                            '3pointer_MADE': 'sum', '3pointer_ATTEMPTS': 'sum', 'FreeThrow_MADE': 'sum', 
                                                            'FreeThrow_ATTEMPTS': 'sum', 'OFFENSIVE_REBOUNDS': 'sum', 
                                                            'DEFENSIVE_REBOUNDS': 'sum', 'REBOUNDS_TOTAL': 'sum', 'ASSISTS': 'sum',
                                                            'STEALS': 'sum', 'BLOCKS': 'sum', 'TURNOVERS': 'sum', 'PERSONAL_FOULS': 'sum', 
                                                            'POINTS': 'sum'}).reset_index()
by_player_13

,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,AJ Price,1610612764,WAS,Washington,201985,161.0,413.0,70.0,200.0,49.0,62.0,20.0,94.0,114.0,205.0,33.0,3.0,64.0,73.0,441.0
1,Aaron Brooks,1610612758,SAC,Sacramento,201166,143.0,316.0,50.0,134.0,40.0,52.0,13.0,67.0,80.0,114.0,30.0,10.0,67.0,94.0,376.0
2,Aaron Gray,1610612761,TOR,Toronto,201189,48.0,90.0,0.0,0.0,23.0,44.0,48.0,85.0,133.0,33.0,7.0,5.0,36.0,85.0,119.0
3,Al Harrington,1610612753,ORL,Orlando,1733,20.0,57.0,8.0,30.0,3.0,4.0,6.0,21.0,27.0,10.0,4.0,1.0,7.0,18.0,51.0
4,Al Horford,1610612737,ATL,Atlanta,201143,576.0,1060.0,3.0,6.0,134.0,208.0,195.0,562.0,757.0,240.0,78.0,78.0,147.0,163.0,1289.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
463,Willie Green,1610612746,LAC,Los Angeles,2584,178.0,386.0,71.0,166.0,23.0,32.0,17.0,80.0,97.0,55.0,29.0,12.0,31.0,96.0,450.0
464,Wilson Chandler,1610612743,DEN,Denver,201163,210.0,455.0,52.0,126.0,88.0,111.0,45.0,173.0,218.0,58.0,45.0,12.0,60.0,119.0,560.0
465,Xavier Henry,1610612740,NOH,New Orleans,202333,66.0,161.0,4.0,11.0,58.0,92.0,21.0,69.0,90.0,13.0,16.0,5.0,31.0,72.0,194.0
466,Zach Randolph,1610612763,MEM,Memphis,2216,471.0,1024.0,2.0,23.0,225.0,300.0,310.0,544.0,854.0,108.0,61.0,31.0,150.0,180.0,1169.0
467,Zaza Pachulia,1610612737,ATL,Atlanta,2585,114.0,241.0,0.0,3.0,78.0,103.0,132.0,204.0,336.0,79.0,35.0,12.0,70.0,128.0,306.0

In [143]:
filtered_14 = Season_14[['TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_CITY', 'PLAYER_ID', 'PLAYER_NAME', '2pointer_MADE', '2pointer_ATTEMPTS',
                        '3pointer_MADE', '3pointer_ATTEMPTS', 'FreeThrow_MADE', 'FreeThrow_ATTEMPTS', 'OFFENSIVE_REBOUNDS', 
                         'DEFENSIVE_REBOUNDS', 'REBOUNDS_TOTAL', 'ASSISTS','STEALS', 'BLOCKS', 'TURNOVERS', 'PERSONAL_FOULS', 'POINTS']]
filtered_14

,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
481833,1610612747,LAL,Los Angeles,202325,Wesley Johnson,5.0,17.0,1.0,7.0,0.0,0.0,1.0,10.0,11.0,2.0,0.0,0.0,0.0,1.0,11.0
481834,1610612747,LAL,Los Angeles,203527,Ryan Kelly,6.0,11.0,0.0,3.0,0.0,0.0,1.0,7.0,8.0,2.0,0.0,0.0,1.0,3.0,12.0
481835,1610612747,LAL,Los Angeles,201941,Jordan Hill,7.0,13.0,0.0,0.0,4.0,6.0,3.0,11.0,14.0,2.0,1.0,2.0,0.0,1.0,18.0
481836,1610612747,LAL,Los Angeles,201975,Jodie Meeks,5.0,6.0,2.0,2.0,2.0,2.0,0.0,3.0,3.0,3.0,2.0,0.0,1.0,1.0,14.0
481837,1610612747,LAL,Los Angeles,203088,Kendall Marshall,5.0,7.0,4.0,4.0,1.0,2.0,0.0,2.0,2.0,11.0,0.0,0.0,4.0,2.0,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
507446,1610612747,LAL,Los Angeles,201975,Jodie Meeks,4.0,8.0,3.0,6.0,2.0,2.0,0.0,3.0,3.0,2.0,1.0,0.0,2.0,2.0,13.0
507447,1610612747,LAL,Los Angeles,200770,Jordan Farmar,6.0,10.0,2.0,3.0,2.0,4.0,2.0,2.0,4.0,6.0,1.0,0.0,3.0,5.0,16.0
507448,1610612747,LAL,Los Angeles,202333,Xavier Henry,8.0,13.0,3.0,4.0,3.0,8.0,2.0,4.0,6.0,2.0,1.0,0.0,1.0,1.0,22.0
507449,1610612747,LAL,Los Angeles,202325,Wesley Johnson,1.0,11.0,1.0,4.0,0.0,0.0,0.0,3.0,3.0,1.0,0.0,1.0,0.0,4.0,3.0
507450,1610612747,LAL,Los Angeles,201941,Jordan Hill,6.0,8.0,0.0,0.0,0.0,0.0,7.0,1.0,8.0,2.0,1.0,1.0,1.0,2.0,12.0

In [144]:
by_player_14 = filtered_14.groupby(['PLAYER_NAME']).agg({'TEAM_ID': 'last', 'TEAM_ABBREVIATION': 'last', 'TEAM_CITY': 'last', 'PLAYER_ID': 'last',
                                                            '2pointer_MADE': 'sum', '2pointer_ATTEMPTS': 'sum',
                                                            '3pointer_MADE': 'sum', '3pointer_ATTEMPTS': 'sum', 'FreeThrow_MADE': 'sum', 
                                                            'FreeThrow_ATTEMPTS': 'sum', 'OFFENSIVE_REBOUNDS': 'sum', 
                                                            'DEFENSIVE_REBOUNDS': 'sum', 'REBOUNDS_TOTAL': 'sum', 'ASSISTS': 'sum',
                                                            'STEALS': 'sum', 'BLOCKS': 'sum', 'TURNOVERS': 'sum', 'PERSONAL_FOULS': 'sum', 
                                                            'POINTS': 'sum'}).reset_index()
by_player_14

,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,AJ Price,1610612750,MIN,Minnesota,201985,19.0,46.0,6.0,22.0,0.0,2.0,1.0,9.0,10.0,13.0,1.0,0.0,7.0,5.0,44.0
1,Aaron Brooks,1610612745,HOU,Houston,201166,233.0,581.0,96.0,248.0,83.0,95.0,43.0,97.0,140.0,233.0,52.0,13.0,117.0,146.0,645.0
2,Aaron Gray,1610612761,TOR,Toronto,201189,27.0,61.0,0.0,1.0,11.0,20.0,42.0,69.0,111.0,22.0,10.0,8.0,31.0,64.0,65.0
3,Adonis Thomas,1610612753,ORL,Orlando,203519,6.0,14.0,1.0,5.0,1.0,1.0,0.0,3.0,3.0,3.0,0.0,0.0,1.0,6.0,14.0
4,Al Harrington,1610612764,WAS,Washington,1733,82.0,207.0,34.0,100.0,27.0,35.0,15.0,65.0,80.0,28.0,14.0,0.0,34.0,72.0,225.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
476,Willie Green,1610612746,LAC,Los Angeles,2584,102.0,271.0,41.0,121.0,28.0,34.0,12.0,66.0,78.0,50.0,22.0,11.0,34.0,96.0,273.0
477,Wilson Chandler,1610612743,DEN,Denver,201163,307.0,738.0,122.0,351.0,110.0,152.0,58.0,236.0,294.0,114.0,46.0,31.0,79.0,193.0,846.0
478,Xavier Henry,1610612747,LAL,Los Angeles,202333,144.0,345.0,28.0,81.0,116.0,177.0,25.0,89.0,114.0,51.0,44.0,7.0,57.0,79.0,432.0
479,Zach Randolph,1610612763,MEM,Memphis,2216,560.0,1198.0,2.0,20.0,250.0,337.0,265.0,530.0,795.0,200.0,54.0,23.0,183.0,210.0,1372.0
480,Zaza Pachulia,1610612749,MIL,Milwaukee,2585,149.0,349.0,0.0,1.0,110.0,130.0,141.0,192.0,333.0,136.0,45.0,14.0,92.0,124.0,408.0

In [145]:
filtered_15 = Season_15[['TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_CITY', 'PLAYER_ID', 'PLAYER_NAME', '2pointer_MADE', '2pointer_ATTEMPTS',
                        '3pointer_MADE', '3pointer_ATTEMPTS', 'FreeThrow_MADE', 'FreeThrow_ATTEMPTS', 'OFFENSIVE_REBOUNDS', 
                         'DEFENSIVE_REBOUNDS', 'REBOUNDS_TOTAL', 'ASSISTS','STEALS', 'BLOCKS', 'TURNOVERS', 'PERSONAL_FOULS', 'POINTS']]
filtered_15

,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
451272,1610612753,ORL,Orlando,203932,Aaron Gordon,3.0,11.0,1.0,2.0,0.0,0.0,3.0,4.0,7.0,0.0,0.0,0.0,0.0,2.0,7.0
451273,1610612753,ORL,Orlando,203094,Andrew Nicholson,8.0,10.0,2.0,3.0,0.0,0.0,3.0,6.0,9.0,1.0,0.0,1.0,1.0,5.0,18.0
451274,1610612753,ORL,Orlando,202696,Nikola Vucevic,12.0,21.0,0.0,1.0,2.0,4.0,1.0,10.0,11.0,5.0,1.0,1.0,2.0,4.0,26.0
451275,1610612753,ORL,Orlando,203506,Victor Oladipo,7.0,17.0,3.0,7.0,2.0,5.0,0.0,2.0,2.0,3.0,0.0,1.0,4.0,0.0,19.0
451276,1610612753,ORL,Orlando,203901,Elfrid Payton,1.0,5.0,0.0,1.0,0.0,2.0,0.0,3.0,3.0,6.0,4.0,1.0,4.0,1.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
477248,1610612747,LAL,Los Angeles,203903,Jordan Clarkson,1.0,4.0,1.0,2.0,5.0,6.0,0.0,4.0,4.0,2.0,0.0,0.0,1.0,3.0,8.0
477249,1610612747,LAL,Los Angeles,202334,Ed Davis,5.0,7.0,0.0,0.0,1.0,2.0,2.0,4.0,6.0,0.0,1.0,2.0,0.0,6.0,11.0
477250,1610612747,LAL,Los Angeles,202333,Xavier Henry,0.0,4.0,0.0,0.0,3.0,4.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,3.0
477251,1610612747,LAL,Los Angeles,203944,Julius Randle,1.0,3.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0
477252,1610612747,LAL,Los Angeles,203135,Robert Sacre,1.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,2.0

In [146]:
by_player_15 = filtered_15.groupby(['PLAYER_NAME']).agg({'TEAM_ID': 'last', 'TEAM_ABBREVIATION': 'last', 'TEAM_CITY': 'last', 'PLAYER_ID': 'last',
                                                            '2pointer_MADE': 'sum', '2pointer_ATTEMPTS': 'sum',
                                                            '3pointer_MADE': 'sum', '3pointer_ATTEMPTS': 'sum', 'FreeThrow_MADE': 'sum', 
                                                            'FreeThrow_ATTEMPTS': 'sum', 'OFFENSIVE_REBOUNDS': 'sum', 
                                                            'DEFENSIVE_REBOUNDS': 'sum', 'REBOUNDS_TOTAL': 'sum', 'ASSISTS': 'sum',
                                                            'STEALS': 'sum', 'BLOCKS': 'sum', 'TURNOVERS': 'sum', 'PERSONAL_FOULS': 'sum', 
                                                            'POINTS': 'sum'}).reset_index()
by_player_15

,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,AJ Price,1610612754,IND,Indiana,201985,51.0,137.0,15.0,57.0,16.0,24.0,6.0,26.0,32.0,46.0,7.0,0.0,14.0,15.0,133.0
1,Aaron Brooks,1610612741,CHI,Chicago,201166,344.0,817.0,121.0,313.0,145.0,174.0,32.0,134.0,166.0,261.0,54.0,15.0,157.0,189.0,954.0
2,Aaron Gordon,1610612753,ORL,Orlando,203932,93.0,208.0,13.0,48.0,44.0,61.0,46.0,123.0,169.0,33.0,21.0,22.0,38.0,83.0,243.0
3,Adreian Payne,1610612737,ATL,Atlanta,203940,91.0,220.0,1.0,9.0,30.0,46.0,48.0,114.0,162.0,30.0,19.0,9.0,44.0,88.0,213.0
4,Al Horford,1610612737,ATL,Atlanta,201143,519.0,965.0,11.0,36.0,107.0,141.0,131.0,413.0,544.0,244.0,68.0,98.0,100.0,121.0,1156.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
487,Xavier Henry,1610612747,LAL,Los Angeles,202333,3.0,13.0,0.0,0.0,14.0,24.0,2.0,2.0,4.0,3.0,3.0,0.0,3.0,6.0,20.0
488,Zach LaVine,1610612750,MIN,Minnesota,203897,286.0,677.0,57.0,167.0,149.0,177.0,27.0,187.0,214.0,276.0,54.0,10.0,193.0,158.0,778.0
489,Zach Randolph,1610612763,MEM,Memphis,2216,454.0,932.0,7.0,20.0,228.0,298.0,225.0,522.0,747.0,153.0,69.0,14.0,156.0,175.0,1143.0
490,Zaza Pachulia,1610612749,MIL,Milwaukee,2585,240.0,529.0,0.0,3.0,126.0,160.0,197.0,303.0,500.0,178.0,80.0,21.0,133.0,170.0,606.0
491,Zoran Dragic,1610612756,PHX,Phoenix,204054,11.0,30.0,3.0,14.0,3.0,5.0,5.0,3.0,8.0,5.0,2.0,0.0,5.0,6.0,28.0

In [147]:
filtered_16 = Season_16[['TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_CITY', 'PLAYER_ID', 'PLAYER_NAME', '2pointer_MADE', '2pointer_ATTEMPTS',
                        '3pointer_MADE', '3pointer_ATTEMPTS', 'FreeThrow_MADE', 'FreeThrow_ATTEMPTS', 'OFFENSIVE_REBOUNDS', 
                         'DEFENSIVE_REBOUNDS', 'REBOUNDS_TOTAL', 'ASSISTS','STEALS', 'BLOCKS', 'TURNOVERS', 'PERSONAL_FOULS', 'POINTS']]
filtered_16

,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
420940,1610612758,SAC,Sacramento,202341,James Anderson,5.0,12.0,1.0,5.0,2.0,6.0,1.0,3.0,4.0,5.0,3.0,0.0,6.0,3.0,13.0
420941,1610612758,SAC,Sacramento,201585,Kosta Koufos,6.0,13.0,0.0,0.0,0.0,0.0,4.0,7.0,11.0,1.0,1.0,2.0,0.0,3.0,12.0
420942,1610612758,SAC,Sacramento,1626161,Willie Cauley-Stein,3.0,10.0,0.0,0.0,0.0,0.0,3.0,5.0,8.0,3.0,2.0,1.0,2.0,5.0,6.0
420943,1610612758,SAC,Sacramento,203463,Ben McLemore,10.0,20.0,4.0,9.0,0.0,0.0,2.0,3.0,5.0,3.0,2.0,0.0,3.0,2.0,24.0
420944,1610612758,SAC,Sacramento,203552,Seth Curry,3.0,18.0,3.0,12.0,1.0,1.0,1.0,5.0,6.0,5.0,0.0,0.0,5.0,1.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447013,1610612744,GSW,Golden State,203105,Festus Ezeli,6.0,10.0,0.0,0.0,1.0,2.0,3.0,1.0,4.0,1.0,1.0,1.0,1.0,2.0,13.0
447014,1610612744,GSW,Golden State,203949,James Michael McAdoo,0.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,4.0,2.0
447015,1610612744,GSW,Golden State,201578,Marreese Speights,2.0,7.0,1.0,1.0,4.0,4.0,4.0,1.0,5.0,1.0,0.0,1.0,2.0,1.0,9.0
447016,1610612744,GSW,Golden State,2733,Shaun Livingston,3.0,6.0,0.0,2.0,0.0,0.0,0.0,3.0,3.0,2.0,0.0,1.0,0.0,1.0,6.0
447017,1610612744,GSW,Golden State,201575,Brandon Rush,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [148]:
by_player_16 = filtered_16.groupby(['PLAYER_NAME']).agg({'TEAM_ID': 'last', 'TEAM_ABBREVIATION': 'last', 'TEAM_CITY': 'last', 'PLAYER_ID': 'last',
                                                            '2pointer_MADE': 'sum', '2pointer_ATTEMPTS': 'sum',
                                                            '3pointer_MADE': 'sum', '3pointer_ATTEMPTS': 'sum', 'FreeThrow_MADE': 'sum', 
                                                            'FreeThrow_ATTEMPTS': 'sum', 'OFFENSIVE_REBOUNDS': 'sum', 
                                                            'DEFENSIVE_REBOUNDS': 'sum', 'REBOUNDS_TOTAL': 'sum', 'ASSISTS': 'sum',
                                                            'STEALS': 'sum', 'BLOCKS': 'sum', 'TURNOVERS': 'sum', 'PERSONAL_FOULS': 'sum', 
                                                            'POINTS': 'sum'}).reset_index()
by_player_16

,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,Aaron Brooks,1610612741,CHI,Chicago,201166,188.0,469.0,66.0,185.0,49.0,64.0,21.0,80.0,101.0,180.0,30.0,10.0,82.0,132.0,491.0
1,Aaron Gordon,1610612753,ORL,Orlando,203932,274.0,579.0,42.0,142.0,129.0,193.0,154.0,353.0,507.0,128.0,59.0,55.0,66.0,153.0,719.0
2,Aaron Harrison,1610612766,CHA,Charlotte,1626151,5.0,19.0,3.0,10.0,5.0,12.0,4.0,11.0,15.0,2.0,6.0,0.0,4.0,10.0,18.0
3,Adreian Payne,1610612750,MIN,Minnesota,203940,53.0,145.0,9.0,32.0,17.0,26.0,20.0,91.0,111.0,29.0,16.0,11.0,36.0,77.0,132.0
4,Al Horford,1610612737,ATL,Atlanta,201143,529.0,1048.0,88.0,256.0,103.0,129.0,148.0,448.0,596.0,263.0,68.0,121.0,107.0,163.0,1249.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
471,Willie Reed,1610612751,BKN,Brooklyn,203186,76.0,133.0,0.0,0.0,30.0,55.0,49.0,73.0,122.0,10.0,6.0,30.0,16.0,47.0,182.0
472,Xavier Munford,1610612763,MEM,Memphis,204098,32.0,77.0,9.0,23.0,7.0,14.0,3.0,28.0,31.0,22.0,13.0,3.0,15.0,25.0,80.0
473,Zach LaVine,1610612750,MIN,Minnesota,203897,433.0,959.0,123.0,316.0,161.0,203.0,27.0,201.0,228.0,251.0,69.0,17.0,155.0,193.0,1150.0
474,Zach Randolph,1610612763,MEM,Memphis,2216,431.0,907.0,6.0,26.0,172.0,216.0,179.0,350.0,529.0,142.0,43.0,13.0,105.0,146.0,1040.0
475,Zaza Pachulia,1610612742,DAL,Dallas,2585,219.0,470.0,0.0,3.0,212.0,276.0,249.0,469.0,718.0,128.0,64.0,22.0,119.0,181.0,650.0

In [149]:
filtered_17 = Season_17[['TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_CITY', 'PLAYER_ID', 'PLAYER_NAME', '2pointer_MADE', '2pointer_ATTEMPTS',
                        '3pointer_MADE', '3pointer_ATTEMPTS', 'FreeThrow_MADE', 'FreeThrow_ATTEMPTS', 'OFFENSIVE_REBOUNDS', 
                         'DEFENSIVE_REBOUNDS', 'REBOUNDS_TOTAL', 'ASSISTS','STEALS', 'BLOCKS', 'TURNOVERS', 'PERSONAL_FOULS', 'POINTS']]
filtered_17

,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
390361,1610612750,MIN,Minnesota,203952,Andrew Wiggins,7.0,17.0,2.0,5.0,5.0,7.0,0.0,2.0,2.0,3.0,1.0,0.0,4.0,2.0,21.0
390362,1610612750,MIN,Minnesota,203476,Gorgui Dieng,3.0,8.0,0.0,0.0,0.0,0.0,3.0,5.0,8.0,2.0,0.0,0.0,3.0,2.0,6.0
390363,1610612750,MIN,Minnesota,1626157,Karl-Anthony Towns,12.0,17.0,3.0,4.0,1.0,1.0,1.0,20.0,21.0,3.0,1.0,0.0,0.0,2.0,28.0
390364,1610612750,MIN,Minnesota,201575,Brandon Rush,3.0,3.0,2.0,2.0,0.0,0.0,1.0,1.0,2.0,2.0,0.0,0.0,2.0,0.0,8.0
390365,1610612750,MIN,Minnesota,1627739,Kris Dunn,5.0,13.0,0.0,2.0,0.0,0.0,0.0,2.0,2.0,16.0,1.0,2.0,3.0,4.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
416495,1610612744,GSW,Golden State,2733,Shaun Livingston,1.0,3.0,0.0,1.0,0.0,0.0,0.0,2.0,2.0,0.0,1.0,0.0,1.0,0.0,2.0
416496,1610612744,GSW,Golden State,1627775,Patrick McCaw,1.0,3.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,1.0,0.0,0.0,2.0
416497,1610612744,GSW,Golden State,2760,Anderson Varejao,0.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,1.0
416498,1610612744,GSW,Golden State,201580,JaVale McGee,1.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
416499,1610612744,GSW,Golden State,1626172,Kevon Looney,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [150]:
by_player_17 = filtered_17.groupby(['PLAYER_NAME']).agg({'TEAM_ID': 'last', 'TEAM_ABBREVIATION': 'last', 'TEAM_CITY': 'last', 'PLAYER_ID': 'last',
                                                            '2pointer_MADE': 'sum', '2pointer_ATTEMPTS': 'sum',
                                                            '3pointer_MADE': 'sum', '3pointer_ATTEMPTS': 'sum', 'FreeThrow_MADE': 'sum', 
                                                            'FreeThrow_ATTEMPTS': 'sum', 'OFFENSIVE_REBOUNDS': 'sum', 
                                                            'DEFENSIVE_REBOUNDS': 'sum', 'REBOUNDS_TOTAL': 'sum', 'ASSISTS': 'sum',
                                                            'STEALS': 'sum', 'BLOCKS': 'sum', 'TURNOVERS': 'sum', 'PERSONAL_FOULS': 'sum', 
                                                            'POINTS': 'sum'}).reset_index()
by_player_17

,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,AJ Hammons,1610612742,DAL,Dallas,1627773,17.0,42.0,5.0,10.0,9.0,20.0,8.0,28.0,36.0,4.0,1.0,13.0,10.0,21.0,48.0
1,Aaron Brooks,1610612754,IND,Indiana,201166,121.0,300.0,48.0,128.0,32.0,40.0,18.0,51.0,69.0,125.0,25.0,9.0,66.0,93.0,322.0
2,Aaron Gordon,1610612753,ORL,Orlando,203932,393.0,865.0,77.0,267.0,156.0,217.0,116.0,289.0,405.0,150.0,65.0,40.0,89.0,172.0,1019.0
3,Aaron Harrison,1610612766,CHA,Charlotte,1626151,0.0,4.0,0.0,2.0,1.0,2.0,0.0,3.0,3.0,3.0,0.0,0.0,0.0,2.0,1.0
4,Adreian Payne,1610612750,MIN,Minnesota,203940,23.0,54.0,3.0,15.0,14.0,19.0,9.0,24.0,33.0,7.0,8.0,7.0,8.0,32.0,63.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
481,Wilson Chandler,1610612743,DEN,Denver,201163,433.0,939.0,110.0,326.0,141.0,194.0,103.0,357.0,460.0,141.0,51.0,30.0,114.0,172.0,1117.0
482,Yogi Ferrell,1610612751,BKN,Brooklyn,1627812,160.0,394.0,68.0,176.0,74.0,89.0,20.0,91.0,111.0,172.0,42.0,9.0,70.0,90.0,462.0
483,Zach LaVine,1610612750,MIN,Minnesota,203897,326.0,710.0,120.0,310.0,117.0,140.0,19.0,141.0,160.0,139.0,41.0,10.0,85.0,104.0,889.0
484,Zach Randolph,1610612763,MEM,Memphis,2216,433.0,964.0,21.0,94.0,141.0,193.0,182.0,416.0,598.0,122.0,38.0,10.0,99.0,136.0,1028.0
485,Zaza Pachulia,1610612744,GSW,Golden State,2585,164.0,307.0,0.0,2.0,98.0,126.0,140.0,270.0,410.0,132.0,59.0,33.0,87.0,166.0,426.0

In [151]:
filtered_18 = Season_18[['TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_CITY', 'PLAYER_ID', 'PLAYER_NAME', '2pointer_MADE', '2pointer_ATTEMPTS',
                        '3pointer_MADE', '3pointer_ATTEMPTS', 'FreeThrow_MADE', 'FreeThrow_ATTEMPTS', 'OFFENSIVE_REBOUNDS', 
                         'DEFENSIVE_REBOUNDS', 'REBOUNDS_TOTAL', 'ASSISTS','STEALS', 'BLOCKS', 'TURNOVERS', 'PERSONAL_FOULS', 'POINTS']]
filtered_18

,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
360413,1610612754,IND,Indiana,202711,Bojan Bogdanovic,5.0,17.0,1.0,6.0,4.0,4.0,0.0,6.0,6.0,1.0,3.0,0.0,1.0,3.0,15.0
360414,1610612754,IND,Indiana,201152,Thaddeus Young,3.0,4.0,0.0,0.0,1.0,2.0,2.0,1.0,3.0,1.0,0.0,1.0,0.0,0.0,7.0
360415,1610612754,IND,Indiana,1626167,Myles Turner,6.0,9.0,1.0,2.0,3.0,4.0,1.0,7.0,8.0,2.0,0.0,1.0,1.0,3.0,16.0
360416,1610612754,IND,Indiana,203506,Victor Oladipo,11.0,19.0,6.0,9.0,4.0,8.0,0.0,6.0,6.0,4.0,4.0,1.0,4.0,3.0,32.0
360417,1610612754,IND,Indiana,201954,Darren Collison,2.0,9.0,1.0,4.0,1.0,2.0,1.0,4.0,5.0,6.0,2.0,0.0,2.0,0.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
386686,1610612744,GSW,Golden State,201156,Nick Young,8.0,9.0,6.0,7.0,1.0,1.0,1.0,1.0,2.0,0.0,0.0,0.0,1.0,4.0,23.0
386687,1610612744,GSW,Golden State,2733,Shaun Livingston,2.0,5.0,0.0,0.0,2.0,2.0,1.0,0.0,1.0,5.0,0.0,0.0,1.0,2.0,6.0
386688,1610612744,GSW,Golden State,201956,Omri Casspi,0.0,0.0,0.0,0.0,2.0,2.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0
386689,1610612744,GSW,Golden State,1626172,Kevon Looney,0.0,0.0,0.0,0.0,1.0,2.0,0.0,2.0,2.0,0.0,1.0,0.0,0.0,2.0,1.0
386690,1610612744,GSW,Golden State,2561,David West,2.0,3.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,4.0

In [152]:
by_player_18 = filtered_18.groupby(['PLAYER_NAME']).agg({'TEAM_ID': 'last', 'TEAM_ABBREVIATION': 'last', 'TEAM_CITY': 'last', 'PLAYER_ID': 'last',
                                                            '2pointer_MADE': 'sum', '2pointer_ATTEMPTS': 'sum',
                                                            '3pointer_MADE': 'sum', '3pointer_ATTEMPTS': 'sum', 'FreeThrow_MADE': 'sum', 
                                                            'FreeThrow_ATTEMPTS': 'sum', 'OFFENSIVE_REBOUNDS': 'sum', 
                                                            'DEFENSIVE_REBOUNDS': 'sum', 'REBOUNDS_TOTAL': 'sum', 'ASSISTS': 'sum',
                                                            'STEALS': 'sum', 'BLOCKS': 'sum', 'TURNOVERS': 'sum', 'PERSONAL_FOULS': 'sum', 
                                                            'POINTS': 'sum'}).reset_index()
by_player_18

,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,Aaron Brooks,1610612750,MIN,Minnesota,201166,28.0,69.0,11.0,31.0,8.0,11.0,7.0,10.0,17.0,20.0,6.0,0.0,11.0,28.0,75.0
1,Aaron Gordon,1610612753,ORL,Orlando,203932,375.0,865.0,115.0,342.0,157.0,225.0,87.0,370.0,457.0,136.0,59.0,45.0,107.0,111.0,1022.0
2,Aaron Harrison,1610612742,DAL,Dallas,1626151,19.0,69.0,9.0,43.0,13.0,17.0,4.0,20.0,24.0,11.0,9.0,2.0,3.0,27.0,60.0
3,Aaron Jackson,1610612745,HOU,Houston,1628935,3.0,9.0,1.0,4.0,1.0,2.0,2.0,1.0,3.0,1.0,0.0,0.0,1.0,4.0,8.0
4,Abdel Nader,1610612738,BOS,Boston,1627846,50.0,149.0,23.0,65.0,23.0,39.0,13.0,58.0,71.0,26.0,15.0,10.0,34.0,45.0,146.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
535,Zach Collins,1610612757,POR,Portland,1628380,118.0,297.0,36.0,117.0,28.0,44.0,45.0,178.0,223.0,55.0,19.0,32.0,58.0,134.0,300.0
536,Zach LaVine,1610612741,CHI,Chicago,203897,136.0,355.0,42.0,123.0,87.0,107.0,9.0,85.0,94.0,72.0,24.0,4.0,43.0,55.0,401.0
537,Zach Randolph,1610612758,SAC,Sacramento,2216,361.0,763.0,51.0,147.0,84.0,107.0,97.0,300.0,397.0,127.0,42.0,10.0,116.0,119.0,857.0
538,Zaza Pachulia,1610612744,GSW,Golden State,2585,149.0,264.0,0.0,1.0,75.0,93.0,89.0,232.0,321.0,109.0,38.0,17.0,72.0,122.0,373.0
539,Zhou Qi,1610612745,HOU,Houston,1627753,6.0,32.0,2.0,19.0,8.0,12.0,6.0,16.0,22.0,2.0,2.0,14.0,10.0,14.0,22.0

In [153]:
filtered_19 = Season_19[['TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_CITY', 'PLAYER_ID', 'PLAYER_NAME', '2pointer_MADE', '2pointer_ATTEMPTS',
                        '3pointer_MADE', '3pointer_ATTEMPTS', 'FreeThrow_MADE', 'FreeThrow_ATTEMPTS', 'OFFENSIVE_REBOUNDS', 
                         'DEFENSIVE_REBOUNDS', 'REBOUNDS_TOTAL', 'ASSISTS','STEALS', 'BLOCKS', 'TURNOVERS', 'PERSONAL_FOULS', 'POINTS']]
filtered_19

,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
330918,1610612754,IND,Indiana,203926,Doug McDermott,4.0,12.0,2.0,3.0,3.0,3.0,1.0,4.0,5.0,2.0,1.0,0.0,0.0,2.0,13.0
330919,1610612754,IND,Indiana,1628388,TJ Leaf,12.0,19.0,0.0,2.0,4.0,5.0,5.0,5.0,10.0,2.0,2.0,2.0,0.0,2.0,28.0
330920,1610612754,IND,Indiana,203124,Kyle O'Quinn,2.0,5.0,0.0,0.0,2.0,2.0,0.0,2.0,2.0,2.0,0.0,2.0,1.0,2.0,6.0
330921,1610612754,IND,Indiana,201936,Tyreke Evans,9.0,14.0,5.0,8.0,4.0,5.0,0.0,2.0,2.0,5.0,0.0,0.0,3.0,4.0,27.0
330922,1610612754,IND,Indiana,201954,Darren Collison,1.0,3.0,0.0,1.0,4.0,4.0,0.0,1.0,1.0,4.0,1.0,0.0,1.0,3.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357014,1610612744,GSW,Golden State,1626188,Quinn Cook,1.0,2.0,1.0,1.0,0.0,0.0,1.0,1.0,2.0,1.0,0.0,0.0,2.0,2.0,3.0
357015,1610612744,GSW,Golden State,2733,Shaun Livingston,3.0,5.0,0.0,0.0,0.0,0.0,2.0,1.0,3.0,1.0,1.0,0.0,1.0,2.0,6.0
357016,1610612744,GSW,Golden State,1628395,Jordan Bell,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,0.0,0.0,1.0,0.0,1.0,0.0
357017,1610612744,GSW,Golden State,1628035,Alfonzo McKinnie,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
357018,1610612744,GSW,Golden State,201973,Jonas Jerebko,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,3.0,0.0,0.0,0.0,1.0,2.0,0.0

In [154]:
by_player_19 = filtered_19.groupby(['PLAYER_NAME']).agg({'TEAM_ID': 'last', 'TEAM_ABBREVIATION': 'last', 'TEAM_CITY': 'last', 'PLAYER_ID': 'last',
                                                            '2pointer_MADE': 'sum', '2pointer_ATTEMPTS': 'sum',
                                                            '3pointer_MADE': 'sum', '3pointer_ATTEMPTS': 'sum', 'FreeThrow_MADE': 'sum', 
                                                            'FreeThrow_ATTEMPTS': 'sum', 'OFFENSIVE_REBOUNDS': 'sum', 
                                                            'DEFENSIVE_REBOUNDS': 'sum', 'REBOUNDS_TOTAL': 'sum', 'ASSISTS': 'sum',
                                                            'STEALS': 'sum', 'BLOCKS': 'sum', 'TURNOVERS': 'sum', 'PERSONAL_FOULS': 'sum', 
                                                            'POINTS': 'sum'}).reset_index()
by_player_19

,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,Aaron Gordon,1610612753,ORL,Orlando,203932,470.0,1046.0,121.0,347.0,185.0,253.0,129.0,445.0,574.0,289.0,57.0,56.0,162.0,172.0,1246.0
1,Aaron Holiday,1610612754,IND,Indiana,1628988,105.0,262.0,43.0,127.0,41.0,50.0,5.0,62.0,67.0,87.0,21.0,13.0,40.0,71.0,294.0
2,Abdel Nader,1610612760,OKC,Oklahoma City,1627846,91.0,215.0,32.0,100.0,27.0,36.0,14.0,102.0,116.0,20.0,20.0,12.0,26.0,68.0,241.0
3,Al Horford,1610612738,BOS,Boston,201143,387.0,723.0,73.0,203.0,78.0,95.0,120.0,338.0,458.0,283.0,59.0,86.0,102.0,126.0,925.0
4,Al-Farouq Aminu,1610612757,POR,Portland,202329,257.0,593.0,96.0,280.0,150.0,173.0,112.0,498.0,610.0,104.0,68.0,33.0,72.0,143.0,760.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
525,Zach LaVine,1610612741,CHI,Chicago,203897,530.0,1135.0,120.0,321.0,312.0,375.0,40.0,254.0,294.0,283.0,60.0,26.0,215.0,140.0,1492.0
526,Zach Lofton,1610612765,DET,Detroit,1629155,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
527,Zaza Pachulia,1610612765,DET,Detroit,2585,85.0,193.0,0.0,4.0,97.0,124.0,99.0,166.0,265.0,91.0,31.0,17.0,57.0,151.0,267.0
528,Zhaire Smith,1610612755,PHI,Philadelphia,1629015,14.0,34.0,6.0,16.0,6.0,8.0,3.0,10.0,13.0,10.0,2.0,2.0,6.0,8.0,40.0
529,Zhou Qi,1610612745,HOU,Houston,1627753,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0

In [155]:
filtered_20 = Season_20[['TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_CITY', 'PLAYER_ID', 'PLAYER_NAME', '2pointer_MADE', '2pointer_ATTEMPTS',
                        '3pointer_MADE', '3pointer_ATTEMPTS', 'FreeThrow_MADE', 'FreeThrow_ATTEMPTS', 'OFFENSIVE_REBOUNDS', 
                         'DEFENSIVE_REBOUNDS', 'REBOUNDS_TOTAL', 'ASSISTS','STEALS', 'BLOCKS', 'TURNOVERS', 'PERSONAL_FOULS', 'POINTS']]
filtered_20

,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
51642,1610612763,MEM,Memphis,203937,Kyle Anderson,4.0,6.0,1.0,1.0,1.0,1.0,1.0,5.0,6.0,9.0,2.0,1.0,6.0,3.0,10.0
51643,1610612763,MEM,Memphis,201229,Anthony Tolliver,2.0,4.0,1.0,2.0,2.0,2.0,1.0,2.0,3.0,0.0,0.0,1.0,0.0,6.0,7.0
51644,1610612763,MEM,Memphis,202685,Jonas Valanciunas,8.0,16.0,0.0,4.0,6.0,6.0,4.0,13.0,17.0,6.0,0.0,0.0,1.0,3.0,22.0
51645,1610612763,MEM,Memphis,1628415,Dillon Brooks,7.0,18.0,4.0,5.0,2.0,3.0,1.0,1.0,2.0,2.0,1.0,0.0,0.0,3.0,20.0
51646,1610612763,MEM,Memphis,1629630,Ja Morant,13.0,28.0,3.0,6.0,6.0,8.0,1.0,3.0,4.0,8.0,0.0,0.0,8.0,1.0,35.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
327314,1610612761,TOR,Toronto,200768,Kyle Lowry,4.0,15.0,3.0,11.0,11.0,13.0,1.0,4.0,5.0,6.0,2.0,0.0,4.0,4.0,22.0
327315,1610612761,TOR,Toronto,1627832,Fred VanVleet,12.0,18.0,5.0,7.0,5.0,6.0,0.0,5.0,5.0,7.0,2.0,0.0,2.0,0.0,34.0
327316,1610612761,TOR,Toronto,201586,Serge Ibaka,4.0,10.0,0.0,1.0,5.0,6.0,2.0,3.0,5.0,0.0,1.0,0.0,3.0,2.0,13.0
327317,1610612761,TOR,Toronto,1626181,Norman Powell,2.0,7.0,1.0,5.0,0.0,0.0,1.0,7.0,8.0,2.0,0.0,0.0,2.0,2.0,5.0
327318,1610612761,TOR,Toronto,1629056,Terence Davis,2.0,6.0,1.0,3.0,0.0,0.0,2.0,3.0,5.0,2.0,2.0,0.0,0.0,2.0,5.0

In [156]:
by_player_20 = filtered_20.groupby(['PLAYER_NAME']).agg({'TEAM_ID': 'last', 'TEAM_ABBREVIATION': 'last', 'TEAM_CITY': 'last', 'PLAYER_ID': 'last',
                                                            '2pointer_MADE': 'sum', '2pointer_ATTEMPTS': 'sum',
                                                            '3pointer_MADE': 'sum', '3pointer_ATTEMPTS': 'sum', 'FreeThrow_MADE': 'sum', 
                                                            'FreeThrow_ATTEMPTS': 'sum', 'OFFENSIVE_REBOUNDS': 'sum', 
                                                            'DEFENSIVE_REBOUNDS': 'sum', 'REBOUNDS_TOTAL': 'sum', 'ASSISTS': 'sum',
                                                            'STEALS': 'sum', 'BLOCKS': 'sum', 'TURNOVERS': 'sum', 'PERSONAL_FOULS': 'sum', 
                                                            'POINTS': 'sum'}).reset_index()
by_player_20

,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,Aaron Gordon,1610612753,ORL,Orlando,203932,345.0,789.0,76.0,245.0,155.0,230.0,107.0,375.0,482.0,232.0,52.0,40.0,101.0,129.0,921.0
1,Aaron Holiday,1610612754,IND,Indiana,1628988,245.0,595.0,89.0,234.0,77.0,90.0,24.0,137.0,161.0,228.0,58.0,17.0,94.0,125.0,656.0
2,Abdel Nader,1610612760,OKC,Oklahoma City,1627846,131.0,280.0,52.0,137.0,53.0,69.0,15.0,90.0,105.0,39.0,23.0,21.0,44.0,79.0,367.0
3,Adam Mokoka,1610612741,CHI,Chicago,1629690,12.0,28.0,6.0,15.0,2.0,4.0,7.0,3.0,10.0,4.0,4.0,0.0,2.0,17.0,32.0
4,Admiral Schofield,1610612764,WAS,Washington,1629678,38.0,106.0,20.0,69.0,11.0,17.0,13.0,43.0,56.0,16.0,9.0,4.0,10.0,60.0,107.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
526,Zach LaVine,1610612741,CHI,Chicago,203897,539.0,1199.0,184.0,484.0,268.0,334.0,41.0,248.0,289.0,254.0,88.0,28.0,206.0,131.0,1530.0
527,Zach Norvell Jr.,1610612747,LAL,Los Angeles,1629668,3.0,12.0,3.0,8.0,1.0,1.0,0.0,6.0,6.0,3.0,2.0,0.0,3.0,4.0,10.0
528,Zhaire Smith,1610612755,PHI,Philadelphia,1629015,3.0,11.0,0.0,3.0,2.0,4.0,0.0,2.0,2.0,2.0,3.0,0.0,2.0,4.0,8.0
529,Zion Williamson,1610612740,NOP,New Orleans,1629627,210.0,360.0,6.0,14.0,114.0,178.0,64.0,86.0,150.0,50.0,16.0,9.0,59.0,42.0,540.0
530,Zylan Cheatham,1610612740,NOP,New Orleans,1629597,11.0,16.0,0.0,2.0,5.0,8.0,5.0,14.0,19.0,3.0,1.0,1.0,6.0,13.0,27.0

In [157]:
filtered_21 = Season_21[['TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_CITY', 'PLAYER_ID', 'PLAYER_NAME', '2pointer_MADE', '2pointer_ATTEMPTS',
                        '3pointer_MADE', '3pointer_ATTEMPTS', 'FreeThrow_MADE', 'FreeThrow_ATTEMPTS', 'OFFENSIVE_REBOUNDS', 
                         'DEFENSIVE_REBOUNDS', 'REBOUNDS_TOTAL', 'ASSISTS','STEALS', 'BLOCKS', 'TURNOVERS', 'PERSONAL_FOULS', 'POINTS']]
filtered_21

,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
25155,1610612763,MEM,Memphis,203937,Kyle Anderson,2.0,7.0,0.0,1.0,5.0,5.0,2.0,8.0,10.0,6.0,1.0,2.0,0.0,1.0,9.0
25156,1610612763,MEM,Memphis,1628991,Jaren Jackson Jr.,1.0,6.0,1.0,4.0,7.0,8.0,2.0,0.0,2.0,0.0,0.0,2.0,1.0,4.0,10.0
25157,1610612763,MEM,Memphis,202685,Jonas Valanciunas,3.0,6.0,1.0,1.0,2.0,4.0,6.0,6.0,12.0,3.0,0.0,0.0,3.0,6.0,9.0
25158,1610612763,MEM,Memphis,1628415,Dillon Brooks,7.0,22.0,0.0,4.0,0.0,0.0,1.0,1.0,2.0,3.0,2.0,0.0,1.0,5.0,14.0
25159,1610612763,MEM,Memphis,1629630,Ja Morant,14.0,29.0,5.0,10.0,2.0,2.0,2.0,4.0,6.0,6.0,4.0,0.0,5.0,2.0,35.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48608,1610612746,LAC,LA,1628379,Luke Kennard,2.0,6.0,0.0,3.0,0.0,0.0,0.0,2.0,2.0,2.0,2.0,1.0,1.0,3.0,4.0
48609,1610612747,LAL,Los Angeles,203484,Kentavious Caldwell-Pope,2.0,4.0,1.0,3.0,4.0,4.0,0.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,9.0
48610,1610612747,LAL,Los Angeles,203471,Dennis Schroder,5.0,15.0,2.0,5.0,2.0,4.0,1.0,11.0,12.0,8.0,0.0,0.0,1.0,4.0,14.0
48611,1610612747,LAL,Los Angeles,1628398,Kyle Kuzma,6.0,11.0,1.0,3.0,2.0,2.0,0.0,1.0,1.0,0.0,0.0,0.0,2.0,2.0,15.0
48612,1610612747,LAL,Los Angeles,202693,Markieff Morris,1.0,3.0,1.0,2.0,2.0,3.0,1.0,3.0,4.0,1.0,0.0,0.0,0.0,0.0,5.0

In [158]:
by_player_21 = filtered_21.groupby(['PLAYER_NAME']).agg({'TEAM_ID': 'last', 'TEAM_ABBREVIATION': 'last', 'TEAM_CITY': 'last', 'PLAYER_ID': 'last',
                                                            '2pointer_MADE': 'sum', '2pointer_ATTEMPTS': 'sum',
                                                            '3pointer_MADE': 'sum', '3pointer_ATTEMPTS': 'sum', 'FreeThrow_MADE': 'sum', 
                                                            'FreeThrow_ATTEMPTS': 'sum', 'OFFENSIVE_REBOUNDS': 'sum', 
                                                            'DEFENSIVE_REBOUNDS': 'sum', 'REBOUNDS_TOTAL': 'sum', 'ASSISTS': 'sum',
                                                            'STEALS': 'sum', 'BLOCKS': 'sum', 'TURNOVERS': 'sum', 'PERSONAL_FOULS': 'sum', 
                                                            'POINTS': 'sum'}).reset_index()
by_player_21

,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,Aaron Gordon,1610612753,ORL,Orlando,203932,231.0,499.0,59.0,176.0,97.0,149.0,77.0,207.0,284.0,161.0,33.0,34.0,97.0,89.0,618.0
1,Aaron Holiday,1610612754,IND,Indiana,1628988,173.0,447.0,68.0,186.0,70.0,85.0,15.0,78.0,93.0,128.0,48.0,13.0,68.0,98.0,484.0
2,Aaron Nesmith,1610612738,BOS,Boston,1630174,79.0,182.0,41.0,112.0,22.0,28.0,29.0,101.0,130.0,23.0,16.0,10.0,24.0,88.0,221.0
3,Abdel Nader,1610612756,PHX,Phoenix,1627846,57.0,116.0,18.0,43.0,28.0,37.0,7.0,55.0,62.0,19.0,10.0,9.0,19.0,34.0,160.0
4,Adam Mokoka,1610612741,CHI,Chicago,1629690,9.0,25.0,1.0,13.0,0.0,1.0,2.0,5.0,7.0,7.0,3.0,2.0,5.0,6.0,19.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
535,Yogi Ferrell,1610612739,CLE,Cleveland,1627812,20.0,57.0,9.0,28.0,7.0,9.0,5.0,14.0,19.0,22.0,7.0,3.0,3.0,11.0,56.0
536,Yuta Watanabe,1610612761,TOR,Toronto,1629139,79.0,180.0,36.0,90.0,24.0,29.0,36.0,123.0,159.0,40.0,26.0,19.0,19.0,57.0,218.0
537,Zach LaVine,1610612741,CHI,Chicago,203897,587.0,1162.0,205.0,493.0,261.0,308.0,36.0,266.0,302.0,287.0,49.0,30.0,215.0,141.0,1640.0
538,Zeke Nnaji,1610612743,DEN,Denver,1630192,50.0,104.0,24.0,59.0,12.0,15.0,14.0,51.0,65.0,10.0,8.0,4.0,7.0,29.0,136.0
539,Zion Williamson,1610612740,NOP,New Orleans,1629627,643.0,1050.0,10.0,34.0,371.0,535.0,168.0,275.0,443.0,226.0,58.0,39.0,168.0,136.0,1667.0

# Group playoff data by PLAYER_NAME

In [159]:
filtered_playoffs_04 = Playoffs_04[['TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_CITY', 'PLAYER_ID', 'PLAYER_NAME', '2pointer_MADE', '2pointer_ATTEMPTS',
                        '3pointer_MADE', '3pointer_ATTEMPTS', 'FreeThrow_MADE', 'FreeThrow_ATTEMPTS', 'OFFENSIVE_REBOUNDS', 
                         'DEFENSIVE_REBOUNDS', 'REBOUNDS_TOTAL', 'ASSISTS','STEALS', 'BLOCKS', 'TURNOVERS', 'PERSONAL_FOULS', 'POINTS']]
filtered_playoffs_04

,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
213209,1610612747,LAL,Los Angeles,1904,Devean George,2.0,6.0,0.0,2.0,0.0,0.0,2.0,1.0,3.0,2.0,0.0,1.0,0.0,4.0,4.0
213210,1610612747,LAL,Los Angeles,2098,Slava Medvedenko,4.0,8.0,0.0,0.0,2.0,2.0,2.0,3.0,5.0,1.0,0.0,0.0,1.0,1.0,10.0
213211,1610612747,LAL,Los Angeles,406,Shaquille O'Neal,7.0,13.0,0.0,0.0,6.0,16.0,2.0,6.0,8.0,1.0,1.0,0.0,1.0,4.0,20.0
213212,1610612747,LAL,Los Angeles,977,Kobe Bryant,7.0,21.0,0.0,2.0,10.0,11.0,1.0,2.0,3.0,4.0,1.0,0.0,3.0,2.0,24.0
213213,1610612747,LAL,Los Angeles,56,Gary Payton,1.0,3.0,0.0,1.0,0.0,0.0,2.0,2.0,4.0,4.0,2.0,1.0,1.0,2.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214858,1610612754,IND,Indiana,2224,Jamaal Tinsley,2.0,6.0,1.0,4.0,0.0,0.0,1.0,2.0,3.0,7.0,1.0,1.0,0.0,3.0,5.0
214859,1610612754,IND,Indiana,1733,Al Harrington,6.0,10.0,0.0,0.0,2.0,3.0,6.0,4.0,10.0,3.0,5.0,1.0,2.0,3.0,14.0
214860,1610612754,IND,Indiana,2410,Fred Jones,4.0,5.0,1.0,1.0,0.0,1.0,1.0,3.0,4.0,2.0,0.0,1.0,1.0,2.0,9.0
214861,1610612754,IND,Indiana,1533,Anthony Johnson,2.0,5.0,0.0,0.0,2.0,2.0,0.0,1.0,1.0,2.0,0.0,1.0,3.0,4.0,6.0
214862,1610612754,IND,Indiana,1886,Jonathan Bender,1.0,2.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0,3.0

In [160]:
playoffs_by_player_04 = filtered_playoffs_04.groupby(['PLAYER_NAME']).agg({'TEAM_ID': 'last', 'TEAM_ABBREVIATION': 'last', 'TEAM_CITY': 'last', 'PLAYER_ID': 'last',
                                                            '2pointer_MADE': 'sum', '2pointer_ATTEMPTS': 'sum',
                                                            '3pointer_MADE': 'sum', '3pointer_ATTEMPTS': 'sum', 'FreeThrow_MADE': 'sum', 
                                                            'FreeThrow_ATTEMPTS': 'sum', 'OFFENSIVE_REBOUNDS': 'sum', 
                                                            'DEFENSIVE_REBOUNDS': 'sum', 'REBOUNDS_TOTAL': 'sum', 'ASSISTS': 'sum',
                                                            'STEALS': 'sum', 'BLOCKS': 'sum', 'TURNOVERS': 'sum', 'PERSONAL_FOULS': 'sum', 
                                                            'POINTS': 'sum'}).reset_index()
playoffs_by_player_04

,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,Aaron Williams,1610612751,NJN,New Jersey,1425,18.0,33.0,0.0,0.0,6.0,10.0,7.0,15.0,22.0,4.0,0.0,7.0,15.0,41.0,42.0
1,Al Harrington,1610612754,IND,Indiana,1733,60.0,140.0,2.0,5.0,30.0,55.0,33.0,69.0,102.0,12.0,23.0,9.0,28.0,56.0,152.0
2,Andre Miller,1610612743,DEN,Denver,1889,34.0,72.0,0.0,2.0,9.0,11.0,15.0,8.0,23.0,16.0,8.0,0.0,10.0,16.0,77.0
3,Anfernee Hardaway,1610612752,NYK,New York,358,23.0,63.0,5.0,14.0,15.0,18.0,4.0,14.0,18.0,23.0,6.0,1.0,10.0,8.0,66.0
4,Antawn Jamison,1610612742,DAL,Dallas,1712,26.0,57.0,2.0,8.0,11.0,15.0,15.0,10.0,25.0,2.0,5.0,2.0,5.0,15.0,65.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,Wally Szczerbiak,1610612750,MIN,Minnesota,1887,47.0,112.0,10.0,29.0,38.0,41.0,9.0,30.0,39.0,20.0,6.0,2.0,24.0,31.0,142.0
185,Walter McCarty,1610612738,BOS,Boston,962,11.0,23.0,6.0,15.0,0.0,0.0,3.0,18.0,21.0,8.0,2.0,2.0,4.0,7.0,28.0
186,Wang Zhi-zhi,1610612748,MIA,Miami,1917,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
187,Yao Ming,1610612745,HOU,Houston,2397,31.0,68.0,0.0,0.0,13.0,17.0,11.0,26.0,37.0,9.0,2.0,7.0,13.0,20.0,75.0
188,Zoran Planinic,1610612751,NJN,New Jersey,2565,0.0,2.0,0.0,1.0,1.0,2.0,0.0,1.0,1.0,2.0,0.0,0.0,2.0,2.0,1.0

In [161]:
filtered_playoffs_05 = Playoffs_05[['TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_CITY', 'PLAYER_ID', 'PLAYER_NAME', '2pointer_MADE', '2pointer_ATTEMPTS',
                        '3pointer_MADE', '3pointer_ATTEMPTS', 'FreeThrow_MADE', 'FreeThrow_ATTEMPTS', 'OFFENSIVE_REBOUNDS', 
                         'DEFENSIVE_REBOUNDS', 'REBOUNDS_TOTAL', 'ASSISTS','STEALS', 'BLOCKS', 'TURNOVERS', 'PERSONAL_FOULS', 'POINTS']]
filtered_playoffs_05

,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
185478,1610612765,DET,Detroit,2419,Tayshaun Prince,4.0,13.0,1.0,4.0,0.0,0.0,1.0,1.0,2.0,1.0,2.0,0.0,1.0,1.0,9.0
185479,1610612765,DET,Detroit,739,Rasheed Wallace,5.0,10.0,1.0,4.0,0.0,0.0,0.0,1.0,1.0,1.0,2.0,1.0,1.0,5.0,11.0
185480,1610612765,DET,Detroit,1112,Ben Wallace,6.0,10.0,0.0,0.0,0.0,2.0,2.0,9.0,11.0,1.0,2.0,2.0,0.0,5.0,12.0
185481,1610612765,DET,Detroit,1497,Chauncey Billups,3.0,8.0,0.0,3.0,7.0,8.0,1.0,3.0,4.0,8.0,1.0,0.0,1.0,4.0,13.0
185482,1610612765,DET,Detroit,1888,Richard Hamilton,6.0,18.0,0.0,2.0,3.0,4.0,1.0,7.0,8.0,1.0,0.0,1.0,1.0,3.0,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187120,1610612760,SEA,Seattle,2209,Vladimir Radmanovic,0.0,1.0,0.0,1.0,0.0,0.0,0.0,2.0,2.0,0.0,2.0,0.0,0.0,0.0,0.0
187121,1610612760,SEA,Seattle,2555,Nick Collison,2.0,3.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,4.0,4.0
187122,1610612760,SEA,Seattle,1498,Antonio Daniels,3.0,8.0,0.0,2.0,6.0,8.0,1.0,3.0,4.0,4.0,2.0,0.0,3.0,0.0,12.0
187123,1610612760,SEA,Seattle,1504,Danny Fortson,1.0,2.0,0.0,0.0,1.0,2.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,3.0
187124,1610612760,SEA,Seattle,2863,Damien Wilkins,0.0,2.0,0.0,2.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [162]:
playoffs_by_player_05 = filtered_playoffs_05.groupby(['PLAYER_NAME']).agg({'TEAM_ID': 'last', 'TEAM_ABBREVIATION': 'last', 'TEAM_CITY': 'last', 'PLAYER_ID': 'last',
                                                            '2pointer_MADE': 'sum', '2pointer_ATTEMPTS': 'sum',
                                                            '3pointer_MADE': 'sum', '3pointer_ATTEMPTS': 'sum', 'FreeThrow_MADE': 'sum', 
                                                            'FreeThrow_ATTEMPTS': 'sum', 'OFFENSIVE_REBOUNDS': 'sum', 
                                                            'DEFENSIVE_REBOUNDS': 'sum', 'REBOUNDS_TOTAL': 'sum', 'ASSISTS': 'sum',
                                                            'STEALS': 'sum', 'BLOCKS': 'sum', 'TURNOVERS': 'sum', 'PERSONAL_FOULS': 'sum', 
                                                            'POINTS': 'sum'}).reset_index()
playoffs_by_player_05

,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,Aaron McKie,1610612755,PHI,Philadelphia,243,3.0,7.0,1.0,3.0,0.0,0.0,1.0,11.0,12.0,5.0,4.0,0.0,1.0,9.0,7.0
1,Adrian Griffin,1610612741,CHI,Chicago,1559,15.0,29.0,0.0,0.0,4.0,5.0,5.0,15.0,20.0,9.0,5.0,0.0,3.0,14.0,34.0
2,Al Jefferson,1610612738,BOS,Boston,2744,17.0,41.0,0.0,0.0,9.0,12.0,17.0,28.0,45.0,2.0,4.0,8.0,4.0,16.0,43.0
3,Alan Henderson,1610612742,DAL,Dallas,673,8.0,14.0,0.0,0.0,2.0,2.0,11.0,6.0,17.0,0.0,2.0,2.0,2.0,15.0,18.0
4,Allen Iverson,1610612755,PHI,Philadelphia,947,59.0,126.0,12.0,29.0,26.0,29.0,0.0,11.0,11.0,50.0,10.0,2.0,21.0,12.0,156.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183,Walter McCarty,1610612756,PHX,Phoenix,962,2.0,9.0,2.0,6.0,0.0,2.0,0.0,6.0,6.0,3.0,2.0,2.0,1.0,13.0,6.0
184,Wesley Person,1610612743,DEN,Denver,445,6.0,14.0,3.0,8.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,15.0
185,Willie Green,1610612755,PHI,Philadelphia,2584,8.0,18.0,2.0,9.0,9.0,10.0,3.0,6.0,9.0,3.0,1.0,0.0,2.0,5.0,27.0
186,Yao Ming,1610612745,HOU,Houston,2397,55.0,84.0,0.0,0.0,40.0,55.0,23.0,31.0,54.0,5.0,2.0,19.0,19.0,31.0,150.0
187,Zoran Planinic,1610612751,NJN,New Jersey,2565,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [163]:
filtered_playoffs_06 = Playoffs_06[['TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_CITY', 'PLAYER_ID', 'PLAYER_NAME', '2pointer_MADE', '2pointer_ATTEMPTS',
                        '3pointer_MADE', '3pointer_ATTEMPTS', 'FreeThrow_MADE', 'FreeThrow_ATTEMPTS', 'OFFENSIVE_REBOUNDS', 
                         'DEFENSIVE_REBOUNDS', 'REBOUNDS_TOTAL', 'ASSISTS','STEALS', 'BLOCKS', 'TURNOVERS', 'PERSONAL_FOULS', 'POINTS']]
filtered_playoffs_06

,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
155967,1610612748,MIA,Miami,952,Antoine Walker,6.0,17.0,0.0,6.0,2.0,3.0,3.0,8.0,11.0,2.0,1.0,1.0,0.0,2.0,14.0
155968,1610612748,MIA,Miami,2617,Udonis Haslem,8.0,13.0,0.0,0.0,1.0,4.0,4.0,6.0,10.0,1.0,2.0,0.0,3.0,3.0,17.0
155969,1610612748,MIA,Miami,406,Shaquille O'Neal,4.0,11.0,0.0,0.0,1.0,4.0,3.0,9.0,12.0,1.0,0.0,1.0,2.0,5.0,9.0
155970,1610612748,MIA,Miami,2548,Dwyane Wade,10.0,18.0,0.0,0.0,16.0,21.0,3.0,7.0,10.0,5.0,4.0,3.0,5.0,4.0,36.0
155971,1610612748,MIA,Miami,1715,Jason Williams,1.0,7.0,1.0,7.0,0.0,0.0,0.0,1.0,1.0,7.0,0.0,0.0,2.0,0.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157682,1610612746,LAC,Los Angeles,208,Sam Cassell,6.0,11.0,1.0,4.0,6.0,7.0,1.0,0.0,1.0,7.0,0.0,0.0,0.0,2.0,19.0
157683,1610612746,LAC,Los Angeles,2209,Vladimir Radmanovic,1.0,3.0,1.0,2.0,2.0,2.0,2.0,3.0,5.0,1.0,1.0,0.0,3.0,3.0,5.0
157684,1610612746,LAC,Los Angeles,1894,Corey Maggette,2.0,8.0,1.0,2.0,3.0,4.0,2.0,5.0,7.0,1.0,1.0,0.0,1.0,2.0,8.0
157685,1610612746,LAC,Los Angeles,1442,Zeljko Rebraca,1.0,2.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,2.0,3.0,2.0
157686,1610612746,LAC,Los Angeles,2733,Shaun Livingston,1.0,4.0,0.0,0.0,0.0,2.0,0.0,1.0,1.0,3.0,0.0,0.0,1.0,2.0,2.0

In [164]:
playoffs_by_player_06 = filtered_playoffs_06.groupby(['PLAYER_NAME']).agg({'TEAM_ID': 'last', 'TEAM_ABBREVIATION': 'last', 'TEAM_CITY': 'last', 'PLAYER_ID': 'last',
                                                            '2pointer_MADE': 'sum', '2pointer_ATTEMPTS': 'sum',
                                                            '3pointer_MADE': 'sum', '3pointer_ATTEMPTS': 'sum', 'FreeThrow_MADE': 'sum', 
                                                            'FreeThrow_ATTEMPTS': 'sum', 'OFFENSIVE_REBOUNDS': 'sum', 
                                                            'DEFENSIVE_REBOUNDS': 'sum', 'REBOUNDS_TOTAL': 'sum', 'ASSISTS': 'sum',
                                                            'STEALS': 'sum', 'BLOCKS': 'sum', 'TURNOVERS': 'sum', 'PERSONAL_FOULS': 'sum', 
                                                            'POINTS': 'sum'}).reset_index()
playoffs_by_player_06

,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,Aaron McKie,1610612747,LAL,Los Angeles,243,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Adrian Griffin,1610612742,DAL,Dallas,1559,32.0,59.0,0.0,0.0,7.0,8.0,28.0,43.0,71.0,24.0,15.0,2.0,11.0,42.0,71.0
2,Alan Henderson,1610612739,CLE,Cleveland,673,0.0,2.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0
3,Alonzo Mourning,1610612748,MIA,Miami,297,26.0,37.0,0.0,0.0,28.0,42.0,17.0,44.0,61.0,3.0,5.0,24.0,17.0,49.0,80.0
4,Anderson Varejao,1610612739,CLE,Cleveland,2760,31.0,50.0,0.0,0.0,26.0,37.0,18.0,40.0,58.0,3.0,9.0,2.0,6.0,50.0,88.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Walter McCarty,1610612746,LAC,Los Angeles,962,1.0,4.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,2.0,2.0
191,Wayne Simien,1610612748,MIA,Miami,101134,0.0,3.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
192,Zeljko Rebraca,1610612746,LAC,Los Angeles,1442,1.0,3.0,0.0,0.0,0.0,0.0,1.0,3.0,4.0,0.0,0.0,1.0,2.0,6.0,2.0
193,Zoran Planinic,1610612751,NJN,New Jersey,2565,0.0,1.0,0.0,0.0,0.0,2.0,0.0,1.0,1.0,2.0,1.0,0.0,1.0,1.0,0.0
194,Zydrunas Ilgauskas,1610612739,CLE,Cleveland,980,54.0,119.0,0.0,0.0,27.0,36.0,33.0,49.0,82.0,10.0,5.0,27.0,24.0,46.0,135.0

In [165]:
filtered_playoffs_07 = Playoffs_07[['TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_CITY', 'PLAYER_ID', 'PLAYER_NAME', '2pointer_MADE', '2pointer_ATTEMPTS',
                        '3pointer_MADE', '3pointer_ATTEMPTS', 'FreeThrow_MADE', 'FreeThrow_ATTEMPTS', 'OFFENSIVE_REBOUNDS', 
                         'DEFENSIVE_REBOUNDS', 'REBOUNDS_TOTAL', 'ASSISTS','STEALS', 'BLOCKS', 'TURNOVERS', 'PERSONAL_FOULS', 'POINTS']]
filtered_playoffs_07

,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
126561,1610612759,SAS,San Antonio,1477,Bruce Bowen,1.0,6.0,0.0,3.0,0.0,0.0,1.0,4.0,5.0,3.0,0.0,0.0,0.0,4.0,2.0
126562,1610612759,SAS,San Antonio,1495,Tim Duncan,4.0,15.0,0.0,0.0,4.0,10.0,5.0,10.0,15.0,3.0,2.0,2.0,6.0,3.0,12.0
126563,1610612759,SAS,San Antonio,101177,Fabricio Oberto,3.0,5.0,0.0,0.0,1.0,1.0,3.0,2.0,5.0,0.0,1.0,0.0,0.0,2.0,7.0
126564,1610612759,SAS,San Antonio,714,Michael Finley,1.0,5.0,0.0,2.0,2.0,3.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,4.0
126565,1610612759,SAS,San Antonio,2225,Tony Parker,10.0,14.0,2.0,3.0,2.0,5.0,0.0,7.0,7.0,1.0,0.0,0.0,3.0,2.0,24.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128118,1610612745,HOU,Houston,1503,Tracy McGrady,8.0,17.0,3.0,5.0,4.0,6.0,0.0,4.0,4.0,7.0,1.0,2.0,4.0,0.0,23.0
128119,1610612745,HOU,Houston,1747,Rafer Alston,3.0,11.0,3.0,10.0,0.0,0.0,1.0,10.0,11.0,8.0,2.0,0.0,3.0,4.0,9.0
128120,1610612745,HOU,Houston,101129,Luther Head,2.0,8.0,1.0,6.0,1.0,2.0,0.0,4.0,4.0,3.0,1.0,1.0,0.0,2.0,6.0
128121,1610612745,HOU,Houston,87,Dikembe Mutombo,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
128122,1610612745,HOU,Houston,436,Juwan Howard,2.0,5.0,0.0,0.0,4.0,4.0,0.0,3.0,3.0,0.0,1.0,0.0,2.0,0.0,8.0

In [166]:
playoffs_by_player_07 = filtered_playoffs_07.groupby(['PLAYER_NAME']).agg({'TEAM_ID': 'last', 'TEAM_ABBREVIATION': 'last', 'TEAM_CITY': 'last', 'PLAYER_ID': 'last',
                                                            '2pointer_MADE': 'sum', '2pointer_ATTEMPTS': 'sum',
                                                            '3pointer_MADE': 'sum', '3pointer_ATTEMPTS': 'sum', 'FreeThrow_MADE': 'sum', 
                                                            'FreeThrow_ATTEMPTS': 'sum', 'OFFENSIVE_REBOUNDS': 'sum', 
                                                            'DEFENSIVE_REBOUNDS': 'sum', 'REBOUNDS_TOTAL': 'sum', 'ASSISTS': 'sum',
                                                            'STEALS': 'sum', 'BLOCKS': 'sum', 'TURNOVERS': 'sum', 'PERSONAL_FOULS': 'sum', 
                                                            'POINTS': 'sum'}).reset_index()
playoffs_by_player_07

,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,Adonal Foyle,1610612744,GSW,Golden State,1502,1.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,2.0
1,Adrian Griffin,1610612741,CHI,Chicago,1559,0.0,6.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
2,Al Harrington,1610612744,GSW,Golden State,1733,39.0,98.0,15.0,38.0,19.0,30.0,17.0,34.0,51.0,6.0,5.0,7.0,10.0,40.0,112.0
3,Allen Iverson,1610612743,DEN,Denver,947,42.0,114.0,5.0,17.0,25.0,31.0,0.0,3.0,3.0,29.0,7.0,0.0,15.0,11.0,114.0
4,Alonzo Mourning,1610612748,MIA,Miami,297,10.0,11.0,0.0,0.0,5.0,13.0,1.0,7.0,8.0,1.0,0.0,3.0,1.0,6.0,25.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,Vassilis Spanoulis,1610612745,HOU,Houston,2779,1.0,2.0,0.0,0.0,2.0,2.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,4.0
187,Vince Carter,1610612751,NJN,New Jersey,1713,93.0,235.0,21.0,54.0,61.0,88.0,17.0,65.0,82.0,64.0,11.0,7.0,38.0,35.0,268.0
188,Yakhouba Diawara,1610612743,DEN,Denver,200821,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
189,Yao Ming,1610612745,HOU,Houston,2397,55.0,125.0,0.0,0.0,66.0,75.0,23.0,49.0,72.0,6.0,1.0,5.0,33.0,27.0,176.0
190,Zydrunas Ilgauskas,1610612739,CLE,Cleveland,980,97.0,197.0,0.0,0.0,57.0,68.0,66.0,127.0,193.0,17.0,9.0,16.0,32.0,60.0,251.0

In [167]:
filtered_playoffs_08 = Playoffs_08[['TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_CITY', 'PLAYER_ID', 'PLAYER_NAME', '2pointer_MADE', '2pointer_ATTEMPTS',
                        '3pointer_MADE', '3pointer_ATTEMPTS', 'FreeThrow_MADE', 'FreeThrow_ATTEMPTS', 'OFFENSIVE_REBOUNDS', 
                         'DEFENSIVE_REBOUNDS', 'REBOUNDS_TOTAL', 'ASSISTS','STEALS', 'BLOCKS', 'TURNOVERS', 'PERSONAL_FOULS', 'POINTS']]
filtered_playoffs_08

,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
97564,1610612747,LAL,Los Angeles,2209,Vladimir Radmanovic,2.0,6.0,2.0,6.0,0.0,0.0,0.0,3.0,3.0,0.0,0.0,0.0,0.0,5.0,6.0
97565,1610612747,LAL,Los Angeles,1885,Lamar Odom,2.0,8.0,0.0,1.0,10.0,16.0,0.0,10.0,10.0,5.0,0.0,0.0,3.0,4.0,14.0
97566,1610612747,LAL,Los Angeles,2200,Pau Gasol,4.0,7.0,0.0,0.0,3.0,4.0,0.0,8.0,8.0,2.0,0.0,0.0,5.0,3.0,11.0
97567,1610612747,LAL,Los Angeles,977,Kobe Bryant,7.0,22.0,3.0,9.0,5.0,5.0,1.0,2.0,3.0,1.0,1.0,0.0,4.0,1.0,22.0
97568,1610612747,LAL,Los Angeles,965,Derek Fisher,2.0,4.0,0.0,2.0,3.0,3.0,0.0,0.0,0.0,4.0,0.0,0.0,1.0,5.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99324,1610612759,SAS,San Antonio,703,Kurt Thomas,2.0,5.0,0.0,0.0,0.0,0.0,4.0,6.0,10.0,0.0,0.0,1.0,2.0,6.0,4.0
99325,1610612759,SAS,San Antonio,1938,Manu Ginobili,10.0,24.0,0.0,6.0,4.0,5.0,1.0,3.0,4.0,5.0,3.0,0.0,4.0,4.0,24.0
99326,1610612759,SAS,San Antonio,1521,Jacque Vaughn,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
99327,1610612759,SAS,San Antonio,2137,Ime Udoka,1.0,4.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,2.0
99328,1610612759,SAS,San Antonio,699,Brent Barry,1.0,1.0,1.0,1.0,1.0,2.0,0.0,2.0,2.0,0.0,1.0,0.0,0.0,2.0,4.0

In [168]:
playoffs_by_player_08 = filtered_playoffs_08.groupby(['PLAYER_NAME']).agg({'TEAM_ID': 'last', 'TEAM_ABBREVIATION': 'last', 'TEAM_CITY': 'last', 'PLAYER_ID': 'last',
                                                            '2pointer_MADE': 'sum', '2pointer_ATTEMPTS': 'sum',
                                                            '3pointer_MADE': 'sum', '3pointer_ATTEMPTS': 'sum', 'FreeThrow_MADE': 'sum', 
                                                            'FreeThrow_ATTEMPTS': 'sum', 'OFFENSIVE_REBOUNDS': 'sum', 
                                                            'DEFENSIVE_REBOUNDS': 'sum', 'REBOUNDS_TOTAL': 'sum', 'ASSISTS': 'sum',
                                                            'STEALS': 'sum', 'BLOCKS': 'sum', 'TURNOVERS': 'sum', 'PERSONAL_FOULS': 'sum', 
                                                            'POINTS': 'sum'}).reset_index()
playoffs_by_player_08

,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,Aaron Brooks,1610612745,HOU,Houston,201166,8.0,25.0,0.0,10.0,9.0,11.0,0.0,6.0,6.0,3.0,0.0,0.0,3.0,11.0,25.0
1,Acie Law,1610612737,ATL,Atlanta,201151,6.0,8.0,0.0,0.0,9.0,10.0,0.0,2.0,2.0,8.0,2.0,0.0,8.0,5.0,21.0
2,Adonal Foyle,1610612753,ORL,Orlando,1502,1.0,3.0,0.0,0.0,0.0,0.0,0.0,3.0,3.0,0.0,0.0,0.0,2.0,1.0,2.0
3,Al Horford,1610612737,ATL,Atlanta,201143,34.0,72.0,0.0,0.0,20.0,27.0,22.0,51.0,73.0,25.0,3.0,7.0,15.0,26.0,88.0
4,Allen Iverson,1610612743,DEN,Denver,947,36.0,83.0,3.0,14.0,23.0,33.0,4.0,8.0,12.0,18.0,4.0,1.0,7.0,3.0,98.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,Walter Herrmann,1610612765,DET,Detroit,200835,1.0,4.0,1.0,1.0,2.0,4.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,4.0,5.0
198,Willie Green,1610612755,PHI,Philadelphia,2584,22.0,51.0,1.0,5.0,9.0,14.0,2.0,6.0,8.0,12.0,5.0,4.0,9.0,19.0,54.0
199,Yakhouba Diawara,1610612743,DEN,Denver,200821,2.0,5.0,0.0,2.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,4.0
200,Zaza Pachulia,1610612737,ATL,Atlanta,2585,7.0,25.0,0.0,1.0,15.0,21.0,9.0,11.0,20.0,2.0,2.0,0.0,9.0,22.0,29.0
201,Zydrunas Ilgauskas,1610612739,CLE,Cleveland,980,67.0,140.0,0.0,0.0,36.0,44.0,33.0,65.0,98.0,21.0,5.0,14.0,21.0,35.0,170.0

In [169]:
filtered_playoffs_09 = Playoffs_09[['TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_CITY', 'PLAYER_ID', 'PLAYER_NAME', '2pointer_MADE', '2pointer_ATTEMPTS',
                        '3pointer_MADE', '3pointer_ATTEMPTS', 'FreeThrow_MADE', 'FreeThrow_ATTEMPTS', 'OFFENSIVE_REBOUNDS', 
                         'DEFENSIVE_REBOUNDS', 'REBOUNDS_TOTAL', 'ASSISTS','STEALS', 'BLOCKS', 'TURNOVERS', 'PERSONAL_FOULS', 'POINTS']]
filtered_playoffs_09

,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
68542,1610612747,LAL,Los Angeles,2772,Trevor Ariza,5.0,12.0,2.0,5.0,3.0,6.0,1.0,4.0,5.0,1.0,2.0,0.0,3.0,3.0,15.0
68543,1610612747,LAL,Los Angeles,2200,Pau Gasol,6.0,9.0,0.0,0.0,2.0,4.0,4.0,11.0,15.0,3.0,0.0,4.0,1.0,2.0,14.0
68544,1610612747,LAL,Los Angeles,101115,Andrew Bynum,3.0,11.0,0.0,0.0,0.0,1.0,4.0,1.0,5.0,0.0,1.0,0.0,1.0,5.0,6.0
68545,1610612747,LAL,Los Angeles,977,Kobe Bryant,10.0,23.0,2.0,5.0,8.0,8.0,0.0,6.0,6.0,5.0,2.0,4.0,1.0,2.0,30.0
68546,1610612747,LAL,Los Angeles,965,Derek Fisher,4.0,7.0,1.0,1.0,4.0,4.0,0.0,4.0,4.0,2.0,0.0,0.0,1.0,4.0,13.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70278,1610612757,POR,Portland,2566,Travis Outlaw,4.0,10.0,0.0,1.0,1.0,2.0,1.0,1.0,2.0,0.0,1.0,0.0,2.0,1.0,9.0
70279,1610612757,POR,Portland,200771,Sergio Rodriguez,1.0,4.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,2.0,0.0,0.0,1.0,1.0,2.0
70280,1610612757,POR,Portland,101112,Channing Frye,2.0,5.0,0.0,0.0,0.0,1.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,4.0,4.0
70281,1610612757,POR,Portland,201573,Jerryd Bayless,1.0,4.0,0.0,1.0,2.0,3.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,4.0
70282,1610612757,POR,Portland,1913,Michael Ruffin,0.0,1.0,0.0,0.0,1.0,2.0,3.0,2.0,5.0,0.0,0.0,0.0,1.0,1.0,1.0

In [170]:
playoffs_by_player_09 = filtered_playoffs_09.groupby(['PLAYER_NAME']).agg({'TEAM_ID': 'last', 'TEAM_ABBREVIATION': 'last', 'TEAM_CITY': 'last', 'PLAYER_ID': 'last',
                                                            '2pointer_MADE': 'sum', '2pointer_ATTEMPTS': 'sum',
                                                            '3pointer_MADE': 'sum', '3pointer_ATTEMPTS': 'sum', 'FreeThrow_MADE': 'sum', 
                                                            'FreeThrow_ATTEMPTS': 'sum', 'OFFENSIVE_REBOUNDS': 'sum', 
                                                            'DEFENSIVE_REBOUNDS': 'sum', 'REBOUNDS_TOTAL': 'sum', 'ASSISTS': 'sum',
                                                            'STEALS': 'sum', 'BLOCKS': 'sum', 'TURNOVERS': 'sum', 'PERSONAL_FOULS': 'sum', 
                                                            'POINTS': 'sum'}).reset_index()
playoffs_by_player_09

,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,Aaron Brooks,1610612745,HOU,Houston,201166,77.0,170.0,27.0,64.0,37.0,46.0,4.0,30.0,34.0,44.0,5.0,3.0,29.0,29.0,218.0
1,Aaron Gray,1610612741,CHI,Chicago,201189,0.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
2,Acie Law,1610612737,ATL,Atlanta,201151,3.0,9.0,1.0,3.0,1.0,1.0,1.0,1.0,2.0,6.0,0.0,0.0,1.0,3.0,8.0
3,Adonal Foyle,1610612753,ORL,Orlando,1502,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
4,Al Horford,1610612737,ATL,Atlanta,201143,25.0,59.0,0.0,1.0,12.0,18.0,12.0,40.0,52.0,18.0,6.0,6.0,4.0,26.0,62.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,Willie Green,1610612755,PHI,Philadelphia,2584,21.0,51.0,4.0,11.0,1.0,3.0,0.0,6.0,6.0,7.0,0.0,1.0,5.0,13.0,47.0
195,Yakhouba Diawara,1610612748,MIA,Miami,200821,1.0,3.0,0.0,1.0,0.0,2.0,0.0,5.0,5.0,0.0,1.0,0.0,0.0,2.0,2.0
196,Yao Ming,1610612745,HOU,Houston,2397,54.0,99.0,0.0,0.0,46.0,51.0,19.0,79.0,98.0,9.0,4.0,11.0,17.0,27.0,154.0
197,Zaza Pachulia,1610612737,ATL,Atlanta,2585,22.0,53.0,0.0,0.0,32.0,42.0,28.0,48.0,76.0,3.0,5.0,3.0,14.0,40.0,76.0
198,Zydrunas Ilgauskas,1610612739,CLE,Cleveland,980,62.0,138.0,2.0,13.0,21.0,33.0,27.0,82.0,109.0,17.0,5.0,13.0,9.0,47.0,147.0

In [171]:
filtered_playoffs_10 = Playoffs_10[['TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_CITY', 'PLAYER_ID', 'PLAYER_NAME', '2pointer_MADE', '2pointer_ATTEMPTS',
                        '3pointer_MADE', '3pointer_ATTEMPTS', 'FreeThrow_MADE', 'FreeThrow_ATTEMPTS', 'OFFENSIVE_REBOUNDS', 
                         'DEFENSIVE_REBOUNDS', 'REBOUNDS_TOTAL', 'ASSISTS','STEALS', 'BLOCKS', 'TURNOVERS', 'PERSONAL_FOULS', 'POINTS']]
filtered_playoffs_10

,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
291805,1610612738,BOS,Boston,1718,Paul Pierce,5.0,15.0,2.0,3.0,6.0,6.0,1.0,9.0,10.0,2.0,1.0,1.0,3.0,4.0,18.0
291806,1610612738,BOS,Boston,708,Kevin Garnett,8.0,13.0,0.0,0.0,1.0,1.0,0.0,3.0,3.0,2.0,0.0,4.0,2.0,5.0,17.0
291807,1610612738,BOS,Boston,739,Rasheed Wallace,5.0,11.0,1.0,4.0,0.0,0.0,2.0,6.0,8.0,2.0,0.0,2.0,0.0,6.0,11.0
291808,1610612738,BOS,Boston,951,Ray Allen,3.0,14.0,2.0,7.0,5.0,6.0,0.0,2.0,2.0,2.0,3.0,0.0,4.0,3.0,13.0
291809,1610612738,BOS,Boston,200765,Rajon Rondo,6.0,13.0,1.0,2.0,1.0,2.0,4.0,4.0,8.0,10.0,1.0,0.0,3.0,2.0,14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
293474,1610612743,DEN,Denver,2365,Chris Andersen,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,6.0,1.0,0.0,2.0,0.0,1.0,0.0
293475,1610612743,DEN,Denver,201951,Ty Lawson,3.0,8.0,2.0,3.0,3.0,4.0,1.0,2.0,3.0,6.0,1.0,0.0,0.0,3.0,11.0
293476,1610612743,DEN,Denver,101121,Joey Graham,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
293477,1610612743,DEN,Denver,101130,Johan Petro,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
293478,1610612743,DEN,Denver,2124,Malik Allen,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [172]:
playoffs_by_player_10 = filtered_playoffs_10.groupby(['PLAYER_NAME']).agg({'TEAM_ID': 'last', 'TEAM_ABBREVIATION': 'last', 'TEAM_CITY': 'last', 'PLAYER_ID': 'last',
                                                            '2pointer_MADE': 'sum', '2pointer_ATTEMPTS': 'sum',
                                                            '3pointer_MADE': 'sum', '3pointer_ATTEMPTS': 'sum', 'FreeThrow_MADE': 'sum', 
                                                            'FreeThrow_ATTEMPTS': 'sum', 'OFFENSIVE_REBOUNDS': 'sum', 
                                                            'DEFENSIVE_REBOUNDS': 'sum', 'REBOUNDS_TOTAL': 'sum', 'ASSISTS': 'sum',
                                                            'STEALS': 'sum', 'BLOCKS': 'sum', 'TURNOVERS': 'sum', 'PERSONAL_FOULS': 'sum', 
                                                            'POINTS': 'sum'}).reset_index()
playoffs_by_player_10

,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,Adam Morrison,1610612747,LAL,Los Angeles,200747,4.0,9.0,0.0,2.0,0.0,0.0,2.0,3.0,5.0,1.0,0.0,0.0,0.0,2.0,8.0
1,Al Horford,1610612737,ATL,Atlanta,201143,67.0,128.0,1.0,1.0,26.0,31.0,28.0,71.0,99.0,20.0,8.0,19.0,15.0,35.0,161.0
2,Amar'e Stoudemire,1610612756,PHX,Phoenix,2405,124.0,239.0,0.0,4.0,107.0,142.0,46.0,60.0,106.0,18.0,11.0,24.0,40.0,54.0,355.0
3,Anderson Varejao,1610612739,CLE,Cleveland,2760,20.0,48.0,0.0,1.0,23.0,31.0,22.0,49.0,71.0,7.0,11.0,9.0,12.0,38.0,63.0
4,Andre Miller,1610612757,POR,Portland,1889,30.0,74.0,3.0,7.0,31.0,40.0,5.0,14.0,19.0,36.0,7.0,1.0,19.0,12.0,94.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,Udonis Haslem,1610612748,MIA,Miami,2617,13.0,37.0,0.0,0.0,4.0,6.0,9.0,28.0,37.0,4.0,1.0,1.0,5.0,18.0,30.0
195,Vince Carter,1610612753,ORL,Orlando,1713,74.0,184.0,12.0,51.0,57.0,69.0,9.0,50.0,59.0,32.0,12.0,3.0,22.0,50.0,217.0
196,Wesley Matthews,1610612762,UTA,Utah,202083,39.0,101.0,15.0,42.0,39.0,48.0,10.0,34.0,44.0,17.0,18.0,5.0,15.0,34.0,132.0
197,Zaza Pachulia,1610612737,ATL,Atlanta,2585,18.0,35.0,0.0,0.0,15.0,24.0,19.0,19.0,38.0,3.0,2.0,7.0,9.0,34.0,51.0
198,Zydrunas Ilgauskas,1610612739,CLE,Cleveland,980,5.0,13.0,0.0,0.0,2.0,3.0,7.0,4.0,11.0,3.0,0.0,7.0,1.0,10.0,12.0

In [173]:
filtered_playoffs_11 = Playoffs_11[['TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_CITY', 'PLAYER_ID', 'PLAYER_NAME', '2pointer_MADE', '2pointer_ATTEMPTS',
                        '3pointer_MADE', '3pointer_ATTEMPTS', 'FreeThrow_MADE', 'FreeThrow_ATTEMPTS', 'OFFENSIVE_REBOUNDS', 
                         'DEFENSIVE_REBOUNDS', 'REBOUNDS_TOTAL', 'ASSISTS','STEALS', 'BLOCKS', 'TURNOVERS', 'PERSONAL_FOULS', 'POINTS']]
filtered_playoffs_11

,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
262364,1610612742,DAL,Dallas,1890,Shawn Marion,4.0,10.0,0.0,0.0,4.0,6.0,3.0,5.0,8.0,1.0,1.0,0.0,2.0,3.0,12.0
262365,1610612742,DAL,Dallas,1717,Dirk Nowitzki,9.0,27.0,1.0,7.0,2.0,2.0,0.0,11.0,11.0,1.0,2.0,0.0,2.0,4.0,21.0
262366,1610612742,DAL,Dallas,2199,Tyson Chandler,2.0,4.0,0.0,0.0,1.0,2.0,2.0,6.0,8.0,1.0,2.0,0.0,1.0,5.0,5.0
262367,1610612742,DAL,Dallas,467,Jason Kidd,2.0,4.0,2.0,3.0,3.0,4.0,0.0,4.0,4.0,8.0,0.0,1.0,2.0,1.0,9.0
262368,1610612742,DAL,Dallas,200826,J.J. Barea,7.0,12.0,1.0,3.0,0.0,0.0,2.0,1.0,3.0,5.0,2.0,0.0,3.0,3.0,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263975,1610612748,MIA,Miami,1710,Mike Bibby,3.0,9.0,2.0,7.0,0.0,0.0,0.0,2.0,2.0,1.0,0.0,0.0,3.0,2.0,8.0
263976,1610612748,MIA,Miami,201202,Joel Anthony,0.0,3.0,0.0,0.0,3.0,4.0,3.0,1.0,4.0,0.0,0.0,1.0,2.0,3.0,3.0
263977,1610612748,MIA,Miami,2592,James Jones,4.0,8.0,1.0,4.0,0.0,0.0,2.0,3.0,5.0,1.0,1.0,0.0,0.0,0.0,9.0
263978,1610612748,MIA,Miami,2034,Mike Miller,0.0,3.0,0.0,2.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
263979,1610612748,MIA,Miami,201596,Mario Chalmers,2.0,2.0,1.0,1.0,1.0,2.0,0.0,1.0,1.0,1.0,1.0,0.0,2.0,1.0,6.0

In [174]:
playoffs_by_player_11 = filtered_playoffs_11.groupby(['PLAYER_NAME']).agg({'TEAM_ID': 'last', 'TEAM_ABBREVIATION': 'last', 'TEAM_CITY': 'last', 'PLAYER_ID': 'last',
                                                            '2pointer_MADE': 'sum', '2pointer_ATTEMPTS': 'sum',
                                                            '3pointer_MADE': 'sum', '3pointer_ATTEMPTS': 'sum', 'FreeThrow_MADE': 'sum', 
                                                            'FreeThrow_ATTEMPTS': 'sum', 'OFFENSIVE_REBOUNDS': 'sum', 
                                                            'DEFENSIVE_REBOUNDS': 'sum', 'REBOUNDS_TOTAL': 'sum', 'ASSISTS': 'sum',
                                                            'STEALS': 'sum', 'BLOCKS': 'sum', 'TURNOVERS': 'sum', 'PERSONAL_FOULS': 'sum', 
                                                            'POINTS': 'sum'}).reset_index()
playoffs_by_player_11

,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,AJ Price,1610612754,IND,Indiana,201985,13.0,35.0,7.0,16.0,9.0,10.0,2.0,5.0,7.0,6.0,3.0,0.0,7.0,5.0,42.0
1,Aaron Gray,1610612740,NOH,New Orleans,201189,9.0,13.0,0.0,0.0,3.0,8.0,3.0,18.0,21.0,2.0,2.0,2.0,5.0,13.0,21.0
2,Al Harrington,1610612743,DEN,Denver,1733,10.0,22.0,5.0,10.0,3.0,4.0,1.0,6.0,7.0,5.0,3.0,0.0,4.0,7.0,28.0
3,Al Horford,1610612737,ATL,Atlanta,201143,58.0,137.0,0.0,2.0,20.0,26.0,25.0,90.0,115.0,42.0,5.0,12.0,17.0,33.0,136.0
4,Amar'e Stoudemire,1610612752,NYK,New York,2405,21.0,55.0,0.0,0.0,16.0,24.0,11.0,20.0,31.0,7.0,1.0,3.0,12.0,10.0,58.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,Willie Green,1610612740,NOH,New Orleans,2584,14.0,36.0,2.0,9.0,4.0,7.0,1.0,4.0,5.0,4.0,2.0,0.0,3.0,14.0,34.0
190,Wilson Chandler,1610612743,DEN,Denver,201163,8.0,29.0,1.0,7.0,7.0,9.0,2.0,20.0,22.0,2.0,3.0,4.0,4.0,15.0,24.0
191,Zach Randolph,1610612763,MEM,Memphis,2216,100.0,224.0,2.0,8.0,87.0,106.0,43.0,98.0,141.0,31.0,14.0,10.0,27.0,45.0,289.0
192,Zaza Pachulia,1610612737,ATL,Atlanta,2585,11.0,23.0,0.0,0.0,17.0,22.0,17.0,37.0,54.0,13.0,2.0,1.0,9.0,37.0,39.0
193,Zydrunas Ilgauskas,1610612748,MIA,Miami,980,14.0,30.0,0.0,0.0,4.0,6.0,15.0,17.0,32.0,3.0,0.0,3.0,9.0,16.0,32.0

In [175]:
filtered_playoffs_12 = Playoffs_12[['TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_CITY', 'PLAYER_ID', 'PLAYER_NAME', '2pointer_MADE', '2pointer_ATTEMPTS',
                        '3pointer_MADE', '3pointer_ATTEMPTS', 'FreeThrow_MADE', 'FreeThrow_ATTEMPTS', 'OFFENSIVE_REBOUNDS', 
                         'DEFENSIVE_REBOUNDS', 'REBOUNDS_TOTAL', 'ASSISTS','STEALS', 'BLOCKS', 'TURNOVERS', 'PERSONAL_FOULS', 'POINTS']]
filtered_playoffs_12

,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
239109,1610612760,OKC,Oklahoma City,201142,Kevin Durant,13.0,24.0,3.0,6.0,3.0,3.0,2.0,9.0,11.0,3.0,2.0,1.0,7.0,5.0,32.0
239110,1610612760,OKC,Oklahoma City,201586,Serge Ibaka,3.0,9.0,0.0,0.0,3.0,4.0,4.0,0.0,4.0,0.0,0.0,2.0,0.0,3.0,9.0
239111,1610612760,OKC,Oklahoma City,2570,Kendrick Perkins,1.0,4.0,0.0,0.0,0.0,0.0,0.0,4.0,4.0,0.0,1.0,0.0,1.0,5.0,2.0
239112,1610612760,OKC,Oklahoma City,200757,Thabo Sefolosha,0.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0
239113,1610612760,OKC,Oklahoma City,201566,Russell Westbrook,4.0,20.0,0.0,5.0,11.0,13.0,0.0,4.0,4.0,6.0,2.0,0.0,2.0,3.0,19.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
240848,1610612741,CHI,Chicago,200758,Ronnie Brewer,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,2.0,0.0
240849,1610612741,CHI,Chicago,201600,Omer Asik,0.0,2.0,0.0,0.0,1.0,4.0,1.0,0.0,1.0,1.0,0.0,1.0,2.0,1.0,1.0
240850,1610612741,CHI,Chicago,201959,Taj Gibson,2.0,3.0,0.0,0.0,3.0,4.0,1.0,2.0,3.0,0.0,3.0,0.0,0.0,4.0,7.0
240851,1610612741,CHI,Chicago,201228,C.J. Watson,1.0,4.0,0.0,1.0,2.0,2.0,0.0,0.0,0.0,5.0,1.0,0.0,1.0,0.0,4.0
240852,1610612741,CHI,Chicago,2594,Kyle Korver,5.0,8.0,1.0,3.0,0.0,0.0,0.0,4.0,4.0,1.0,0.0,1.0,2.0,4.0,11.0

In [176]:
playoffs_by_player_12 = filtered_playoffs_12.groupby(['PLAYER_NAME']).agg({'TEAM_ID': 'last', 'TEAM_ABBREVIATION': 'last', 'TEAM_CITY': 'last', 'PLAYER_ID': 'last',
                                                            '2pointer_MADE': 'sum', '2pointer_ATTEMPTS': 'sum',
                                                            '3pointer_MADE': 'sum', '3pointer_ATTEMPTS': 'sum', 'FreeThrow_MADE': 'sum', 
                                                            'FreeThrow_ATTEMPTS': 'sum', 'OFFENSIVE_REBOUNDS': 'sum', 
                                                            'DEFENSIVE_REBOUNDS': 'sum', 'REBOUNDS_TOTAL': 'sum', 'ASSISTS': 'sum',
                                                            'STEALS': 'sum', 'BLOCKS': 'sum', 'TURNOVERS': 'sum', 'PERSONAL_FOULS': 'sum', 
                                                            'POINTS': 'sum'}).reset_index()
playoffs_by_player_12

,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,AJ Price,1610612754,IND,Indiana,201985,1.0,2.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,1.0,0.0,0.0,0.0,0.0,2.0
1,Al Harrington,1610612743,DEN,Denver,1733,24.0,75.0,10.0,35.0,10.0,15.0,7.0,23.0,30.0,6.0,3.0,1.0,3.0,13.0,68.0
2,Al Horford,1610612737,ATL,Atlanta,201143,20.0,34.0,0.0,0.0,6.0,8.0,5.0,20.0,25.0,8.0,4.0,4.0,12.0,11.0,46.0
3,Al Jefferson,1610612762,UTA,Utah,2744,36.0,68.0,0.0,1.0,1.0,4.0,7.0,27.0,34.0,10.0,5.0,3.0,5.0,10.0,73.0
4,Alec Burks,1610612762,UTA,Utah,202692,7.0,28.0,0.0,2.0,12.0,14.0,5.0,6.0,11.0,3.0,2.0,0.0,3.0,4.0,26.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,Von Wafer,1610612753,ORL,Orlando,101144,3.0,5.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,6.0
200,Willie Green,1610612737,ATL,Atlanta,2584,6.0,13.0,1.0,4.0,0.0,0.0,1.0,7.0,8.0,3.0,0.0,0.0,2.0,6.0,13.0
201,Xavier Silas,1610612755,PHI,Philadelphia,202918,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,2.0
202,Yi Jianlian,1610612742,DAL,Dallas,201146,1.0,3.0,0.0,1.0,0.0,1.0,0.0,2.0,2.0,0.0,1.0,0.0,0.0,0.0,2.0
203,Zach Randolph,1610612763,MEM,Memphis,2216,37.0,88.0,0.0,4.0,22.0,35.0,27.0,42.0,69.0,6.0,7.0,4.0,11.0,25.0,96.0

In [177]:
filtered_playoffs_13 = Playoffs_13[['TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_CITY', 'PLAYER_ID', 'PLAYER_NAME', '2pointer_MADE', '2pointer_ATTEMPTS',
                        '3pointer_MADE', '3pointer_ATTEMPTS', 'FreeThrow_MADE', 'FreeThrow_ATTEMPTS', 'OFFENSIVE_REBOUNDS', 
                         'DEFENSIVE_REBOUNDS', 'REBOUNDS_TOTAL', 'ASSISTS','STEALS', 'BLOCKS', 'TURNOVERS', 'PERSONAL_FOULS', 'POINTS']]
filtered_playoffs_13

,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
510156,1610612759,SAS,San Antonio,202695,Kawhi Leonard,8.0,17.0,1.0,4.0,2.0,4.0,4.0,12.0,16.0,0.0,1.0,1.0,2.0,2.0,19.0
510157,1610612759,SAS,San Antonio,1938,Manu Ginobili,6.0,12.0,2.0,5.0,4.0,4.0,0.0,3.0,3.0,5.0,0.0,0.0,4.0,4.0,18.0
510158,1610612759,SAS,San Antonio,1495,Tim Duncan,8.0,18.0,0.0,0.0,8.0,8.0,4.0,8.0,12.0,2.0,4.0,1.0,3.0,4.0,24.0
510159,1610612759,SAS,San Antonio,201980,Danny Green,1.0,12.0,1.0,6.0,2.0,2.0,1.0,4.0,5.0,0.0,2.0,1.0,2.0,3.0,5.0
510160,1610612759,SAS,San Antonio,2225,Tony Parker,3.0,12.0,0.0,0.0,4.0,4.0,0.0,0.0,0.0,4.0,3.0,0.0,2.0,1.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
511932,1610612746,LAC,Los Angeles,200797,Ryan Hollins,1.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,4.0,2.0
511933,1610612746,LAC,Los Angeles,1885,Lamar Odom,1.0,7.0,0.0,1.0,2.0,4.0,3.0,4.0,7.0,3.0,0.0,1.0,2.0,3.0,4.0
511934,1610612746,LAC,Los Angeles,202339,Eric Bledsoe,7.0,7.0,0.0,0.0,1.0,2.0,1.0,5.0,6.0,4.0,0.0,0.0,1.0,1.0,15.0
511935,1610612746,LAC,Los Angeles,101142,Ronny Turiaf,2.0,2.0,0.0,0.0,1.0,2.0,1.0,2.0,3.0,0.0,0.0,0.0,0.0,3.0,5.0
511936,1610612746,LAC,Los Angeles,2584,Willie Green,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [178]:
playoffs_by_player_13 = filtered_playoffs_13.groupby(['PLAYER_NAME']).agg({'TEAM_ID': 'last', 'TEAM_ABBREVIATION': 'last', 'TEAM_CITY': 'last', 'PLAYER_ID': 'last',
                                                            '2pointer_MADE': 'sum', '2pointer_ATTEMPTS': 'sum',
                                                            '3pointer_MADE': 'sum', '3pointer_ATTEMPTS': 'sum', 'FreeThrow_MADE': 'sum', 
                                                            'FreeThrow_ATTEMPTS': 'sum', 'OFFENSIVE_REBOUNDS': 'sum', 
                                                            'DEFENSIVE_REBOUNDS': 'sum', 'REBOUNDS_TOTAL': 'sum', 'ASSISTS': 'sum',
                                                            'STEALS': 'sum', 'BLOCKS': 'sum', 'TURNOVERS': 'sum', 'PERSONAL_FOULS': 'sum', 
                                                            'POINTS': 'sum'}).reset_index()
playoffs_by_player_13

,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,Aaron Brooks,1610612745,HOU,Houston,201166,13.0,34.0,1.0,9.0,3.0,5.0,3.0,6.0,9.0,11.0,1.0,1.0,6.0,3.0,30.0
1,Al Horford,1610612737,ATL,Atlanta,201143,41.0,83.0,0.0,0.0,18.0,27.0,12.0,41.0,53.0,18.0,6.0,5.0,9.0,17.0,100.0
2,Amar'e Stoudemire,1610612752,NYK,New York,2405,5.0,13.0,1.0,1.0,4.0,4.0,4.0,5.0,9.0,0.0,0.0,0.0,3.0,9.0,15.0
3,Andray Blatche,1610612751,BKN,Brooklyn,101154,29.0,58.0,0.0,0.0,14.0,17.0,10.0,24.0,34.0,9.0,2.0,3.0,5.0,14.0,72.0
4,Andre Iguodala,1610612743,DEN,Denver,2738,38.0,76.0,14.0,29.0,18.0,25.0,9.0,39.0,48.0,32.0,12.0,2.0,17.0,9.0,108.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204,Udonis Haslem,1610612748,MIA,Miami,2617,51.0,86.0,0.0,0.0,8.0,14.0,26.0,54.0,80.0,6.0,15.0,5.0,14.0,54.0,110.0
205,Vladimir Radmanovic,1610612741,CHI,Chicago,2209,3.0,3.0,3.0,3.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,0.0,1.0,1.0,9.0
206,Willie Green,1610612746,LAC,Los Angeles,2584,2.0,3.0,0.0,1.0,2.0,2.0,0.0,3.0,3.0,2.0,1.0,0.0,0.0,0.0,6.0
207,Wilson Chandler,1610612743,DEN,Denver,201163,27.0,76.0,9.0,29.0,9.0,12.0,5.0,28.0,33.0,8.0,8.0,3.0,7.0,25.0,72.0
208,Zach Randolph,1610612763,MEM,Memphis,2216,99.0,215.0,0.0,1.0,63.0,94.0,59.0,91.0,150.0,24.0,10.0,7.0,31.0,52.0,261.0

In [179]:
filtered_playoffs_14 = Playoffs_14[['TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_CITY', 'PLAYER_ID', 'PLAYER_NAME', '2pointer_MADE', '2pointer_ATTEMPTS',
                        '3pointer_MADE', '3pointer_ATTEMPTS', 'FreeThrow_MADE', 'FreeThrow_ATTEMPTS', 'OFFENSIVE_REBOUNDS', 
                         'DEFENSIVE_REBOUNDS', 'REBOUNDS_TOTAL', 'ASSISTS','STEALS', 'BLOCKS', 'TURNOVERS', 'PERSONAL_FOULS', 'POINTS']]
filtered_playoffs_14

,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
479927,1610612748,MIA,Miami,2544,LeBron James,10.0,21.0,3.0,9.0,8.0,9.0,1.0,9.0,10.0,5.0,0.0,2.0,1.0,1.0,31.0
479928,1610612748,MIA,Miami,1740,Rashard Lewis,1.0,2.0,1.0,2.0,0.0,0.0,0.0,2.0,2.0,1.0,0.0,0.0,0.0,2.0,3.0
479929,1610612748,MIA,Miami,2547,Chris Bosh,6.0,14.0,0.0,5.0,1.0,2.0,0.0,7.0,7.0,2.0,1.0,0.0,0.0,2.0,13.0
479930,1610612748,MIA,Miami,2548,Dwyane Wade,4.0,12.0,1.0,2.0,2.0,4.0,0.0,3.0,3.0,1.0,0.0,0.0,3.0,3.0,11.0
479931,1610612748,MIA,Miami,951,Ray Allen,1.0,8.0,1.0,3.0,2.0,2.0,1.0,4.0,5.0,2.0,1.0,0.0,4.0,2.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
481828,1610612760,OKC,Oklahoma City,203500,Steven Adams,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,3.0,0.0,5.0,0.0
481829,1610612760,OKC,Oklahoma City,202704,Reggie Jackson,1.0,5.0,0.0,2.0,7.0,8.0,0.0,8.0,8.0,4.0,0.0,1.0,0.0,2.0,9.0
481830,1610612760,OKC,Oklahoma City,965,Derek Fisher,1.0,3.0,0.0,1.0,2.0,2.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,4.0
481831,1610612760,OKC,Oklahoma City,201934,Hasheem Thabeet,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0
481832,1610612760,OKC,Oklahoma City,203087,Jeremy Lamb,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [180]:
playoffs_by_player_14 = filtered_playoffs_14.groupby(['PLAYER_NAME']).agg({'TEAM_ID': 'last', 'TEAM_ABBREVIATION': 'last', 'TEAM_CITY': 'last', 'PLAYER_ID': 'last',
                                                            '2pointer_MADE': 'sum', '2pointer_ATTEMPTS': 'sum',
                                                            '3pointer_MADE': 'sum', '3pointer_ATTEMPTS': 'sum', 'FreeThrow_MADE': 'sum', 
                                                            'FreeThrow_ATTEMPTS': 'sum', 'OFFENSIVE_REBOUNDS': 'sum', 
                                                            'DEFENSIVE_REBOUNDS': 'sum', 'REBOUNDS_TOTAL': 'sum', 'ASSISTS': 'sum',
                                                            'STEALS': 'sum', 'BLOCKS': 'sum', 'TURNOVERS': 'sum', 'PERSONAL_FOULS': 'sum', 
                                                            'POINTS': 'sum'}).reset_index()
playoffs_by_player_14

,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,Al Harrington,1610612764,WAS,Washington,1733,6.0,15.0,0.0,7.0,5.0,7.0,1.0,15.0,16.0,0.0,3.0,0.0,4.0,14.0,17.0
1,Al Jefferson,1610612766,CHA,Charlotte,2744,26.0,53.0,0.0,0.0,4.0,5.0,6.0,22.0,28.0,2.0,1.0,5.0,1.0,7.0,56.0
2,Alan Anderson,1610612751,BKN,Brooklyn,101187,25.0,62.0,9.0,31.0,12.0,18.0,10.0,22.0,32.0,15.0,10.0,0.0,10.0,32.0,71.0
3,Amir Johnson,1610612761,TOR,Toronto,101161,34.0,52.0,0.0,2.0,9.0,12.0,16.0,26.0,42.0,7.0,3.0,4.0,12.0,29.0,77.0
4,Andray Blatche,1610612751,BKN,Brooklyn,101154,26.0,58.0,0.0,2.0,25.0,30.0,25.0,35.0,60.0,4.0,6.0,2.0,10.0,22.0,77.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,Wayne Ellington,1610612742,DAL,Dallas,201961,2.0,6.0,2.0,6.0,2.0,2.0,0.0,2.0,2.0,2.0,0.0,0.0,2.0,1.0,8.0
200,Wesley Matthews,1610612757,POR,Portland,202083,56.0,136.0,22.0,68.0,26.0,32.0,7.0,36.0,43.0,14.0,14.0,5.0,22.0,45.0,160.0
201,Will Barton,1610612757,POR,Portland,203115,17.0,34.0,6.0,11.0,5.0,6.0,5.0,7.0,12.0,3.0,1.0,2.0,6.0,7.0,45.0
202,Willie Green,1610612746,LAC,Los Angeles,2584,1.0,5.0,1.0,4.0,2.0,2.0,0.0,7.0,7.0,1.0,3.0,0.0,1.0,3.0,5.0
203,Zach Randolph,1610612763,MEM,Memphis,2216,42.0,104.0,0.0,1.0,25.0,41.0,17.0,35.0,52.0,14.0,5.0,1.0,10.0,13.0,109.0

In [181]:
filtered_playoffs_15 = Playoffs_15[['TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_CITY', 'PLAYER_ID', 'PLAYER_NAME', '2pointer_MADE', '2pointer_ATTEMPTS',
                        '3pointer_MADE', '3pointer_ATTEMPTS', 'FreeThrow_MADE', 'FreeThrow_ATTEMPTS', 'OFFENSIVE_REBOUNDS', 
                         'DEFENSIVE_REBOUNDS', 'REBOUNDS_TOTAL', 'ASSISTS','STEALS', 'BLOCKS', 'TURNOVERS', 'PERSONAL_FOULS', 'POINTS']]
filtered_playoffs_15

,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
449619,1610612744,GSW,Golden State,2738,Andre Iguodala,9.0,20.0,3.0,8.0,4.0,10.0,1.0,4.0,5.0,5.0,2.0,0.0,0.0,4.0,25.0
449620,1610612744,GSW,Golden State,203084,Harrison Barnes,3.0,8.0,3.0,4.0,0.0,0.0,0.0,2.0,2.0,2.0,1.0,0.0,0.0,3.0,9.0
449621,1610612744,GSW,Golden State,203110,Draymond Green,6.0,13.0,2.0,5.0,2.0,4.0,1.0,10.0,11.0,10.0,3.0,1.0,3.0,5.0,16.0
449622,1610612744,GSW,Golden State,202691,Klay Thompson,2.0,7.0,1.0,3.0,0.0,0.0,0.0,5.0,5.0,2.0,0.0,1.0,2.0,6.0,5.0
449623,1610612744,GSW,Golden State,201939,Stephen Curry,8.0,19.0,3.0,11.0,6.0,8.0,0.0,6.0,6.0,8.0,3.0,0.0,3.0,3.0,25.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
451267,1610612744,GSW,Golden State,2738,Andre Iguodala,2.0,6.0,1.0,4.0,3.0,6.0,0.0,4.0,4.0,3.0,1.0,0.0,0.0,2.0,8.0
451268,1610612744,GSW,Golden State,2571,Leandro Barbosa,0.0,3.0,0.0,0.0,0.0,0.0,2.0,2.0,4.0,0.0,0.0,0.0,0.0,1.0,0.0
451269,1610612744,GSW,Golden State,203105,Festus Ezeli,0.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0
451270,1610612744,GSW,Golden State,2733,Shaun Livingston,1.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,2.0
451271,1610612744,GSW,Golden State,201578,Marreese Speights,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [182]:
playoffs_by_player_15 = filtered_playoffs_15.groupby(['PLAYER_NAME']).agg({'TEAM_ID': 'last', 'TEAM_ABBREVIATION': 'last', 'TEAM_CITY': 'last', 'PLAYER_ID': 'last',
                                                            '2pointer_MADE': 'sum', '2pointer_ATTEMPTS': 'sum',
                                                            '3pointer_MADE': 'sum', '3pointer_ATTEMPTS': 'sum', 'FreeThrow_MADE': 'sum', 
                                                            'FreeThrow_ATTEMPTS': 'sum', 'OFFENSIVE_REBOUNDS': 'sum', 
                                                            'DEFENSIVE_REBOUNDS': 'sum', 'REBOUNDS_TOTAL': 'sum', 'ASSISTS': 'sum',
                                                            'STEALS': 'sum', 'BLOCKS': 'sum', 'TURNOVERS': 'sum', 'PERSONAL_FOULS': 'sum', 
                                                            'POINTS': 'sum'}).reset_index()
playoffs_by_player_15

,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,Aaron Brooks,1610612741,CHI,Chicago,201166,21.0,61.0,8.0,26.0,4.0,7.0,3.0,15.0,18.0,11.0,3.0,1.0,9.0,16.0,54.0
1,Al Horford,1610612737,ATL,Atlanta,201143,107.0,211.0,2.0,9.0,15.0,20.0,40.0,98.0,138.0,59.0,13.0,23.0,25.0,34.0,231.0
2,Al-Farouq Aminu,1610612742,DAL,Dallas,202329,17.0,31.0,7.0,11.0,15.0,19.0,14.0,22.0,36.0,6.0,10.0,8.0,6.0,15.0,56.0
3,Alan Anderson,1610612751,BKN,Brooklyn,101187,25.0,41.0,10.0,16.0,6.0,9.0,2.0,19.0,21.0,7.0,4.0,1.0,8.0,9.0,66.0
4,Alexis Ajinca,1610612740,NOP,New Orleans,201582,4.0,4.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,2.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,Tyson Chandler,1610612742,DAL,Dallas,2199,19.0,29.0,0.0,0.0,13.0,26.0,27.0,27.0,54.0,1.0,3.0,6.0,5.0,16.0,51.0
204,Vince Carter,1610612763,MEM,Memphis,1713,27.0,67.0,7.0,28.0,8.0,9.0,13.0,34.0,47.0,11.0,7.0,2.0,7.0,17.0,69.0
205,Will Bynum,1610612764,WAS,Washington,101198,7.0,14.0,1.0,2.0,4.0,5.0,2.0,1.0,3.0,3.0,2.0,1.0,5.0,6.0,19.0
206,Zach Randolph,1610612763,MEM,Memphis,2216,71.0,168.0,1.0,5.0,29.0,33.0,32.0,61.0,93.0,23.0,6.0,0.0,23.0,37.0,172.0
207,Zaza Pachulia,1610612749,MIL,Milwaukee,2585,16.0,40.0,0.0,0.0,8.0,13.0,11.0,29.0,40.0,9.0,10.0,3.0,5.0,15.0,40.0

In [183]:
filtered_playoffs_16 = Playoffs_16[['TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_CITY', 'PLAYER_ID', 'PLAYER_NAME', '2pointer_MADE', '2pointer_ATTEMPTS',
                        '3pointer_MADE', '3pointer_ATTEMPTS', 'FreeThrow_MADE', 'FreeThrow_ATTEMPTS', 'OFFENSIVE_REBOUNDS', 
                         'DEFENSIVE_REBOUNDS', 'REBOUNDS_TOTAL', 'ASSISTS','STEALS', 'BLOCKS', 'TURNOVERS', 'PERSONAL_FOULS', 'POINTS']]
filtered_playoffs_16

,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
419040,1610612739,CLE,Cleveland,2544,LeBron James,9.0,24.0,1.0,5.0,8.0,10.0,1.0,10.0,11.0,11.0,2.0,3.0,5.0,1.0,27.0
419041,1610612739,CLE,Cleveland,201567,Kevin Love,3.0,9.0,0.0,3.0,3.0,4.0,4.0,10.0,14.0,3.0,2.0,0.0,1.0,2.0,9.0
419042,1610612739,CLE,Cleveland,202684,Tristan Thompson,3.0,3.0,0.0,0.0,3.0,4.0,0.0,3.0,3.0,0.0,0.0,2.0,0.0,4.0,9.0
419043,1610612739,CLE,Cleveland,2747,JR Smith,5.0,13.0,2.0,8.0,0.0,0.0,0.0,4.0,4.0,2.0,1.0,0.0,2.0,3.0,12.0
419044,1610612739,CLE,Cleveland,202681,Kyrie Irving,10.0,23.0,2.0,5.0,4.0,4.0,3.0,3.0,6.0,1.0,1.0,1.0,2.0,3.0,26.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
420935,1610612761,TOR,Toronto,202335,Patrick Patterson,4.0,5.0,1.0,1.0,0.0,0.0,3.0,3.0,6.0,1.0,0.0,1.0,1.0,1.0,9.0
420936,1610612761,TOR,Toronto,201960,DeMarre Carroll,2.0,4.0,0.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,0.0,0.0,1.0,1.0,6.0
420937,1610612761,TOR,Toronto,202687,Bismack Biyombo,1.0,2.0,0.0,0.0,4.0,6.0,1.0,7.0,8.0,0.0,0.0,2.0,2.0,1.0,6.0
420938,1610612761,TOR,Toronto,202709,Cory Joseph,5.0,6.0,1.0,2.0,7.0,8.0,1.0,2.0,3.0,3.0,1.0,0.0,2.0,4.0,18.0
420939,1610612761,TOR,Toronto,203082,Terrence Ross,2.0,8.0,1.0,3.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,2.0,3.0,5.0

In [184]:
playoffs_by_player_16 = filtered_playoffs_16.groupby(['PLAYER_NAME']).agg({'TEAM_ID': 'last', 'TEAM_ABBREVIATION': 'last', 'TEAM_CITY': 'last', 'PLAYER_ID': 'last',
                                                            '2pointer_MADE': 'sum', '2pointer_ATTEMPTS': 'sum',
                                                            '3pointer_MADE': 'sum', '3pointer_ATTEMPTS': 'sum', 'FreeThrow_MADE': 'sum', 
                                                            'FreeThrow_ATTEMPTS': 'sum', 'OFFENSIVE_REBOUNDS': 'sum', 
                                                            'DEFENSIVE_REBOUNDS': 'sum', 'REBOUNDS_TOTAL': 'sum', 'ASSISTS': 'sum',
                                                            'STEALS': 'sum', 'BLOCKS': 'sum', 'TURNOVERS': 'sum', 'PERSONAL_FOULS': 'sum', 
                                                            'POINTS': 'sum'}).reset_index()
playoffs_by_player_16

,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,Aaron Harrison,1610612766,CHA,Charlotte,1626151,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1,Al Horford,1610612737,ATL,Atlanta,201143,54.0,116.0,11.0,28.0,15.0,16.0,13.0,52.0,65.0,31.0,12.0,24.0,17.0,25.0,134.0
2,Al Jefferson,1610612766,CHA,Charlotte,2744,42.0,83.0,0.0,0.0,9.0,13.0,14.0,29.0,43.0,8.0,4.0,3.0,6.0,12.0,93.0
3,Al-Farouq Aminu,1610612757,POR,Portland,202329,56.0,128.0,28.0,70.0,21.0,29.0,23.0,72.0,95.0,20.0,8.0,10.0,21.0,31.0,161.0
4,Allen Crabbe,1610612757,POR,Portland,203459,38.0,73.0,15.0,35.0,14.0,19.0,5.0,27.0,32.0,15.0,7.0,1.0,6.0,23.0,105.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,Wesley Johnson,1610612746,LAC,LA,202325,5.0,14.0,3.0,9.0,3.0,3.0,5.0,13.0,18.0,2.0,1.0,4.0,2.0,6.0,16.0
211,Wesley Matthews,1610612742,DAL,Dallas,202083,20.0,60.0,10.0,35.0,15.0,19.0,4.0,14.0,18.0,6.0,6.0,0.0,4.0,14.0,65.0
212,Xavier Munford,1610612763,MEM,Memphis,204098,9.0,28.0,1.0,8.0,0.0,2.0,1.0,8.0,9.0,10.0,6.0,3.0,5.0,8.0,19.0
213,Zach Randolph,1610612763,MEM,Memphis,2216,23.0,62.0,0.0,0.0,6.0,7.0,15.0,20.0,35.0,7.0,1.0,0.0,7.0,10.0,52.0
214,Zaza Pachulia,1610612742,DAL,Dallas,2585,9.0,24.0,0.0,0.0,15.0,17.0,10.0,17.0,27.0,16.0,3.0,1.0,2.0,13.0,33.0

In [185]:
filtered_playoffs_17 = Playoffs_17[['TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_CITY', 'PLAYER_ID', 'PLAYER_NAME', '2pointer_MADE', '2pointer_ATTEMPTS',
                        '3pointer_MADE', '3pointer_ATTEMPTS', 'FreeThrow_MADE', 'FreeThrow_ATTEMPTS', 'OFFENSIVE_REBOUNDS', 
                         'DEFENSIVE_REBOUNDS', 'REBOUNDS_TOTAL', 'ASSISTS','STEALS', 'BLOCKS', 'TURNOVERS', 'PERSONAL_FOULS', 'POINTS']]
filtered_playoffs_17

,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
388624,1610612739,CLE,Cleveland,2544,LeBron James,19.0,30.0,2.0,5.0,1.0,4.0,2.0,11.0,13.0,8.0,2.0,1.0,2.0,3.0,41.0
388625,1610612739,CLE,Cleveland,201567,Kevin Love,2.0,8.0,0.0,3.0,2.0,5.0,3.0,7.0,10.0,2.0,0.0,1.0,0.0,2.0,6.0
388626,1610612739,CLE,Cleveland,202684,Tristan Thompson,6.0,8.0,0.0,0.0,3.0,4.0,4.0,4.0,8.0,3.0,1.0,1.0,3.0,1.0,15.0
388627,1610612739,CLE,Cleveland,2747,JR Smith,9.0,11.0,7.0,8.0,0.0,1.0,0.0,3.0,3.0,1.0,0.0,2.0,0.0,2.0,25.0
388628,1610612739,CLE,Cleveland,202681,Kyrie Irving,9.0,22.0,1.0,2.0,7.0,7.0,1.0,1.0,2.0,6.0,2.0,0.0,4.0,3.0,26.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390356,1610612761,TOR,Toronto,1626181,Norman Powell,2.0,4.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,5.0
390357,1610612761,TOR,Toronto,1627832,Fred VanVleet,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
390358,1610612761,TOR,Toronto,1626153,Delon Wright,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
390359,1610612761,TOR,Toronto,1627751,Jakob Poeltl,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
390360,1610612761,TOR,Toronto,203512,Lucas Nogueira,0.0,1.0,0.0,0.0,1.0,2.0,2.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,1.0

In [186]:
playoffs_by_player_17 = filtered_playoffs_17.groupby(['PLAYER_NAME']).agg({'TEAM_ID': 'last', 'TEAM_ABBREVIATION': 'last', 'TEAM_CITY': 'last', 'PLAYER_ID': 'last',
                                                            '2pointer_MADE': 'sum', '2pointer_ATTEMPTS': 'sum',
                                                            '3pointer_MADE': 'sum', '3pointer_ATTEMPTS': 'sum', 'FreeThrow_MADE': 'sum', 
                                                            'FreeThrow_ATTEMPTS': 'sum', 'OFFENSIVE_REBOUNDS': 'sum', 
                                                            'DEFENSIVE_REBOUNDS': 'sum', 'REBOUNDS_TOTAL': 'sum', 'ASSISTS': 'sum',
                                                            'STEALS': 'sum', 'BLOCKS': 'sum', 'TURNOVERS': 'sum', 'PERSONAL_FOULS': 'sum', 
                                                            'POINTS': 'sum'}).reset_index()
playoffs_by_player_17

,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,Aaron Brooks,1610612754,IND,Indiana,201166,2.0,3.0,1.0,2.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,5.0
1,Al Horford,1610612738,BOS,Boston,201143,111.0,190.0,27.0,52.0,22.0,29.0,31.0,87.0,118.0,97.0,15.0,14.0,33.0,33.0,271.0
2,Al-Farouq Aminu,1610612757,POR,Portland,202329,17.0,37.0,7.0,17.0,7.0,11.0,5.0,21.0,26.0,4.0,3.0,4.0,9.0,9.0,48.0
3,Alex Abrines,1610612760,OKC,Oklahoma City,203518,8.0,23.0,5.0,17.0,3.0,4.0,2.0,7.0,9.0,4.0,0.0,0.0,0.0,8.0,24.0
4,Allen Crabbe,1610612757,POR,Portland,203459,9.0,24.0,3.0,13.0,1.0,3.0,0.0,12.0,12.0,2.0,1.0,0.0,1.0,9.0,22.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,Wade Baldwin IV,1610612763,MEM,Memphis,1627735,0.0,1.0,0.0,0.0,2.0,2.0,1.0,3.0,4.0,2.0,0.0,0.0,0.0,3.0,2.0
211,Wayne Selden,1610612763,MEM,Memphis,1627782,9.0,26.0,2.0,11.0,3.0,4.0,3.0,6.0,9.0,7.0,1.0,1.0,2.0,8.0,23.0
212,Wesley Johnson,1610612746,LAC,LA,202325,0.0,0.0,0.0,0.0,1.0,2.0,0.0,2.0,2.0,0.0,1.0,0.0,0.0,2.0,1.0
213,Zach Randolph,1610612763,MEM,Memphis,2216,35.0,83.0,1.0,7.0,8.0,11.0,9.0,40.0,49.0,4.0,5.0,2.0,7.0,14.0,79.0
214,Zaza Pachulia,1610612744,GSW,Golden State,2585,32.0,60.0,0.0,1.0,13.0,17.0,18.0,39.0,57.0,12.0,8.0,4.0,14.0,32.0,77.0

In [187]:
filtered_playoffs_18 = Playoffs_18[['TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_CITY', 'PLAYER_ID', 'PLAYER_NAME', '2pointer_MADE', '2pointer_ATTEMPTS',
                        '3pointer_MADE', '3pointer_ATTEMPTS', 'FreeThrow_MADE', 'FreeThrow_ATTEMPTS', 'OFFENSIVE_REBOUNDS', 
                         'DEFENSIVE_REBOUNDS', 'REBOUNDS_TOTAL', 'ASSISTS','STEALS', 'BLOCKS', 'TURNOVERS', 'PERSONAL_FOULS', 'POINTS']]
filtered_playoffs_18

,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
358855,1610612744,GSW,Golden State,201142,Kevin Durant,7.0,17.0,0.0,3.0,6.0,6.0,1.0,11.0,12.0,10.0,1.0,3.0,2.0,3.0,20.0
358856,1610612744,GSW,Golden State,203110,Draymond Green,4.0,8.0,1.0,5.0,0.0,0.0,1.0,2.0,3.0,9.0,1.0,3.0,1.0,5.0,9.0
358857,1610612744,GSW,Golden State,201580,JaVale McGee,3.0,4.0,0.0,0.0,0.0,0.0,1.0,2.0,3.0,0.0,0.0,1.0,0.0,1.0,6.0
358858,1610612744,GSW,Golden State,202691,Klay Thompson,4.0,10.0,2.0,5.0,0.0,0.0,0.0,6.0,6.0,0.0,0.0,0.0,2.0,3.0,10.0
358859,1610612744,GSW,Golden State,201939,Stephen Curry,12.0,27.0,7.0,15.0,6.0,6.0,2.0,4.0,6.0,4.0,3.0,3.0,2.0,4.0,37.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360408,1610612755,PHI,Philadelphia,101161,Amir Johnson,3.0,5.0,0.0,0.0,0.0,0.0,2.0,5.0,7.0,2.0,1.0,0.0,1.0,2.0,6.0
360409,1610612755,PHI,Philadelphia,201158,Marco Belinelli,5.0,13.0,2.0,8.0,4.0,5.0,0.0,2.0,2.0,0.0,1.0,0.0,1.0,3.0,16.0
360410,1610612755,PHI,Philadelphia,1628365,Markelle Fultz,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
360411,1610612755,PHI,Philadelphia,1626158,Richaun Holmes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,2.0,0.0
360412,1610612755,PHI,Philadelphia,204456,T.J. McConnell,0.0,1.0,0.0,0.0,2.0,2.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,2.0

In [188]:
playoffs_by_player_18 = filtered_playoffs_18.groupby(['PLAYER_NAME']).agg({'TEAM_ID': 'last', 'TEAM_ABBREVIATION': 'last', 'TEAM_CITY': 'last', 'PLAYER_ID': 'last',
                                                            '2pointer_MADE': 'sum', '2pointer_ATTEMPTS': 'sum',
                                                            '3pointer_MADE': 'sum', '3pointer_ATTEMPTS': 'sum', 'FreeThrow_MADE': 'sum', 
                                                            'FreeThrow_ATTEMPTS': 'sum', 'OFFENSIVE_REBOUNDS': 'sum', 
                                                            'DEFENSIVE_REBOUNDS': 'sum', 'REBOUNDS_TOTAL': 'sum', 'ASSISTS': 'sum',
                                                            'STEALS': 'sum', 'BLOCKS': 'sum', 'TURNOVERS': 'sum', 'PERSONAL_FOULS': 'sum', 
                                                            'POINTS': 'sum'}).reset_index()
playoffs_by_player_18

,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,Aaron Brooks,1610612750,MIN,Minnesota,201166,2.0,3.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
1,Aaron Jackson,1610612745,HOU,Houston,1628935,2.0,4.0,0.0,2.0,1.0,2.0,2.0,2.0,4.0,2.0,0.0,0.0,2.0,2.0,5.0
2,Abdel Nader,1610612738,BOS,Boston,1627846,5.0,15.0,0.0,4.0,2.0,4.0,1.0,2.0,3.0,3.0,1.0,1.0,2.0,2.0,12.0
3,Al Horford,1610612738,BOS,Boston,201143,106.0,196.0,14.0,41.0,49.0,61.0,29.0,116.0,145.0,59.0,17.0,19.0,31.0,36.0,275.0
4,Al-Farouq Aminu,1610612757,POR,Portland,202329,24.0,45.0,12.0,25.0,2.0,2.0,10.0,19.0,29.0,3.0,4.0,1.0,3.0,7.0,62.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,Wade Baldwin IV,1610612757,POR,Portland,1627735,1.0,4.0,1.0,1.0,1.0,2.0,0.0,3.0,3.0,2.0,1.0,1.0,3.0,1.0,4.0
204,Wayne Ellington,1610612748,MIA,Miami,201961,10.0,30.0,10.0,25.0,3.0,3.0,1.0,5.0,6.0,2.0,2.0,1.0,3.0,7.0,33.0
205,Zach Collins,1610612757,POR,Portland,1628380,8.0,22.0,2.0,10.0,2.0,2.0,3.0,7.0,10.0,3.0,1.0,1.0,2.0,9.0,20.0
206,Zaza Pachulia,1610612744,GSW,Golden State,2585,4.0,7.0,0.0,0.0,9.0,12.0,6.0,6.0,12.0,1.0,3.0,1.0,3.0,1.0,17.0
207,Zhou Qi,1610612745,HOU,Houston,1627753,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0

In [189]:
filtered_playoffs_19 = Playoffs_19[['TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_CITY', 'PLAYER_ID', 'PLAYER_NAME', '2pointer_MADE', '2pointer_ATTEMPTS',
                        '3pointer_MADE', '3pointer_ATTEMPTS', 'FreeThrow_MADE', 'FreeThrow_ATTEMPTS', 'OFFENSIVE_REBOUNDS', 
                         'DEFENSIVE_REBOUNDS', 'REBOUNDS_TOTAL', 'ASSISTS','STEALS', 'BLOCKS', 'TURNOVERS', 'PERSONAL_FOULS', 'POINTS']]
filtered_playoffs_19

,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
329157,1610612761,TOR,Toronto,202695,Kawhi Leonard,7.0,16.0,1.0,5.0,7.0,8.0,1.0,5.0,6.0,3.0,2.0,1.0,2.0,4.0,22.0
329158,1610612761,TOR,Toronto,1627783,Pascal Siakam,10.0,17.0,3.0,6.0,3.0,4.0,2.0,8.0,10.0,3.0,1.0,1.0,2.0,2.0,26.0
329159,1610612761,TOR,Toronto,201188,Marc Gasol,0.0,5.0,0.0,2.0,3.0,4.0,3.0,6.0,9.0,4.0,0.0,0.0,1.0,4.0,3.0
329160,1610612761,TOR,Toronto,201980,Danny Green,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,3.0,1.0,0.0,1.0,1.0,0.0
329161,1610612761,TOR,Toronto,200768,Kyle Lowry,9.0,16.0,4.0,7.0,4.0,6.0,2.0,5.0,7.0,10.0,3.0,0.0,3.0,5.0,26.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
330913,1610612755,PHI,Philadelphia,204456,T.J. McConnell,2.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,1.0,4.0
330914,1610612755,PHI,Philadelphia,203118,Mike Scott,1.0,8.0,1.0,8.0,0.0,0.0,0.0,5.0,5.0,0.0,1.0,0.0,1.0,4.0,3.0
330915,1610612755,PHI,Philadelphia,203613,Jonathon Simmons,2.0,5.0,0.0,2.0,0.0,0.0,1.0,1.0,2.0,0.0,0.0,0.0,0.0,1.0,4.0
330916,1610612755,PHI,Philadelphia,1629015,Zhaire Smith,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
330917,1610612755,PHI,Philadelphia,1628413,Jonah Bolden,1.0,2.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0

In [190]:
playoffs_by_player_19 = filtered_playoffs_19.groupby(['PLAYER_NAME']).agg({'TEAM_ID': 'last', 'TEAM_ABBREVIATION': 'last', 'TEAM_CITY': 'last', 'PLAYER_ID': 'last',
                                                            '2pointer_MADE': 'sum', '2pointer_ATTEMPTS': 'sum',
                                                            '3pointer_MADE': 'sum', '3pointer_ATTEMPTS': 'sum', 'FreeThrow_MADE': 'sum', 
                                                            'FreeThrow_ATTEMPTS': 'sum', 'OFFENSIVE_REBOUNDS': 'sum', 
                                                            'DEFENSIVE_REBOUNDS': 'sum', 'REBOUNDS_TOTAL': 'sum', 'ASSISTS': 'sum',
                                                            'STEALS': 'sum', 'BLOCKS': 'sum', 'TURNOVERS': 'sum', 'PERSONAL_FOULS': 'sum', 
                                                            'POINTS': 'sum'}).reset_index()
playoffs_by_player_19

,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,Aaron Gordon,1610612753,ORL,Orlando,203932,29.0,62.0,8.0,20.0,10.0,19.0,11.0,25.0,36.0,18.0,6.0,1.0,13.0,16.0,76.0
1,Aaron Holiday,1610612754,IND,Indiana,1628988,2.0,5.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,5.0
2,Abdel Nader,1610612760,OKC,Oklahoma City,1627846,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0
3,Al Horford,1610612738,BOS,Boston,201143,46.0,110.0,18.0,44.0,15.0,18.0,13.0,68.0,81.0,40.0,4.0,7.0,19.0,21.0,125.0
4,Al-Farouq Aminu,1610612757,POR,Portland,202329,38.0,109.0,15.0,51.0,27.0,36.0,29.0,71.0,100.0,21.0,9.0,10.0,16.0,34.0,118.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207,Will Barton,1610612743,DEN,Denver,203115,47.0,135.0,15.0,55.0,18.0,26.0,15.0,52.0,67.0,24.0,4.0,9.0,14.0,19.0,127.0
208,Wilson Chandler,1610612746,LAC,LA,201163,5.0,16.0,1.0,10.0,4.0,4.0,0.0,6.0,6.0,2.0,2.0,0.0,3.0,7.0,15.0
209,Zach Collins,1610612757,POR,Portland,1628380,41.0,81.0,7.0,21.0,20.0,25.0,17.0,41.0,58.0,14.0,7.0,21.0,20.0,54.0,109.0
210,Zaza Pachulia,1610612765,DET,Detroit,2585,2.0,6.0,0.0,0.0,1.0,2.0,1.0,8.0,9.0,0.0,0.0,0.0,1.0,3.0,5.0
211,Zhaire Smith,1610612755,PHI,Philadelphia,1629015,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [191]:
filtered_playoffs_20 = Playoffs_20[['TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_CITY', 'PLAYER_ID', 'PLAYER_NAME', '2pointer_MADE', '2pointer_ATTEMPTS',
                        '3pointer_MADE', '3pointer_ATTEMPTS', 'FreeThrow_MADE', 'FreeThrow_ATTEMPTS', 'OFFENSIVE_REBOUNDS', 
                         'DEFENSIVE_REBOUNDS', 'REBOUNDS_TOTAL', 'ASSISTS','STEALS', 'BLOCKS', 'TURNOVERS', 'PERSONAL_FOULS', 'POINTS']]
filtered_playoffs_20

,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
49948,1610612747,LAL,Los Angeles,2544,LeBron James,13.0,20.0,1.0,5.0,1.0,4.0,3.0,11.0,14.0,10.0,1.0,0.0,1.0,3.0,28.0
49949,1610612747,LAL,Los Angeles,201980,Danny Green,4.0,10.0,3.0,7.0,0.0,0.0,2.0,3.0,5.0,1.0,0.0,1.0,0.0,2.0,11.0
49950,1610612747,LAL,Los Angeles,203076,Anthony Davis,7.0,17.0,0.0,3.0,5.0,7.0,4.0,11.0,15.0,3.0,1.0,2.0,3.0,4.0,19.0
49951,1610612747,LAL,Los Angeles,1627936,Alex Caruso,2.0,7.0,0.0,2.0,0.0,0.0,1.0,2.0,3.0,5.0,1.0,1.0,1.0,2.0,4.0
49952,1610612747,LAL,Los Angeles,203484,Kentavious Caldwell-Pope,6.0,13.0,2.0,7.0,3.0,3.0,1.0,1.0,2.0,0.0,1.0,0.0,2.0,5.0,17.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51637,1610612746,LAC,LA,1626149,Montrezl Harrell,2.0,5.0,0.0,0.0,2.0,4.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,6.0
51638,1610612746,LAC,LA,202704,Reggie Jackson,0.0,5.0,0.0,1.0,0.0,0.0,0.0,3.0,3.0,1.0,0.0,0.0,0.0,2.0,0.0
51639,1610612746,LAC,LA,203210,JaMychal Green,2.0,3.0,1.0,2.0,0.0,0.0,1.0,1.0,2.0,0.0,0.0,1.0,0.0,3.0,5.0
51640,1610612746,LAC,LA,1629013,Landry Shamet,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
51641,1610612746,LAC,LA,1629611,Terance Mann,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [192]:
playoffs_by_player_20 = filtered_playoffs_20.groupby(['PLAYER_NAME']).agg({'TEAM_ID': 'last', 'TEAM_ABBREVIATION': 'last', 'TEAM_CITY': 'last', 'PLAYER_ID': 'last',
                                                            '2pointer_MADE': 'sum', '2pointer_ATTEMPTS': 'sum',
                                                            '3pointer_MADE': 'sum', '3pointer_ATTEMPTS': 'sum', 'FreeThrow_MADE': 'sum', 
                                                            'FreeThrow_ATTEMPTS': 'sum', 'OFFENSIVE_REBOUNDS': 'sum', 
                                                            'DEFENSIVE_REBOUNDS': 'sum', 'REBOUNDS_TOTAL': 'sum', 'ASSISTS': 'sum',
                                                            'STEALS': 'sum', 'BLOCKS': 'sum', 'TURNOVERS': 'sum', 'PERSONAL_FOULS': 'sum', 
                                                            'POINTS': 'sum'}).reset_index()
playoffs_by_player_20

,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,Aaron Holiday,1610612754,IND,Indiana,1628988,12.0,21.0,4.0,9.0,3.0,5.0,1.0,4.0,5.0,10.0,4.0,0.0,4.0,10.0,31.0
1,Abdel Nader,1610612760,OKC,Oklahoma City,1627846,1.0,7.0,1.0,5.0,1.0,2.0,1.0,2.0,3.0,0.0,1.0,2.0,0.0,1.0,4.0
2,Al Horford,1610612755,PHI,Philadelphia,201143,12.0,25.0,0.0,4.0,4.0,7.0,9.0,20.0,29.0,9.0,1.0,5.0,3.0,14.0,28.0
3,Alec Burks,1610612755,PHI,Philadelphia,202692,16.0,49.0,3.0,16.0,7.0,9.0,7.0,8.0,15.0,7.0,1.0,3.0,3.0,7.0,42.0
4,Alex Caruso,1610612747,LAL,Los Angeles,1627936,48.0,113.0,17.0,61.0,24.0,30.0,15.0,33.0,48.0,59.0,23.0,12.0,31.0,55.0,137.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,Victor Oladipo,1610612754,IND,Indiana,203506,22.0,56.0,12.0,33.0,15.0,16.0,0.0,13.0,13.0,10.0,9.0,0.0,14.0,14.0,71.0
213,Vincent Poirier,1610612738,BOS,Boston,1629738,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
214,Wenyen Gabriel,1610612757,POR,Portland,1629117,9.0,15.0,2.0,5.0,1.0,2.0,7.0,3.0,10.0,4.0,2.0,2.0,5.0,16.0,21.0
215,Wes Iwundu,1610612753,ORL,Orlando,1628411,6.0,20.0,4.0,7.0,5.0,8.0,1.0,10.0,11.0,4.0,3.0,2.0,3.0,5.0,21.0
216,Wesley Matthews,1610612749,MIL,Milwaukee,202083,24.0,57.0,17.0,43.0,7.0,10.0,6.0,12.0,18.0,9.0,9.0,4.0,7.0,20.0,72.0

In [193]:
filtered_playoffs_21 = Playoffs_21[['TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_CITY', 'PLAYER_ID', 'PLAYER_NAME', '2pointer_MADE', '2pointer_ATTEMPTS',
                        '3pointer_MADE', '3pointer_ATTEMPTS', 'FreeThrow_MADE', 'FreeThrow_ATTEMPTS', 'OFFENSIVE_REBOUNDS', 
                         'DEFENSIVE_REBOUNDS', 'REBOUNDS_TOTAL', 'ASSISTS','STEALS', 'BLOCKS', 'TURNOVERS', 'PERSONAL_FOULS', 'POINTS']]
filtered_playoffs_21

,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
23291,1610612756,PHX,Phoenix,1628969,Mikal Bridges,3.0,7.0,0.0,1.0,1.0,2.0,1.0,5.0,6.0,2.0,2.0,0.0,0.0,4.0,7.0
23292,1610612756,PHX,Phoenix,203109,Jae Crowder,4.0,11.0,2.0,9.0,5.0,5.0,2.0,11.0,13.0,0.0,4.0,1.0,2.0,3.0,15.0
23293,1610612756,PHX,Phoenix,1629028,Deandre Ayton,4.0,12.0,0.0,0.0,4.0,5.0,1.0,5.0,6.0,1.0,2.0,2.0,2.0,5.0,12.0
23294,1610612756,PHX,Phoenix,1626164,Devin Booker,8.0,22.0,0.0,7.0,3.0,3.0,0.0,3.0,3.0,5.0,0.0,0.0,6.0,4.0,19.0
23295,1610612756,PHX,Phoenix,101108,Chris Paul,11.0,19.0,1.0,2.0,3.0,4.0,1.0,1.0,2.0,5.0,1.0,0.0,3.0,5.0,26.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25150,1610612743,DEN,Denver,1630267,Facundo Campazzo,3.0,4.0,2.0,3.0,0.0,0.0,2.0,1.0,3.0,5.0,2.0,1.0,1.0,3.0,8.0
25151,1610612743,DEN,Denver,1628420,Monte Morris,5.0,10.0,0.0,1.0,0.0,0.0,0.0,2.0,2.0,5.0,0.0,0.0,1.0,4.0,10.0
25152,1610612743,DEN,Denver,203210,JaMychal Green,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,3.0,0.0,1.0,0.0,2.0,0.0
25153,1610612743,DEN,Denver,1630210,Markus Howard,3.0,5.0,1.0,3.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,7.0
25154,1610612743,DEN,Denver,200794,Paul Millsap,1.0,3.0,1.0,2.0,0.0,0.0,0.0,3.0,3.0,4.0,1.0,0.0,2.0,2.0,3.0

In [194]:
playoffs_by_player_21 = filtered_playoffs_21.groupby(['PLAYER_NAME']).agg({'TEAM_ID': 'last', 'TEAM_ABBREVIATION': 'last', 'TEAM_CITY': 'last', 'PLAYER_ID': 'last',
                                                            '2pointer_MADE': 'sum', '2pointer_ATTEMPTS': 'sum',
                                                            '3pointer_MADE': 'sum', '3pointer_ATTEMPTS': 'sum', 'FreeThrow_MADE': 'sum', 
                                                            'FreeThrow_ATTEMPTS': 'sum', 'OFFENSIVE_REBOUNDS': 'sum', 
                                                            'DEFENSIVE_REBOUNDS': 'sum', 'REBOUNDS_TOTAL': 'sum', 'ASSISTS': 'sum',
                                                            'STEALS': 'sum', 'BLOCKS': 'sum', 'TURNOVERS': 'sum', 'PERSONAL_FOULS': 'sum', 
                                                            'POINTS': 'sum'}).reset_index()
playoffs_by_player_21

,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,2pointer_MADE,2pointer_ATTEMPTS,3pointer_MADE,3pointer_ATTEMPTS,FreeThrow_MADE,FreeThrow_ATTEMPTS,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,Aaron Gordon,1610612743,DEN,Denver,203932,43.0,99.0,9.0,23.0,16.0,25.0,21.0,33.0,54.0,20.0,5.0,3.0,14.0,23.0,111.0
1,Aaron Nesmith,1610612738,BOS,Boston,1630174,5.0,18.0,4.0,14.0,2.0,2.0,2.0,11.0,13.0,1.0,1.0,1.0,2.0,7.0,16.0
2,Abdel Nader,1610612756,PHX,Phoenix,1627846,2.0,6.0,0.0,2.0,0.0,0.0,0.0,5.0,5.0,0.0,0.0,0.0,0.0,3.0,4.0
3,Alec Burks,1610612752,NYK,New York,202692,24.0,56.0,8.0,24.0,14.0,19.0,5.0,20.0,25.0,13.0,1.0,0.0,4.0,11.0,70.0
4,Alex Caruso,1610612747,LAL,Los Angeles,1627936,14.0,38.0,5.0,17.0,2.0,2.0,2.0,6.0,8.0,3.0,1.0,4.0,7.0,12.0,35.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,Will Barton,1610612743,DEN,Denver,203115,19.0,43.0,7.0,21.0,4.0,4.0,1.0,12.0,13.0,8.0,2.0,1.0,4.0,4.0,49.0
236,Willie Cauley-Stein,1610612742,DAL,Dallas,1626161,6.0,9.0,0.0,0.0,3.0,3.0,3.0,13.0,16.0,3.0,2.0,4.0,3.0,8.0,15.0
237,Xavier Tillman,1610612763,MEM,Memphis,1630214,1.0,5.0,0.0,1.0,0.0,0.0,1.0,2.0,3.0,1.0,1.0,0.0,1.0,2.0,2.0
238,Yogi Ferrell,1610612746,LAC,LA,1627812,2.0,5.0,0.0,1.0,0.0,0.0,0.0,3.0,3.0,3.0,0.0,0.0,0.0,0.0,4.0
239,Zeke Nnaji,1610612743,DEN,Denver,1630192,4.0,8.0,3.0,7.0,1.0,2.0,1.0,1.0,2.0,2.0,1.0,0.0,0.0,1.0,12.0

In [195]:
# Playoffs_21.columns

In [196]:
# Testing out if we can use the percentages columns

filtered_playoffs_21test = Playoffs_21[['TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_CITY', 'PLAYER_ID', 'PLAYER_NAME', '2pointer_MADE', '2pointer_ATTEMPTS',
                        '2pointer_PCT', '3pointer_MADE', '3pointer_ATTEMPTS', '3pointer_PCT', 'FreeThrow_MADE', 'FreeThrow_ATTEMPTS', 'FreeThrow_PCT', 
                        'OFFENSIVE_REBOUNDS', 'DEFENSIVE_REBOUNDS', 'REBOUNDS_TOTAL', 'ASSISTS','STEALS', 'BLOCKS', 'TURNOVERS', 'PERSONAL_FOULS', 'POINTS']]
filtered_playoffs_21test

,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,2pointer_MADE,2pointer_ATTEMPTS,2pointer_PCT,3pointer_MADE,3pointer_ATTEMPTS,...,FreeThrow_PCT,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
23291,1610612756,PHX,Phoenix,1628969,Mikal Bridges,3.0,7.0,0.429,0.0,1.0,...,0.50,1.0,5.0,6.0,2.0,2.0,0.0,0.0,4.0,7.0
23292,1610612756,PHX,Phoenix,203109,Jae Crowder,4.0,11.0,0.364,2.0,9.0,...,1.00,2.0,11.0,13.0,0.0,4.0,1.0,2.0,3.0,15.0
23293,1610612756,PHX,Phoenix,1629028,Deandre Ayton,4.0,12.0,0.333,0.0,0.0,...,0.80,1.0,5.0,6.0,1.0,2.0,2.0,2.0,5.0,12.0
23294,1610612756,PHX,Phoenix,1626164,Devin Booker,8.0,22.0,0.364,0.0,7.0,...,1.00,0.0,3.0,3.0,5.0,0.0,0.0,6.0,4.0,19.0
23295,1610612756,PHX,Phoenix,101108,Chris Paul,11.0,19.0,0.579,1.0,2.0,...,0.75,1.0,1.0,2.0,5.0,1.0,0.0,3.0,5.0,26.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25150,1610612743,DEN,Denver,1630267,Facundo Campazzo,3.0,4.0,0.750,2.0,3.0,...,0.00,2.0,1.0,3.0,5.0,2.0,1.0,1.0,3.0,8.0
25151,1610612743,DEN,Denver,1628420,Monte Morris,5.0,10.0,0.500,0.0,1.0,...,0.00,0.0,2.0,2.0,5.0,0.0,0.0,1.0,4.0,10.0
25152,1610612743,DEN,Denver,203210,JaMychal Green,0.0,1.0,0.000,0.0,1.0,...,0.00,0.0,1.0,1.0,3.0,0.0,1.0,0.0,2.0,0.0
25153,1610612743,DEN,Denver,1630210,Markus Howard,3.0,5.0,0.600,1.0,3.0,...,0.00,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,7.0
25154,1610612743,DEN,Denver,200794,Paul Millsap,1.0,3.0,0.333,1.0,2.0,...,0.00,0.0,3.0,3.0,4.0,1.0,0.0,2.0,2.0,3.0

In [197]:
# Testing out if we can include the percentage columns

playoffs_by_player_21test = filtered_playoffs_21test.groupby(['PLAYER_NAME']).agg({'TEAM_ID': 'last', 'TEAM_ABBREVIATION': 'last', 'TEAM_CITY': 'last', 'PLAYER_ID': 'last',
                                                            '2pointer_MADE': 'sum', '2pointer_ATTEMPTS': 'sum', '2pointer_PCT': 'mean',
                                                            '3pointer_MADE': 'sum', '3pointer_ATTEMPTS': 'sum', '3pointer_PCT': 'mean', 'FreeThrow_MADE': 'sum', 
                                                            'FreeThrow_ATTEMPTS': 'sum', 'FreeThrow_PCT': 'mean', 'OFFENSIVE_REBOUNDS': 'sum', 
                                                            'DEFENSIVE_REBOUNDS': 'sum', 'REBOUNDS_TOTAL': 'sum', 'ASSISTS': 'sum',
                                                            'STEALS': 'sum', 'BLOCKS': 'sum', 'TURNOVERS': 'sum', 'PERSONAL_FOULS': 'sum', 
                                                            'POINTS': 'sum'}).reset_index()
playoffs_by_player_21test

,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,2pointer_MADE,2pointer_ATTEMPTS,2pointer_PCT,3pointer_MADE,3pointer_ATTEMPTS,...,FreeThrow_PCT,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,REBOUNDS_TOTAL,ASSISTS,STEALS,BLOCKS,TURNOVERS,PERSONAL_FOULS,POINTS
0,Aaron Gordon,1610612743,DEN,Denver,203932,43.0,99.0,0.423200,9.0,23.0,...,0.505000,21.0,33.0,54.0,20.0,5.0,3.0,14.0,23.0,111.0
1,Aaron Nesmith,1610612738,BOS,Boston,1630174,5.0,18.0,0.173400,4.0,14.0,...,0.200000,2.0,11.0,13.0,1.0,1.0,1.0,2.0,7.0,16.0
2,Abdel Nader,1610612756,PHX,Phoenix,1627846,2.0,6.0,0.100000,0.0,2.0,...,0.000000,0.0,5.0,5.0,0.0,0.0,0.0,0.0,3.0,4.0
3,Alec Burks,1610612752,NYK,New York,202692,24.0,56.0,0.416600,8.0,24.0,...,0.750000,5.0,20.0,25.0,13.0,1.0,0.0,4.0,11.0,70.0
4,Alex Caruso,1610612747,LAL,Los Angeles,1627936,14.0,38.0,0.367000,5.0,17.0,...,0.166667,2.0,6.0,8.0,3.0,1.0,4.0,7.0,12.0,35.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,Will Barton,1610612743,DEN,Denver,203115,19.0,43.0,0.452667,7.0,21.0,...,0.333333,1.0,12.0,13.0,8.0,2.0,1.0,4.0,4.0,49.0
236,Willie Cauley-Stein,1610612742,DAL,Dallas,1626161,6.0,9.0,0.500000,0.0,0.0,...,0.166667,3.0,13.0,16.0,3.0,2.0,4.0,3.0,8.0,15.0
237,Xavier Tillman,1610612763,MEM,Memphis,1630214,1.0,5.0,0.333333,0.0,1.0,...,0.000000,1.0,2.0,3.0,1.0,1.0,0.0,1.0,2.0,2.0
238,Yogi Ferrell,1610612746,LAC,LA,1627812,2.0,5.0,0.166667,0.0,1.0,...,0.000000,0.0,3.0,3.0,3.0,0.0,0.0,0.0,0.0,4.0
239,Zeke Nnaji,1610612743,DEN,Denver,1630192,4.0,8.0,0.600000,3.0,7.0,...,0.100000,1.0,1.0,2.0,2.0,1.0,0.0,0.0,1.0,12.0

In [ ]:
All_seasons_player_df
All_playoffs_by_player_df

In [198]:
player_attributes = pd.read_csv('../Resources/Player_attributes.csv')
player_attributes

,Unnamed: 0,PLAYER_NAME,BIRTHDATE,AGE,SCHOOL,COUNTRY,HEIGHT,WEIGHT,SEASON_EXP,TEAM_ID,FIRST_SEASON,LAST_SEASON,DRAFT_YEAR,DRAFT_ROUND,DRAFT_NUMBER
0,0,Alaa Abdelnaby,1968-06-24,53,Duke,USA,82.0,240.0,4,1610612757,1990,1994,1990,1,25
1,1,Zaid Abdul-Aziz,1946-04-07,76,Iowa State,USA,81.0,235.0,9,1610612745,1968,1977,1968,1,5
2,2,Kareem Abdul-Jabbar,1947-04-16,75,UCLA,USA,86.0,225.0,19,1610612747,1969,1988,1969,1,1
3,3,Mahmoud Abdul-Rauf,1969-03-09,53,Louisiana State,USA,73.0,162.0,8,1610612743,1990,2000,1990,1,3
4,4,Tariq Abdul-Wahad,1974-11-03,47,San Jose State,France,78.0,235.0,6,1610612758,1997,2003,1997,1,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4261,4494,Paul Zipser,1994-02-18,28,Bayern Munich,Germany,80.0,226.0,1,1610612741,2016,2017,2016,2,48
4262,4495,Ante Zizic,1997-01-04,25,,Croatia,82.0,266.0,3,1610612739,2017,2019,2016,1,23
4263,4496,Jim Zoet,1953-12-30,68,Kent State,USA,85.0,240.0,0,1610612765,1982,1982,0,0,0
4264,4497,Bill Zopf,1948-06-07,73,Duquesne,USA,73.0,170.0,0,1610612749,1970,1970,1970,2,33
4265,4498,Ivica Zubac,1997-03-18,25,Mega Basket,Croatia,84.0,240.0,4,1610612746,2016,2020,2016,2,32

In [201]:
player_attributes = player_attributes.drop(columns = ['Unnamed: 0'])
player_attributes

,PLAYER_NAME,BIRTHDATE,AGE,SCHOOL,COUNTRY,HEIGHT,WEIGHT,SEASON_EXP,TEAM_ID,FIRST_SEASON,LAST_SEASON,DRAFT_YEAR,DRAFT_ROUND,DRAFT_NUMBER
0,Alaa Abdelnaby,1968-06-24,53,Duke,USA,82.0,240.0,4,1610612757,1990,1994,1990,1,25
1,Zaid Abdul-Aziz,1946-04-07,76,Iowa State,USA,81.0,235.0,9,1610612745,1968,1977,1968,1,5
2,Kareem Abdul-Jabbar,1947-04-16,75,UCLA,USA,86.0,225.0,19,1610612747,1969,1988,1969,1,1
3,Mahmoud Abdul-Rauf,1969-03-09,53,Louisiana State,USA,73.0,162.0,8,1610612743,1990,2000,1990,1,3
4,Tariq Abdul-Wahad,1974-11-03,47,San Jose State,France,78.0,235.0,6,1610612758,1997,2003,1997,1,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4261,Paul Zipser,1994-02-18,28,Bayern Munich,Germany,80.0,226.0,1,1610612741,2016,2017,2016,2,48
4262,Ante Zizic,1997-01-04,25,,Croatia,82.0,266.0,3,1610612739,2017,2019,2016,1,23
4263,Jim Zoet,1953-12-30,68,Kent State,USA,85.0,240.0,0,1610612765,1982,1982,0,0,0
4264,Bill Zopf,1948-06-07,73,Duquesne,USA,73.0,170.0,0,1610612749,1970,1970,1970,2,33
4265,Ivica Zubac,1997-03-18,25,Mega Basket,Croatia,84.0,240.0,4,1610612746,2016,2020,2016,2,32